//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/13/2025 at 14:24:28
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :i2c_master_top.mw
// Cell Name    :i2c_master_top
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./outputs/i2c_master_top_extracted.v
//


module i2c_master_bit_ctrl_DW01_dec_0_DW01_dec_1 (SUM , A );
output [15:0] SUM ;
input  [15:0] A ;



INVX1_RVT U3 (.A ( n27 ) , .Y ( n2 ) ) ;
INVX1_RVT U2 (.A ( n26 ) , .Y ( n3 ) ) ;
INVX1_RVT U1 (.A ( n25 ) , .Y ( n4 ) ) ;
INVX1_RVT U11 (.A ( n21 ) , .Y ( n11 ) ) ;
INVX1_RVT U10 (.A ( n20 ) , .Y ( n10 ) ) ;
INVX1_RVT U9 (.A ( n19 ) , .Y ( n9 ) ) ;
INVX1_RVT U8 (.A ( n18 ) , .Y ( n8 ) ) ;
INVX1_RVT U7 (.A ( n17 ) , .Y ( n7 ) ) ;
INVX1_RVT U6 (.A ( n15 ) , .Y ( n6 ) ) ;
INVX1_RVT U5 (.A ( n16 ) , .Y ( n5 ) ) ;
INVX1_RVT U4 (.A ( n28 ) , .Y ( n1 ) ) ;
AO21X1_RVT U19 (.A1 ( A[5] ) , .Y ( SUM[5] ) , .A2 ( n20 ) , .A3 ( n9 ) ) ;
AO21X1_RVT U18 (.A1 ( A[6] ) , .Y ( SUM[6] ) , .A2 ( n19 ) , .A3 ( n8 ) ) ;
AO21X1_RVT U17 (.A1 ( A[7] ) , .Y ( SUM[7] ) , .A2 ( n18 ) , .A3 ( n7 ) ) ;
AO21X1_RVT U16 (.A1 ( A[8] ) , .Y ( SUM[8] ) , .A2 ( n17 ) , .A3 ( n6 ) ) ;
AO21X1_RVT U15 (.A1 ( A[9] ) , .Y ( SUM[9] ) , .A2 ( n15 ) , .A3 ( n5 ) ) ;
INVX1_RVT U14 (.A ( A[0] ) , .Y ( SUM[0] ) ) ;
INVX1_RVT U13 (.A ( n23 ) , .Y ( n13 ) ) ;
INVX1_RVT U12 (.A ( n22 ) , .Y ( n12 ) ) ;
AO21X1_RVT U27 (.A1 ( A[13] ) , .Y ( SUM[13] ) , .A2 ( n26 ) , .A3 ( n4 ) ) ;
XOR2X1_RVT U26 (.Y ( SUM[14] ) , .A2 ( n4 ) , .A1 ( A[14] ) ) ;
OR2X1_RVT U25 (.Y ( n24 ) , .A2 ( A[14] ) , .A1 ( n25 ) ) ;
XNOR2X1_RVT U24 (.A2 ( A[15] ) , .A1 ( n24 ) , .Y ( SUM[15] ) ) ;
AO21X1_RVT U23 (.A1 ( A[1] ) , .Y ( SUM[1] ) , .A2 ( A[0] ) , .A3 ( n13 ) ) ;
AO21X1_RVT U22 (.A1 ( A[2] ) , .Y ( SUM[2] ) , .A2 ( n23 ) , .A3 ( n12 ) ) ;
AO21X1_RVT U21 (.A1 ( A[3] ) , .Y ( SUM[3] ) , .A2 ( n22 ) , .A3 ( n11 ) ) ;
AO21X1_RVT U20 (.A1 ( A[4] ) , .Y ( SUM[4] ) , .A2 ( n21 ) , .A3 ( n10 ) ) ;
OR2X1_RVT U35 (.Y ( n16 ) , .A2 ( A[9] ) , .A1 ( n15 ) ) ;
OR2X1_RVT U34 (.Y ( n28 ) , .A2 ( A[10] ) , .A1 ( n16 ) ) ;
AO21X1_RVT U33 (.A1 ( A[10] ) , .Y ( SUM[10] ) , .A2 ( n16 ) , .A3 ( n1 ) ) ;
OR2X1_RVT U32 (.Y ( n27 ) , .A2 ( A[11] ) , .A1 ( n28 ) ) ;
AO21X1_RVT U31 (.A1 ( A[11] ) , .Y ( SUM[11] ) , .A2 ( n28 ) , .A3 ( n2 ) ) ;
OR2X1_RVT U30 (.Y ( n26 ) , .A2 ( A[12] ) , .A1 ( n27 ) ) ;
AO21X1_RVT U29 (.A1 ( A[12] ) , .Y ( SUM[12] ) , .A2 ( n27 ) , .A3 ( n3 ) ) ;
OR2X1_RVT U28 (.Y ( n25 ) , .A2 ( A[13] ) , .A1 ( n26 ) ) ;
OR2X1_RVT U43 (.Y ( n23 ) , .A2 ( A[0] ) , .A1 ( A[1] ) ) ;
OR2X1_RVT U42 (.Y ( n22 ) , .A2 ( A[2] ) , .A1 ( n23 ) ) ;
OR2X1_RVT U41 (.Y ( n21 ) , .A2 ( A[3] ) , .A1 ( n22 ) ) ;
OR2X1_RVT U40 (.Y ( n20 ) , .A2 ( A[4] ) , .A1 ( n21 ) ) ;
OR2X1_RVT U39 (.Y ( n19 ) , .A2 ( A[5] ) , .A1 ( n20 ) ) ;
OR2X1_RVT U38 (.Y ( n18 ) , .A2 ( A[6] ) , .A1 ( n19 ) ) ;
OR2X1_RVT U37 (.Y ( n17 ) , .A2 ( A[7] ) , .A1 ( n18 ) ) ;
OR2X1_RVT U36 (.Y ( n15 ) , .A2 ( A[8] ) , .A1 ( n17 ) ) ;
endmodule




module i2c_master_bit_ctrl (scl_oen , sda_o , sda_oen , IN0 , IN1 , 
    IN2 , din , scl_i , sda_i , cmd_ack , busy , al , dout , scl_o , 
    cmd , clk , rst , nReset , ena , clk_cnt );
output scl_oen ;
output sda_o ;
output sda_oen ;
input  IN0 ;
input  IN1 ;
input  IN2 ;
input  din ;
input  scl_i ;
input  sda_i ;
output cmd_ack ;
output busy ;
output al ;
output dout ;
output scl_o ;
input  [3:0] cmd ;
input  clk ;
input  rst ;
input  nReset ;
input  ena ;
input  [15:0] clk_cnt ;

wire [15:0] cnt ;



i2c_master_bit_ctrl_DW01_dec_0_DW01_dec_1 sub_219 (
    .SUM ( {N47 , N46 , N45 , N44 , N43 , N42 , N41 , N40 , N39 , N38 , 
	N37 , N36 , N35 , N34 , N33 , N32 } ) , 
    .A ( cnt ) ) ;

INVX2_RVT U4 (.A ( n25 ) , .Y ( n39 ) ) ;
INVX2_RVT U3 (.A ( n66 ) , .Y ( n38 ) ) ;
INVX2_RVT U2 (.A ( n29 ) , .Y ( n37 ) ) ;
INVX2_RVT U1 (.A ( n12 ) , .Y ( n36 ) ) ;
OR4X1_RVT U71 (.A4 ( n94 ) , .A3 ( n93 ) , .A1 ( n91 ) , .Y ( n90 ) , .A2 ( n92 ) ) ;
NAND4X0_RVT U72 (.A2 ( n109 ) , .A4 ( n111 ) , .A3 ( n110 ) , .Y ( n94 ) 
    , .A1 ( n108 ) ) ;
NAND4X0_RVT U73 (.A2 ( n113 ) , .A4 ( n115 ) , .A3 ( n114 ) , .Y ( n93 ) 
    , .A1 ( n112 ) ) ;
NAND4X0_RVT U74 (.A2 ( n105 ) , .A4 ( n107 ) , .A3 ( n106 ) , .Y ( n91 ) 
    , .A1 ( n104 ) ) ;
NAND4X0_RVT U75 (.A2 ( n101 ) , .A4 ( n103 ) , .A3 ( n102 ) , .Y ( n92 ) 
    , .A1 ( n100 ) ) ;
OR2X1_RVT U76 (.Y ( N70 ) , .A2 ( IN2 ) , .A1 ( sSDA ) ) ;
NOR3X0_RVT U77 (.Y ( N73 ) , .A1 ( N70 ) , .A3 ( n15 ) , .A2 ( n133 ) ) ;
OR2X1_RVT U78 (.Y ( N67 ) , .A2 ( scl_i ) , .A1 ( IN2 ) ) ;
OR2X1_RVT U79 (.Y ( N68 ) , .A2 ( sda_i ) , .A1 ( IN2 ) ) ;
AOI21X1_RVT U80 (.Y ( n156 ) , .A2 ( n45 ) , .A3 ( IN2 ) , .A1 ( n44 ) ) ;
NAND2X0_RVT U81 (.A2 ( n132 ) , .A1 ( n116 ) , .Y ( n44 ) ) ;
NAND4X0_RVT U82 (.A2 ( n28 ) , .A4 ( n57 ) , .A3 ( n71 ) , .Y ( n45 ) 
    , .A1 ( cmd[1] ) ) ;
AO21X1_RVT U83 (.A1 ( n89 ) , .Y ( N64 ) , .A2 ( n69 ) , .A3 ( IN2 ) ) ;
OR2X1_RVT U84 (.Y ( n89 ) , .A2 ( n97 ) , .A1 ( sSCL ) ) ;
NAND3X0_RVT U85 (.Y ( n8 ) , .A1 ( n126 ) , .A2 ( n63 ) , .A3 ( n117 ) ) ;
NAND4X0_RVT U86 (.A2 ( n129 ) , .A4 ( n84 ) , .A3 ( n83 ) , .Y ( n78 ) 
    , .A1 ( n122 ) ) ;
AND4X1_RVT U87 (.Y ( n84 ) , .A1 ( n118 ) , .A3 ( n120 ) , .A4 ( n121 ) 
    , .A2 ( n119 ) ) ;
NOR3X0_RVT U88 (.Y ( n83 ) , .A1 ( n8 ) , .A3 ( n16 ) , .A2 ( n9 ) ) ;
NAND2X0_RVT U89 (.A2 ( n128 ) , .A1 ( n127 ) , .Y ( n79 ) ) ;
AND3X1_RVT U90 (.A1 ( n124 ) , .Y ( n75 ) , .A2 ( n125 ) , .A3 ( n123 ) ) ;
NAND3X0_RVT U91 (.Y ( n9 ) , .A1 ( n135 ) , .A2 ( n75 ) , .A3 ( n134 ) ) ;
INVX1_RVT U92 (.A ( cmd[3] ) , .Y ( n71 ) ) ;
INVX1_RVT U93 (.A ( cmd[2] ) , .Y ( n76 ) ) ;
INVX1_RVT U94 (.A ( cmd[0] ) , .Y ( n68 ) ) ;
INVX1_RVT U95 (.A ( cmd[1] ) , .Y ( n67 ) ) ;
AO22X1_RVT U96 (.A2 ( dout ) , .A3 ( sSDA ) , .Y ( n131 ) , .A4 ( n50 ) 
    , .A1 ( n1 ) ) ;
INVX1_RVT U97 (.A ( n1 ) , .Y ( n50 ) ) ;
NAND2X0_RVT U98 (.A2 ( n130 ) , .A1 ( sSCL ) , .Y ( n1 ) ) ;
OR3X2_RVT U100 (.A1 ( N69 ) , .A3 ( n56 ) , .Y ( n66 ) , .A2 ( n97 ) ) ;
NAND2X0_RVT U103 (.A2 ( n55 ) , .A1 ( n132 ) , .Y ( n12 ) ) ;
AO22X1_RVT U105 (.A2 ( n24 ) , .A3 ( n34 ) , .Y ( n149 ) , .A4 ( cmd[1] ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U106 (.A2 ( n13 ) , .A3 ( n37 ) , .Y ( n144 ) , .A4 ( n61 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U107 (.A2 ( n3 ) , .A3 ( n37 ) , .Y ( n148 ) , .A4 ( n24 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U108 (.A2 ( n21 ) , .A3 ( n37 ) , .Y ( n143 ) , .A4 ( n13 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U109 (.A2 ( n14 ) , .A3 ( n37 ) , .Y ( n140 ) , .A4 ( n22 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U110 (.A2 ( n62 ) , .A3 ( n37 ) , .Y ( n142 ) , .A4 ( n21 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U111 (.A2 ( n23 ) , .A3 ( n37 ) , .Y ( n139 ) , .A4 ( n14 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U112 (.A2 ( n59 ) , .A3 ( n37 ) , .Y ( n155 ) , .A4 ( n23 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U113 (.A2 ( n65 ) , .A3 ( n37 ) , .Y ( n150 ) , .A4 ( n20 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U114 (.A2 ( n20 ) , .A3 ( n37 ) , .Y ( n151 ) , .A4 ( n6 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U115 (.A2 ( n16 ) , .A3 ( n37 ) , .Y ( n147 ) , .A4 ( n3 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U116 (.A2 ( n36 ) , .A3 ( n37 ) , .Y ( n174 ) , .A4 ( n79 ) 
    , .A1 ( sda_chk ) ) ;
AO22X1_RVT U117 (.A2 ( n6 ) , .A3 ( n37 ) , .Y ( n152 ) , .A4 ( n17 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U118 (.A2 ( n64 ) , .A3 ( n37 ) , .Y ( n146 ) , .A4 ( n16 ) 
    , .A1 ( n36 ) ) ;
AO22X1_RVT U119 (.A2 ( n17 ) , .A3 ( n37 ) , .Y ( n153 ) , .A4 ( n2 ) 
    , .A1 ( n36 ) ) ;
INVX0_RVT U120 (.A ( n10 ) , .Y ( n55 ) ) ;
DFFARX1_RVT \c_state_reg[15] (.QN ( n128 ) , .RSTB ( IN1 ) , .D ( n139 ) 
    , .CLK ( clk ) , .Q ( n23 ) ) ;
DFFX1_RVT dscl_oen_reg (.QN ( n97 ) , .D ( scl_oen ) , .CLK ( clk ) ) ;
DFFASX1_RVT sSCL_reg (.QN ( n15 ) , .D ( N67 ) , .SETB ( IN0 ) , .CLK ( clk ) 
    , .Q ( sSCL ) ) ;
DFFARX1_RVT \cnt_reg[8] (.QN ( n108 ) , .RSTB ( nReset ) , .D ( n164 ) 
    , .CLK ( clk ) , .Q ( cnt[8] ) ) ;
DFFARX1_RVT \cnt_reg[9] (.QN ( n109 ) , .RSTB ( IN0 ) , .D ( n163 ) 
    , .CLK ( clk ) , .Q ( cnt[9] ) ) ;
DFFARX1_RVT \cnt_reg[10] (.QN ( n110 ) , .RSTB ( IN0 ) , .D ( n162 ) 
    , .CLK ( clk ) , .Q ( cnt[10] ) ) ;
DFFARX1_RVT \cnt_reg[11] (.QN ( n111 ) , .RSTB ( IN0 ) , .D ( n161 ) 
    , .CLK ( clk ) , .Q ( cnt[11] ) ) ;
DFFARX1_RVT \cnt_reg[12] (.QN ( n112 ) , .RSTB ( IN0 ) , .D ( n160 ) 
    , .CLK ( clk ) , .Q ( cnt[12] ) ) ;
DFFARX1_RVT \cnt_reg[13] (.QN ( n113 ) , .RSTB ( IN0 ) , .D ( n159 ) 
    , .CLK ( clk ) , .Q ( cnt[13] ) ) ;
DFFARX1_RVT \cnt_reg[14] (.QN ( n114 ) , .RSTB ( IN0 ) , .D ( n158 ) 
    , .CLK ( clk ) , .Q ( cnt[14] ) ) ;
DFFARX1_RVT \cnt_reg[15] (.QN ( n115 ) , .RSTB ( IN0 ) , .D ( n157 ) 
    , .CLK ( clk ) , .Q ( cnt[15] ) ) ;
DFFARX1_RVT \cnt_reg[6] (.QN ( n106 ) , .RSTB ( nReset ) , .D ( n166 ) 
    , .CLK ( clk ) , .Q ( cnt[6] ) ) ;
DFFARX1_RVT \cnt_reg[7] (.QN ( n107 ) , .RSTB ( IN1 ) , .D ( n165 ) 
    , .CLK ( clk ) , .Q ( cnt[7] ) ) ;
DFFARX1_RVT \cnt_reg[5] (.QN ( n105 ) , .RSTB ( IN1 ) , .D ( n167 ) 
    , .CLK ( clk ) , .Q ( cnt[5] ) ) ;
DFFARX1_RVT \cnt_reg[4] (.QN ( n104 ) , .RSTB ( nReset ) , .D ( n168 ) 
    , .CLK ( clk ) , .Q ( cnt[4] ) ) ;
DFFARX1_RVT \cnt_reg[3] (.QN ( n103 ) , .RSTB ( IN1 ) , .D ( n169 ) 
    , .CLK ( clk ) , .Q ( cnt[3] ) ) ;
DFFARX1_RVT \cnt_reg[2] (.QN ( n102 ) , .RSTB ( IN1 ) , .D ( n170 ) 
    , .CLK ( clk ) , .Q ( cnt[2] ) ) ;
DFFARX1_RVT \cnt_reg[1] (.QN ( n101 ) , .RSTB ( nReset ) , .D ( n171 ) 
    , .CLK ( clk ) , .Q ( cnt[1] ) ) ;
DFFARX1_RVT \cnt_reg[0] (.QN ( n100 ) , .RSTB ( IN1 ) , .D ( n172 ) 
    , .CLK ( clk ) , .Q ( cnt[0] ) ) ;
DFFASX1_RVT clk_en_reg (.QN ( n132 ) , .D ( N64 ) , .SETB ( IN1 ) , .CLK ( clk ) 
    , .Q ( n57 ) ) ;
DFFARX1_RVT cmd_stop_reg (.QN ( n58 ) , .RSTB ( IN1 ) , .D ( n156 ) 
    , .CLK ( clk ) , .Q ( n116 ) ) ;
DFFARX1_RVT cmd_ack_reg (.RSTB ( IN1 ) , .D ( N172 ) , .CLK ( clk ) 
    , .Q ( cmd_ack ) ) ;
DFFARX1_RVT sto_condition_reg (.QN ( n51 ) , .RSTB ( IN1 ) , .D ( N74 ) 
    , .CLK ( clk ) , .Q ( sto_condition ) ) ;
DFFARX1_RVT al_reg (.RSTB ( IN1 ) , .D ( N84 ) , .CLK ( clk ) , .Q ( al ) ) ;
DFFARX1_RVT sda_chk_reg (.RSTB ( IN1 ) , .D ( n174 ) , .CLK ( clk ) 
    , .Q ( sda_chk ) ) ;
NAND2X0_RVT U14 (.A2 ( rst ) , .A1 ( n56 ) , .Y ( n25 ) ) ;
INVX1_RVT U15 (.A ( n11 ) , .Y ( n60 ) ) ;
NAND2X0_RVT U16 (.A2 ( n12 ) , .A1 ( n55 ) , .Y ( n29 ) ) ;
AND3X1_RVT U17 (.A1 ( n60 ) , .Y ( n19 ) , .A2 ( n71 ) , .A3 ( n37 ) ) ;
NAND2X0_RVT U18 (.A2 ( rst ) , .A1 ( n15 ) , .Y ( N69 ) ) ;
AND3X1_RVT U19 (.A1 ( n69 ) , .Y ( n47 ) , .A2 ( rst ) , .A3 ( n66 ) ) ;
OA21X1_RVT U20 (.Y ( n4 ) , .A3 ( n12 ) , .A2 ( n11 ) , .A1 ( n10 ) ) ;
INVX1_RVT U21 (.A ( n69 ) , .Y ( n56 ) ) ;
OR2X1_RVT U22 (.Y ( n11 ) , .A2 ( n78 ) , .A1 ( n2 ) ) ;
INVX1_RVT U23 (.A ( n79 ) , .Y ( n63 ) ) ;
AND2X1_RVT U24 (.Y ( n28 ) , .A1 ( n68 ) , .A2 ( n76 ) ) ;
AO21X1_RVT U25 (.A1 ( n36 ) , .Y ( n154 ) , .A2 ( n2 ) , .A3 ( n40 ) ) ;
AND4X1_RVT U26 (.Y ( n40 ) , .A1 ( cmd[0] ) , .A3 ( n67 ) , .A4 ( n76 ) 
    , .A2 ( n19 ) ) ;
OR2X1_RVT U27 (.Y ( n10 ) , .A2 ( IN2 ) , .A1 ( al ) ) ;
AO21X1_RVT U28 (.A1 ( n36 ) , .Y ( n141 ) , .A2 ( n22 ) , .A3 ( n18 ) ) ;
AND4X1_RVT U29 (.Y ( n18 ) , .A1 ( cmd[2] ) , .A3 ( n68 ) , .A4 ( n67 ) 
    , .A2 ( n19 ) ) ;
AND2X1_RVT U30 (.Y ( n34 ) , .A1 ( n28 ) , .A2 ( n19 ) ) ;
AO222X1_RVT U31 (.A1 ( clk_cnt[15] ) , .A5 ( n38 ) , .A6 ( cnt[15] ) 
    , .A3 ( N47 ) , .A2 ( n47 ) , .Y ( n157 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U32 (.A1 ( clk_cnt[14] ) , .A5 ( n38 ) , .A6 ( cnt[14] ) 
    , .A3 ( N46 ) , .A2 ( n47 ) , .Y ( n158 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U33 (.A1 ( clk_cnt[13] ) , .A5 ( n38 ) , .A6 ( cnt[13] ) 
    , .A3 ( N45 ) , .A2 ( n47 ) , .Y ( n159 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U34 (.A1 ( clk_cnt[12] ) , .A5 ( n38 ) , .A6 ( cnt[12] ) 
    , .A3 ( N44 ) , .A2 ( n47 ) , .Y ( n160 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U35 (.A1 ( clk_cnt[11] ) , .A5 ( n38 ) , .A6 ( cnt[11] ) 
    , .A3 ( N43 ) , .A2 ( n47 ) , .Y ( n161 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U36 (.A1 ( clk_cnt[10] ) , .A5 ( n38 ) , .A6 ( cnt[10] ) 
    , .A3 ( N42 ) , .A2 ( n47 ) , .Y ( n162 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U37 (.A1 ( clk_cnt[9] ) , .A5 ( n38 ) , .A6 ( cnt[9] ) , .A3 ( N41 ) 
    , .A2 ( n47 ) , .Y ( n163 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U38 (.A1 ( clk_cnt[8] ) , .A5 ( n38 ) , .A6 ( cnt[8] ) , .A3 ( N40 ) 
    , .A2 ( n47 ) , .Y ( n164 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U39 (.A1 ( clk_cnt[7] ) , .A5 ( n38 ) , .A6 ( cnt[7] ) , .A3 ( N39 ) 
    , .A2 ( n47 ) , .Y ( n165 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U40 (.A1 ( clk_cnt[6] ) , .A5 ( n38 ) , .A6 ( cnt[6] ) , .A3 ( N38 ) 
    , .A2 ( n47 ) , .Y ( n166 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U41 (.A1 ( clk_cnt[5] ) , .A5 ( n38 ) , .A6 ( cnt[5] ) , .A3 ( N37 ) 
    , .A2 ( n47 ) , .Y ( n167 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U42 (.A1 ( clk_cnt[4] ) , .A5 ( n38 ) , .A6 ( cnt[4] ) , .A3 ( N36 ) 
    , .A2 ( n47 ) , .Y ( n168 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U43 (.A1 ( clk_cnt[3] ) , .A5 ( n38 ) , .A6 ( cnt[3] ) , .A3 ( N35 ) 
    , .A2 ( n47 ) , .Y ( n169 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U44 (.A1 ( clk_cnt[2] ) , .A5 ( n38 ) , .A6 ( cnt[2] ) , .A3 ( N34 ) 
    , .A2 ( n47 ) , .Y ( n170 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U45 (.A1 ( clk_cnt[1] ) , .A5 ( n38 ) , .A6 ( cnt[1] ) , .A3 ( N33 ) 
    , .A2 ( n47 ) , .Y ( n171 ) , .A4 ( n39 ) ) ;
AO222X1_RVT U46 (.A1 ( clk_cnt[0] ) , .A5 ( n38 ) , .A6 ( cnt[0] ) , .A3 ( N32 ) 
    , .A2 ( n47 ) , .Y ( n172 ) , .A4 ( n39 ) ) ;
OAI22X1_RVT U47 (.Y ( n145 ) , .A4 ( n27 ) , .A3 ( n26 ) , .A2 ( n12 ) 
    , .A1 ( n135 ) ) ;
NAND2X0_RVT U48 (.A2 ( n28 ) , .A1 ( cmd[3] ) , .Y ( n27 ) ) ;
NAND3X0_RVT U49 (.Y ( n26 ) , .A1 ( n60 ) , .A2 ( n67 ) , .A3 ( n37 ) ) ;
AO22X1_RVT U50 (.A2 ( n54 ) , .A3 ( n4 ) , .Y ( n138 ) , .A4 ( n5 ) 
    , .A1 ( sda_oen ) ) ;
NAND4X0_RVT U51 (.A2 ( n137 ) , .A4 ( n129 ) , .A3 ( n7 ) , .Y ( n5 ) 
    , .A1 ( n55 ) ) ;
INVX1_RVT U52 (.A ( n4 ) , .Y ( n54 ) ) ;
AOI21X1_RVT U53 (.Y ( n7 ) , .A2 ( n8 ) , .A3 ( n9 ) , .A1 ( din ) ) ;
AO22X1_RVT U54 (.A2 ( n70 ) , .A3 ( n53 ) , .Y ( n173 ) , .A4 ( n72 ) 
    , .A1 ( scl_oen ) ) ;
OR2X1_RVT U55 (.Y ( n72 ) , .A2 ( n74 ) , .A1 ( n73 ) ) ;
INVX1_RVT U56 (.A ( n70 ) , .Y ( n53 ) ) ;
NAND4X0_RVT U57 (.A2 ( n136 ) , .A4 ( n63 ) , .A3 ( n75 ) , .Y ( n73 ) 
    , .A1 ( n129 ) ) ;
NAND2X0_RVT U58 (.A2 ( n12 ) , .A1 ( n77 ) , .Y ( n70 ) ) ;
AO21X1_RVT U59 (.A1 ( n137 ) , .Y ( n77 ) , .A2 ( n78 ) , .A3 ( n10 ) ) ;
NAND4X0_RVT U60 (.A2 ( n118 ) , .A4 ( n122 ) , .A3 ( n119 ) , .Y ( n74 ) 
    , .A1 ( n55 ) ) ;
NAND2X0_RVT U61 (.A2 ( n81 ) , .A1 ( n80 ) , .Y ( N84 ) ) ;
NAND3X0_RVT U62 (.Y ( n80 ) , .A1 ( sda_oen ) , .A2 ( n48 ) , .A3 ( sda_chk ) ) ;
NAND4X0_RVT U63 (.A2 ( n11 ) , .A4 ( rst ) , .A3 ( n58 ) , .Y ( n81 ) 
    , .A1 ( sto_condition ) ) ;
INVX1_RVT U64 (.A ( N70 ) , .Y ( n48 ) ) ;
AND4X1_RVT U65 (.Y ( N74 ) , .A1 ( n133 ) , .A3 ( sSCL ) , .A4 ( rst ) 
    , .A2 ( sSDA ) ) ;
AND3X1_RVT U66 (.A1 ( rst ) , .Y ( N76 ) , .A2 ( n51 ) , .A3 ( n87 ) ) ;
NAND2X0_RVT U67 (.A2 ( n98 ) , .A1 ( n99 ) , .Y ( n87 ) ) ;
AND3X1_RVT U68 (.A1 ( n95 ) , .Y ( N172 ) , .A2 ( n57 ) , .A3 ( n55 ) ) ;
NAND4X0_RVT U69 (.A2 ( n134 ) , .A4 ( n117 ) , .A3 ( n123 ) , .Y ( n95 ) 
    , .A1 ( n120 ) ) ;
NAND2X0_RVT U70 (.A2 ( n90 ) , .A1 ( ena ) , .Y ( n69 ) ) ;
DFFARX1_RVT sta_condition_reg (.QN ( n98 ) , .RSTB ( IN0 ) , .D ( N73 ) 
    , .CLK ( clk ) ) ;
DFFASX1_RVT dSDA_reg (.QN ( n133 ) , .D ( N70 ) , .SETB ( IN0 ) , .CLK ( clk ) ) ;
DFFASX1_RVT scl_oen_reg (.D ( n173 ) , .SETB ( IN1 ) , .CLK ( clk ) 
    , .Q ( scl_oen ) ) ;
DFFARX1_RVT busy_reg (.QN ( n99 ) , .RSTB ( IN0 ) , .D ( N76 ) , .CLK ( clk ) 
    , .Q ( busy ) ) ;
DFFASX1_RVT sda_oen_reg (.D ( n138 ) , .SETB ( IN1 ) , .CLK ( clk ) 
    , .Q ( sda_oen ) ) ;
DFFASX1_RVT dSCL_reg (.QN ( n130 ) , .D ( N69 ) , .SETB ( IN1 ) , .CLK ( clk ) ) ;
DFFX1_RVT dout_reg (.D ( n131 ) , .CLK ( clk ) , .Q ( dout ) ) ;
DFFASX1_RVT sSDA_reg (.D ( N68 ) , .SETB ( IN0 ) , .CLK ( clk ) , .Q ( sSDA ) ) ;
DFFARX1_RVT \c_state_reg[6] (.QN ( n122 ) , .RSTB ( IN1 ) , .D ( n148 ) 
    , .CLK ( clk ) , .Q ( n3 ) ) ;
DFFARX1_RVT \c_state_reg[5] (.QN ( n121 ) , .RSTB ( IN1 ) , .D ( n149 ) 
    , .CLK ( clk ) , .Q ( n24 ) ) ;
DFFARX1_RVT \c_state_reg[1] (.QN ( n129 ) , .RSTB ( IN1 ) , .D ( n153 ) 
    , .CLK ( clk ) , .Q ( n17 ) ) ;
DFFARX1_RVT \c_state_reg[0] (.QN ( n137 ) , .RSTB ( IN1 ) , .D ( n154 ) 
    , .CLK ( clk ) , .Q ( n2 ) ) ;
DFFARX1_RVT \c_state_reg[2] (.QN ( n118 ) , .RSTB ( IN1 ) , .D ( n152 ) 
    , .CLK ( clk ) , .Q ( n6 ) ) ;
DFFARX1_RVT \c_state_reg[3] (.QN ( n119 ) , .RSTB ( IN1 ) , .D ( n151 ) 
    , .CLK ( clk ) , .Q ( n20 ) ) ;
DFFARX1_RVT \c_state_reg[4] (.QN ( n120 ) , .RSTB ( IN1 ) , .D ( n150 ) 
    , .CLK ( clk ) , .Q ( n65 ) ) ;
DFFARX1_RVT \c_state_reg[13] (.QN ( n126 ) , .RSTB ( IN1 ) , .D ( n141 ) 
    , .CLK ( clk ) , .Q ( n22 ) ) ;
DFFARX1_RVT \c_state_reg[7] (.QN ( n136 ) , .RSTB ( IN1 ) , .D ( n147 ) 
    , .CLK ( clk ) , .Q ( n16 ) ) ;
DFFARX1_RVT \c_state_reg[12] (.QN ( n134 ) , .RSTB ( IN1 ) , .D ( n142 ) 
    , .CLK ( clk ) , .Q ( n62 ) ) ;
DFFARX1_RVT \c_state_reg[9] (.QN ( n135 ) , .RSTB ( IN1 ) , .D ( n145 ) 
    , .CLK ( clk ) , .Q ( n61 ) ) ;
DFFARX1_RVT \c_state_reg[16] (.QN ( n117 ) , .RSTB ( IN1 ) , .D ( n155 ) 
    , .CLK ( clk ) , .Q ( n59 ) ) ;
DFFARX1_RVT \c_state_reg[10] (.QN ( n124 ) , .RSTB ( IN1 ) , .D ( n144 ) 
    , .CLK ( clk ) , .Q ( n13 ) ) ;
DFFARX1_RVT \c_state_reg[11] (.QN ( n125 ) , .RSTB ( IN1 ) , .D ( n143 ) 
    , .CLK ( clk ) , .Q ( n21 ) ) ;
DFFARX1_RVT \c_state_reg[8] (.QN ( n123 ) , .RSTB ( IN1 ) , .D ( n146 ) 
    , .CLK ( clk ) , .Q ( n64 ) ) ;
DFFARX1_RVT \c_state_reg[14] (.QN ( n127 ) , .RSTB ( IN1 ) , .D ( n140 ) 
    , .CLK ( clk ) , .Q ( n14 ) ) ;
endmodule




module i2c_master_byte_ctrl (scl_oen , sda_o , sda_oen , IN0 , IN1 , 
    IN2 , IN3 , IN4 , ack_in , scl_i , sda_i , cmd_ack , ack_out , 
    i2c_busy , i2c_al , scl_o , clk , rst , nReset , ena , start , 
    stop , read , write , dout , din , clk_cnt );
output scl_oen ;
output sda_o ;
output sda_oen ;
input  IN0 ;
input  IN1 ;
input  IN2 ;
input  IN3 ;
input  IN4 ;
input  ack_in ;
input  scl_i ;
input  sda_i ;
output cmd_ack ;
output ack_out ;
output i2c_busy ;
output i2c_al ;
output scl_o ;
input  clk ;
input  rst ;
input  nReset ;
input  ena ;
input  start ;
input  stop ;
input  read ;
input  write ;
output [7:0] dout ;
input  [7:0] din ;
input  [15:0] clk_cnt ;

wire [3:0] core_cmd ;

wire [4:0] c_state ;
wire [2:0] dcnt ;


i2c_master_bit_ctrl bit_controller (.scl_oen ( scl_oen ) , 
    .sda_oen ( sda_oen ) , .IN0 ( IN1 ) , .IN1 ( IN2 ) , .IN2 ( IN4 ) , 
    .din ( core_txd ) , .scl_i ( scl_i ) , .sda_i ( sda_i ) , 
    .cmd_ack ( core_ack ) , .busy ( i2c_busy ) , .al ( i2c_al ) , 
    .dout ( core_rxd ) , .cmd ( core_cmd ) , .clk ( clk ) , .rst ( rst ) , 
    .nReset ( nReset ) , .ena ( ena ) , .clk_cnt ( clk_cnt ) ) ;

INVX1_RVT U2 (.A ( n44 ) , .Y ( n91 ) ) ;
INVX1_RVT U1 (.A ( n47 ) , .Y ( n90 ) ) ;
INVX1_RVT U20 (.A ( n32 ) , .Y ( n10 ) ) ;
NAND3X0_RVT U21 (.Y ( n32 ) , .A1 ( n38 ) , .A2 ( n88 ) , .A3 ( n28 ) ) ;
AO21X1_RVT U22 (.A1 ( write ) , .Y ( n38 ) , .A2 ( n86 ) , .A3 ( c_state[0] ) ) ;
OR2X1_RVT U23 (.Y ( n52 ) , .A2 ( IN3 ) , .A1 ( i2c_al ) ) ;
AO21X1_RVT U24 (.A1 ( c_state[1] ) , .Y ( n71 ) , .A2 ( n37 ) , .A3 ( n9 ) ) ;
INVX1_RVT U25 (.A ( n26 ) , .Y ( n9 ) ) ;
NAND3X0_RVT U26 (.Y ( n26 ) , .A1 ( n28 ) , .A2 ( n39 ) , .A3 ( read ) ) ;
NAND2X0_RVT U27 (.A2 ( n40 ) , .A1 ( n14 ) , .Y ( n39 ) ) ;
NAND4X0_RVT U28 (.A2 ( n31 ) , .A4 ( n33 ) , .A3 ( n32 ) , .Y ( n66 ) 
    , .A1 ( n30 ) ) ;
NAND2X0_RVT U29 (.A2 ( n17 ) , .A1 ( core_cmd[2] ) , .Y ( n30 ) ) ;
NAND3X0_RVT U30 (.Y ( n31 ) , .A1 ( n28 ) , .A2 ( n29 ) , .A3 ( c_state[2] ) ) ;
NAND3X0_RVT U31 (.Y ( n33 ) , .A1 ( n28 ) , .A2 ( n57 ) , .A3 ( c_state[1] ) ) ;
NAND3X0_RVT U32 (.Y ( n27 ) , .A1 ( n28 ) , .A2 ( n57 ) , .A3 ( c_state[2] ) ) ;
NAND4X0_RVT U33 (.A2 ( n25 ) , .A4 ( n27 ) , .A3 ( n26 ) , .Y ( n65 ) 
    , .A1 ( n24 ) ) ;
NAND2X0_RVT U34 (.A2 ( n17 ) , .A1 ( core_cmd[3] ) , .Y ( n24 ) ) ;
NAND3X0_RVT U35 (.Y ( n25 ) , .A1 ( n28 ) , .A2 ( n29 ) , .A3 ( c_state[1] ) ) ;
NAND3X0_RVT U36 (.Y ( n69 ) , .A1 ( n33 ) , .A2 ( n27 ) , .A3 ( n36 ) ) ;
NAND2X0_RVT U37 (.A2 ( c_state[3] ) , .A1 ( n17 ) , .Y ( n36 ) ) ;
AO21X1_RVT U38 (.A1 ( c_state[0] ) , .Y ( n72 ) , .A2 ( n17 ) , .A3 ( n35 ) ) ;
AO21X1_RVT U39 (.A1 ( core_cmd[0] ) , .Y ( n68 ) , .A2 ( n17 ) , .A3 ( n35 ) ) ;
AND3X1_RVT U40 (.A1 ( n28 ) , .Y ( n35 ) , .A2 ( n85 ) , .A3 ( start ) ) ;
AO22X1_RVT U41 (.A2 ( n17 ) , .A3 ( n28 ) , .Y ( n76 ) , .A4 ( n34 ) 
    , .A1 ( c_state[4] ) ) ;
AO22X1_RVT U42 (.A2 ( n17 ) , .A3 ( n28 ) , .Y ( n67 ) , .A4 ( n34 ) 
    , .A1 ( core_cmd[1] ) ) ;
AO221X1_RVT U43 (.A5 ( n91 ) , .A1 ( n90 ) , .A4 ( n41 ) , .Y ( n73 ) 
    , .A2 ( n57 ) , .A3 ( dcnt[2] ) ) ;
AO21X1_RVT U44 (.A1 ( dcnt[1] ) , .Y ( n41 ) , .A2 ( n90 ) , .A3 ( n42 ) ) ;
AO21X1_RVT U45 (.A1 ( dcnt[0] ) , .Y ( n42 ) , .A2 ( n90 ) , .A3 ( n46 ) ) ;
NAND3X0_RVT U46 (.Y ( n47 ) , .A1 ( n16 ) , .A2 ( rst ) , .A3 ( shift ) ) ;
AO221X1_RVT U47 (.A5 ( n91 ) , .A1 ( n20 ) , .A4 ( n42 ) , .Y ( n75 ) 
    , .A2 ( n7 ) , .A3 ( dcnt[1] ) ) ;
INVX1_RVT U48 (.A ( n43 ) , .Y ( n20 ) ) ;
AO221X1_RVT U49 (.A5 ( n52 ) , .A1 ( core_ack ) , .A4 ( n85 ) , .Y ( n50 ) 
    , .A2 ( n49 ) , .A3 ( n51 ) ) ;
AO222X1_RVT U50 (.A1 ( din[7] ) , .A5 ( dout[7] ) , .A6 ( n53 ) 
    , .A3 ( dout[6] ) , .A2 ( n91 ) , .Y ( n77 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U51 (.A1 ( din[6] ) , .A5 ( n53 ) , .A6 ( dout[6] ) 
    , .A3 ( dout[5] ) , .A2 ( n91 ) , .Y ( n78 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U52 (.A1 ( din[5] ) , .A5 ( dout[5] ) , .A6 ( n53 ) 
    , .A3 ( dout[4] ) , .A2 ( n91 ) , .Y ( n79 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U53 (.A1 ( din[4] ) , .A5 ( dout[4] ) , .A6 ( n53 ) 
    , .A3 ( dout[3] ) , .A2 ( n91 ) , .Y ( n80 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U54 (.A1 ( din[3] ) , .A5 ( dout[3] ) , .A6 ( n53 ) 
    , .A3 ( dout[2] ) , .A2 ( n91 ) , .Y ( n81 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U55 (.A1 ( din[2] ) , .A5 ( dout[2] ) , .A6 ( n53 ) 
    , .A3 ( dout[1] ) , .A2 ( n91 ) , .Y ( n82 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U56 (.A1 ( din[1] ) , .A5 ( dout[1] ) , .A6 ( n53 ) 
    , .A3 ( dout[0] ) , .A2 ( n91 ) , .Y ( n84 ) , .A4 ( n90 ) ) ;
AO222X1_RVT U57 (.A1 ( din[0] ) , .A5 ( dout[0] ) , .A6 ( n53 ) , .A3 ( n90 ) 
    , .A2 ( n91 ) , .Y ( n83 ) , .A4 ( core_rxd ) ) ;
NAND3X0_RVT U58 (.Y ( n49 ) , .A1 ( n14 ) , .A2 ( n13 ) , .A3 ( n58 ) ) ;
NOR3X0_RVT U59 (.Y ( n58 ) , .A1 ( c_state[3] ) , .A3 ( c_state[2] ) 
    , .A2 ( c_state[4] ) ) ;
NAND2X0_RVT U60 (.A2 ( rst ) , .A1 ( ld ) , .Y ( n44 ) ) ;
INVX1_RVT U61 (.A ( read ) , .Y ( n88 ) ) ;
AND2X1_RVT U62 (.Y ( n51 ) , .A1 ( n1 ) , .A2 ( n2 ) ) ;
NAND3X0_RVT U63 (.Y ( n2 ) , .A1 ( n87 ) , .A2 ( n89 ) , .A3 ( n88 ) ) ;
INVX1_RVT U64 (.A ( write ) , .Y ( n89 ) ) ;
AO22X1_RVT U65 (.A2 ( c_state[0] ) , .A3 ( n56 ) , .Y ( N106 ) , .A4 ( n51 ) 
    , .A1 ( n54 ) ) ;
AND2X1_RVT U66 (.Y ( n56 ) , .A1 ( n85 ) , .A2 ( n15 ) ) ;
AND2X1_RVT U67 (.Y ( n54 ) , .A1 ( n15 ) , .A2 ( core_ack ) ) ;
AND2X1_RVT U68 (.Y ( N107 ) , .A1 ( n54 ) , .A2 ( n55 ) ) ;
AO21X1_RVT U69 (.A1 ( c_state[3] ) , .Y ( n55 ) , .A2 ( n87 ) 
    , .A3 ( c_state[4] ) ) ;
OA21X1_RVT U70 (.Y ( N105 ) , .A3 ( n54 ) , .A2 ( c_state[1] ) , .A1 ( n59 ) ) ;
AND2X1_RVT U71 (.Y ( n59 ) , .A1 ( c_state[2] ) , .A2 ( n29 ) ) ;
INVX1_RVT U72 (.A ( stop ) , .Y ( n87 ) ) ;
AND2X1_RVT U73 (.Y ( N104 ) , .A1 ( n15 ) , .A2 ( n60 ) ) ;
AO221X1_RVT U74 (.A5 ( n18 ) , .A1 ( ack_in ) , .A4 ( n62 ) , .Y ( n60 ) 
    , .A2 ( n61 ) , .A3 ( dout[7] ) ) ;
AO21X1_RVT U75 (.A1 ( c_state[1] ) , .Y ( n61 ) , .A2 ( core_ack ) 
    , .A3 ( c_state[3] ) ) ;
NAND4X0_RVT U76 (.A2 ( n11 ) , .A4 ( n63 ) , .A3 ( n14 ) , .Y ( n62 ) 
    , .A1 ( n12 ) ) ;
AND2X1_RVT U77 (.Y ( n64 ) , .A1 ( n15 ) , .A2 ( n22 ) ) ;
AO22X1_RVT U78 (.A2 ( n23 ) , .A3 ( core_rxd ) , .Y ( n22 ) , .A4 ( n18 ) 
    , .A1 ( ack_out ) ) ;
OR2X1_RVT U79 (.Y ( n40 ) , .A2 ( start ) , .A1 ( n49 ) ) ;
AO22X1_RVT U80 (.A2 ( c_state[3] ) , .A3 ( n48 ) , .Y ( n34 ) , .A4 ( n86 ) 
    , .A1 ( stop ) ) ;
AND2X1_RVT U81 (.Y ( n48 ) , .A1 ( n88 ) , .A2 ( n89 ) ) ;
NAND2X0_RVT U82 (.A2 ( c_state[3] ) , .A1 ( core_ack ) , .Y ( n23 ) ) ;
OA22X1_RVT U83 (.Y ( n63 ) , .A4 ( n13 ) , .A3 ( core_ack ) , .A2 ( c_state[1] ) 
    , .A1 ( c_state[3] ) ) ;
OR3X2_RVT U84 (.A1 ( dcnt[1] ) , .A3 ( dcnt[0] ) , .Y ( n29 ) , .A2 ( dcnt[2] ) ) ;
OR2X1_RVT U85 (.Y ( n43 ) , .A2 ( dcnt[0] ) , .A1 ( n47 ) ) ;
NAND3X0_RVT U86 (.Y ( n74 ) , .A1 ( n43 ) , .A2 ( n44 ) , .A3 ( n45 ) ) ;
NAND2X0_RVT U87 (.A2 ( dcnt[0] ) , .A1 ( n46 ) , .Y ( n45 ) ) ;
DFFARX1_RVT ld_reg (.QN ( n16 ) , .RSTB ( IN0 ) , .D ( N106 ) , .CLK ( clk ) 
    , .Q ( ld ) ) ;
DFFARX1_RVT \dcnt_reg[0] (.RSTB ( IN0 ) , .D ( n74 ) , .CLK ( clk ) 
    , .Q ( dcnt[0] ) ) ;
DFFARX1_RVT core_txd_reg (.RSTB ( IN0 ) , .D ( N104 ) , .CLK ( clk ) 
    , .Q ( core_txd ) ) ;
DFFARX1_RVT ack_out_reg (.RSTB ( IN0 ) , .D ( n64 ) , .CLK ( clk ) 
    , .Q ( ack_out ) ) ;
DFFARX1_RVT shift_reg (.RSTB ( IN0 ) , .D ( N105 ) , .CLK ( clk ) , .Q ( shift ) ) ;
DFFARX1_RVT \sr_reg[0] (.RSTB ( IN0 ) , .D ( n83 ) , .CLK ( clk ) 
    , .Q ( dout[0] ) ) ;
DFFARX1_RVT \sr_reg[7] (.RSTB ( IN0 ) , .D ( n77 ) , .CLK ( clk ) 
    , .Q ( dout[7] ) ) ;
DFFARX1_RVT \sr_reg[6] (.RSTB ( IN0 ) , .D ( n78 ) , .CLK ( clk ) 
    , .Q ( dout[6] ) ) ;
DFFARX1_RVT \sr_reg[5] (.RSTB ( nReset ) , .D ( n79 ) , .CLK ( clk ) 
    , .Q ( dout[5] ) ) ;
DFFARX1_RVT \sr_reg[4] (.RSTB ( IN0 ) , .D ( n80 ) , .CLK ( clk ) 
    , .Q ( dout[4] ) ) ;
DFFARX1_RVT \sr_reg[3] (.RSTB ( nReset ) , .D ( n81 ) , .CLK ( clk ) 
    , .Q ( dout[3] ) ) ;
DFFARX1_RVT \sr_reg[2] (.RSTB ( nReset ) , .D ( n82 ) , .CLK ( clk ) 
    , .Q ( dout[2] ) ) ;
DFFARX1_RVT \sr_reg[1] (.RSTB ( IN0 ) , .D ( n84 ) , .CLK ( clk ) 
    , .Q ( dout[1] ) ) ;
DFFARX1_RVT \dcnt_reg[2] (.RSTB ( IN0 ) , .D ( n73 ) , .CLK ( clk ) 
    , .Q ( dcnt[2] ) ) ;
DFFARX1_RVT \core_cmd_reg[1] (.RSTB ( IN0 ) , .D ( n67 ) , .CLK ( clk ) 
    , .Q ( core_cmd[1] ) ) ;
DFFARX1_RVT \c_state_reg[3] (.RSTB ( IN0 ) , .D ( n69 ) , .CLK ( clk ) 
    , .Q ( c_state[3] ) ) ;
DFFARX1_RVT \core_cmd_reg[0] (.RSTB ( IN0 ) , .D ( n68 ) , .CLK ( clk ) 
    , .Q ( core_cmd[0] ) ) ;
DFFARX1_RVT \core_cmd_reg[3] (.RSTB ( IN0 ) , .D ( n65 ) , .CLK ( clk ) 
    , .Q ( core_cmd[3] ) ) ;
DFFARX1_RVT \core_cmd_reg[2] (.RSTB ( IN0 ) , .D ( n66 ) , .CLK ( clk ) 
    , .Q ( core_cmd[2] ) ) ;
DFFARX1_RVT \dcnt_reg[1] (.QN ( n7 ) , .RSTB ( IN0 ) , .D ( n75 ) , .CLK ( clk ) 
    , .Q ( dcnt[1] ) ) ;
DFFARX1_RVT \c_state_reg[1] (.QN ( n13 ) , .RSTB ( IN0 ) , .D ( n71 ) 
    , .CLK ( clk ) , .Q ( c_state[1] ) ) ;
DFFARX1_RVT \c_state_reg[0] (.QN ( n14 ) , .RSTB ( IN0 ) , .D ( n72 ) 
    , .CLK ( clk ) , .Q ( c_state[0] ) ) ;
DFFARX1_RVT \c_state_reg[2] (.QN ( n12 ) , .RSTB ( IN0 ) , .D ( n70 ) 
    , .CLK ( clk ) , .Q ( c_state[2] ) ) ;
DFFARX1_RVT \c_state_reg[4] (.QN ( n11 ) , .RSTB ( IN0 ) , .D ( n76 ) 
    , .CLK ( clk ) , .Q ( c_state[4] ) ) ;
DFFARX1_RVT cmd_ack_reg (.QN ( n1 ) , .RSTB ( IN0 ) , .D ( N107 ) , .CLK ( clk ) 
    , .Q ( cmd_ack ) ) ;
AND2X1_RVT U6 (.Y ( n28 ) , .A1 ( n15 ) , .A2 ( n50 ) ) ;
INVX1_RVT U7 (.A ( n52 ) , .Y ( n15 ) ) ;
INVX1_RVT U9 (.A ( n50 ) , .Y ( n17 ) ) ;
AO21X1_RVT U10 (.A1 ( n15 ) , .Y ( n37 ) , .A2 ( n29 ) , .A3 ( n17 ) ) ;
INVX1_RVT U11 (.A ( n49 ) , .Y ( n85 ) ) ;
AND3X1_RVT U13 (.A1 ( n44 ) , .Y ( n53 ) , .A2 ( rst ) , .A3 ( n47 ) ) ;
INVX1_RVT U14 (.A ( n40 ) , .Y ( n86 ) ) ;
INVX1_RVT U15 (.A ( n23 ) , .Y ( n18 ) ) ;
INVX1_RVT U16 (.A ( n29 ) , .Y ( n57 ) ) ;
AND2X1_RVT U17 (.Y ( n46 ) , .A1 ( n47 ) , .A2 ( rst ) ) ;
AO21X1_RVT U19 (.A1 ( c_state[2] ) , .Y ( n70 ) , .A2 ( n37 ) , .A3 ( n10 ) ) ;
endmodule




module i2c_master_top (wb_adr_i , wb_dat_i , wb_dat_o , wb_cyc_i , 
    wb_stb_i , wb_we_i , arst_i , wb_rst_i , wb_clk_i , sda_padoen_o , 
    sda_pad_o , scl_padoen_o , scl_pad_o , wb_inta_o , wb_ack_o , 
    sda_pad_i , scl_pad_i );
input  [2:0] wb_adr_i ;
input  [7:0] wb_dat_i ;
output [7:0] wb_dat_o ;
input  wb_cyc_i ;
input  wb_stb_i ;
input  wb_we_i ;
input  arst_i ;
input  wb_rst_i ;
input  wb_clk_i ;
output sda_padoen_o ;
output sda_pad_o ;
output scl_padoen_o ;
output scl_pad_o ;
output wb_inta_o ;
output wb_ack_o ;
input  sda_pad_i ;
input  scl_pad_i ;

wire [7:0] cr ;
wire [7:5] sr ;
wire [7:0] ctr ;
wire [7:0] rxr ;
wire [7:0] txr ;
wire [15:0] prer ;


assign scl_pad_o = sda_pad_o ;

i2c_master_byte_ctrl byte_controller (.scl_oen ( scl_padoen_o ) , 
    .sda_oen ( sda_padoen_o ) , .IN0 ( n6 ) , .IN1 ( n6 ) , .IN2 ( n3 ) , 
    .IN3 ( wb_rst_i ) , .IN4 ( wb_rst_i ) , .ack_in ( cr[3] ) , 
    .scl_i ( scl_pad_i ) , .sda_i ( sda_pad_i ) , .cmd_ack ( done ) , 
    .ack_out ( irxack ) , .i2c_busy ( sr[6] ) , .i2c_al ( i2c_al ) , 
    .clk ( wb_clk_i ) , .rst ( n2 ) , .nReset ( n7 ) , .ena ( ctr[7] ) , 
    .start ( cr[7] ) , .stop ( cr[6] ) , .read ( cr[5] ) , .write ( cr[4] ) , 
    .dout ( rxr ) , .din ( txr ) , .clk_cnt ( prer ) ) ;

INVX0_RVT U6 (.A ( n26 ) , .Y ( n9 ) ) ;
INVX0_RVT U5 (.A ( n28 ) , .Y ( n8 ) ) ;
NBUFFX2_RVT U4 (.A ( arst_i ) , .Y ( n7 ) ) ;
NBUFFX2_RVT U3 (.A ( arst_i ) , .Y ( n6 ) ) ;
NBUFFX2_RVT U2 (.A ( arst_i ) , .Y ( n3 ) ) ;
INVX0_RVT U1 (.A ( wb_rst_i ) , .Y ( n2 ) ) ;
AO22X1_RVT U179 (.A2 ( n132 ) , .A3 ( wb_dat_i[1] ) , .Y ( n62 ) , .A4 ( n14 ) 
    , .A1 ( cr[1] ) ) ;
AO22X1_RVT U180 (.A2 ( n132 ) , .A3 ( wb_dat_i[2] ) , .Y ( n63 ) , .A4 ( n14 ) 
    , .A1 ( cr[2] ) ) ;
NAND2X0_RVT U181 (.A2 ( n24 ) , .A1 ( n23 ) , .Y ( n68 ) ) ;
NAND4X0_RVT U182 (.A2 ( ctr[7] ) , .A4 ( n25 ) , .A3 ( n15 ) , .Y ( n24 ) 
    , .A1 ( wb_dat_i[3] ) ) ;
NAND3X0_RVT U183 (.Y ( n23 ) , .A1 ( n17 ) , .A2 ( n2 ) , .A3 ( cr[3] ) ) ;
INVX1_RVT U184 (.A ( wb_adr_i[2] ) , .Y ( n133 ) ) ;
INVX1_RVT U185 (.A ( wb_adr_i[0] ) , .Y ( n135 ) ) ;
INVX1_RVT U186 (.A ( wb_adr_i[1] ) , .Y ( n134 ) ) ;
AND3X1_RVT U187 (.A1 ( n135 ) , .Y ( n25 ) , .A2 ( n134 ) , .A3 ( wb_adr_i[2] ) ) ;
AND3X1_RVT U188 (.A1 ( wb_adr_i[2] ) , .Y ( n40 ) , .A2 ( n134 ) 
    , .A3 ( wb_adr_i[0] ) ) ;
OR3X2_RVT U189 (.A1 ( n105 ) , .A3 ( n107 ) , .Y ( N43 ) , .A2 ( n106 ) ) ;
AO22X1_RVT U190 (.A2 ( n25 ) , .A3 ( rxr[0] ) , .Y ( n105 ) , .A4 ( n104 ) 
    , .A1 ( sr_0 ) ) ;
AO22X1_RVT U191 (.A2 ( n39 ) , .A3 ( txr[0] ) , .Y ( n106 ) , .A4 ( n40 ) 
    , .A1 ( cr[0] ) ) ;
AO222X1_RVT U192 (.A1 ( n102 ) , .A5 ( n101 ) , .A6 ( prer[8] ) , .A3 ( n103 ) 
    , .A2 ( prer[0] ) , .Y ( n107 ) , .A4 ( ctr[0] ) ) ;
OR3X2_RVT U193 (.A1 ( n108 ) , .A3 ( n110 ) , .Y ( N44 ) , .A2 ( n109 ) ) ;
AO22X1_RVT U194 (.A2 ( n25 ) , .A3 ( rxr[1] ) , .Y ( n108 ) , .A4 ( n104 ) 
    , .A1 ( sr_1 ) ) ;
AO22X1_RVT U195 (.A2 ( n39 ) , .A3 ( txr[1] ) , .Y ( n109 ) , .A4 ( n40 ) 
    , .A1 ( cr[1] ) ) ;
AO222X1_RVT U196 (.A1 ( n102 ) , .A5 ( n101 ) , .A6 ( prer[9] ) , .A3 ( n103 ) 
    , .A2 ( prer[1] ) , .Y ( n110 ) , .A4 ( ctr[1] ) ) ;
OR3X2_RVT U197 (.A1 ( n111 ) , .A3 ( n113 ) , .Y ( N50 ) , .A2 ( n112 ) ) ;
AO22X1_RVT U198 (.A2 ( n25 ) , .A3 ( rxr[7] ) , .Y ( n111 ) , .A4 ( n104 ) 
    , .A1 ( sr[7] ) ) ;
AO22X1_RVT U199 (.A2 ( n39 ) , .A3 ( txr[7] ) , .Y ( n112 ) , .A4 ( n40 ) 
    , .A1 ( cr[7] ) ) ;
AO222X1_RVT U200 (.A1 ( n102 ) , .A5 ( n101 ) , .A6 ( prer[15] ) 
    , .A3 ( ctr[7] ) , .A2 ( prer[7] ) , .Y ( n113 ) , .A4 ( n103 ) ) ;
OR3X2_RVT U201 (.A1 ( n114 ) , .A3 ( n116 ) , .Y ( N48 ) , .A2 ( n115 ) ) ;
AO22X1_RVT U202 (.A2 ( n25 ) , .A3 ( rxr[5] ) , .Y ( n114 ) , .A4 ( n104 ) 
    , .A1 ( sr[5] ) ) ;
AO22X1_RVT U203 (.A2 ( n39 ) , .A3 ( txr[5] ) , .Y ( n115 ) , .A4 ( n40 ) 
    , .A1 ( cr[5] ) ) ;
AO222X1_RVT U204 (.A1 ( n102 ) , .A5 ( n101 ) , .A6 ( prer[13] ) , .A3 ( n103 ) 
    , .A2 ( prer[5] ) , .Y ( n116 ) , .A4 ( ctr[5] ) ) ;
OR3X2_RVT U205 (.A1 ( n117 ) , .A3 ( n119 ) , .Y ( N49 ) , .A2 ( n118 ) ) ;
AO22X1_RVT U206 (.A2 ( n25 ) , .A3 ( rxr[6] ) , .Y ( n117 ) , .A4 ( n104 ) 
    , .A1 ( sr[6] ) ) ;
AO22X1_RVT U207 (.A2 ( n39 ) , .A3 ( txr[6] ) , .Y ( n118 ) , .A4 ( n40 ) 
    , .A1 ( cr[6] ) ) ;
AO222X1_RVT U208 (.A1 ( n102 ) , .A5 ( n101 ) , .A6 ( prer[14] ) , .A3 ( n103 ) 
    , .A2 ( prer[6] ) , .Y ( n119 ) , .A4 ( ctr[6] ) ) ;
OR2X1_RVT U209 (.Y ( N45 ) , .A2 ( n52 ) , .A1 ( n51 ) ) ;
AO222X1_RVT U210 (.A1 ( prer[10] ) , .A5 ( prer[2] ) , .A6 ( n102 ) 
    , .A3 ( ctr[2] ) , .A2 ( n101 ) , .Y ( n52 ) , .A4 ( n103 ) ) ;
AO222X1_RVT U211 (.A1 ( n40 ) , .A5 ( rxr[2] ) , .A6 ( n104 ) , .A3 ( n39 ) 
    , .A2 ( txr[2] ) , .Y ( n51 ) , .A4 ( cr[2] ) ) ;
OR2X1_RVT U212 (.Y ( N46 ) , .A2 ( n50 ) , .A1 ( n49 ) ) ;
AO222X1_RVT U213 (.A1 ( prer[11] ) , .A5 ( prer[3] ) , .A6 ( n102 ) 
    , .A3 ( ctr[3] ) , .A2 ( n101 ) , .Y ( n50 ) , .A4 ( n103 ) ) ;
AO222X1_RVT U214 (.A1 ( n40 ) , .A5 ( rxr[3] ) , .A6 ( n104 ) , .A3 ( n39 ) 
    , .A2 ( txr[3] ) , .Y ( n49 ) , .A4 ( cr[3] ) ) ;
OR2X1_RVT U215 (.Y ( N47 ) , .A2 ( n48 ) , .A1 ( n47 ) ) ;
AO222X1_RVT U216 (.A1 ( prer[12] ) , .A5 ( prer[4] ) , .A6 ( n102 ) 
    , .A3 ( ctr[4] ) , .A2 ( n101 ) , .Y ( n48 ) , .A4 ( n103 ) ) ;
AO222X1_RVT U217 (.A1 ( n40 ) , .A5 ( rxr[4] ) , .A6 ( n104 ) , .A3 ( n39 ) 
    , .A2 ( txr[4] ) , .Y ( n47 ) , .A4 ( cr[4] ) ) ;
AND3X1_RVT U218 (.A1 ( wb_adr_i[2] ) , .Y ( n39 ) , .A2 ( n135 ) 
    , .A3 ( wb_adr_i[1] ) ) ;
AND3X1_RVT U219 (.A1 ( ctr[6] ) , .Y ( N121 ) , .A2 ( n2 ) , .A3 ( sr_0 ) ) ;
AND3X1_RVT U220 (.A1 ( n5 ) , .Y ( N117 ) , .A2 ( n2 ) , .A3 ( n59 ) ) ;
OR2X1_RVT U221 (.Y ( n59 ) , .A2 ( sr_0 ) , .A1 ( n21 ) ) ;
AND2X1_RVT U222 (.Y ( N115 ) , .A1 ( irxack ) , .A2 ( n2 ) ) ;
OA21X1_RVT U223 (.Y ( N114 ) , .A3 ( n2 ) , .A2 ( n60 ) , .A1 ( i2c_al ) ) ;
AND2X1_RVT U224 (.Y ( n60 ) , .A1 ( sr[5] ) , .A2 ( n4 ) ) ;
OA21X1_RVT U225 (.Y ( N116 ) , .A3 ( n2 ) , .A2 ( cr[5] ) , .A1 ( cr[4] ) ) ;
OR2X1_RVT U226 (.Y ( n21 ) , .A2 ( i2c_al ) , .A1 ( done ) ) ;
AND3X1_RVT U227 (.A1 ( wb_stb_i ) , .Y ( N20 ) , .A2 ( n1 ) , .A3 ( wb_cyc_i ) ) ;
DFFX1_RVT \wb_dat_o_reg[0] (.D ( N43 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[0] ) ) ;
DFFARX1_RVT rxack_reg (.RSTB ( n6 ) , .D ( N115 ) , .CLK ( wb_clk_i ) 
    , .Q ( sr[7] ) ) ;
DFFARX1_RVT al_reg (.RSTB ( n6 ) , .D ( N114 ) , .CLK ( wb_clk_i ) 
    , .Q ( sr[5] ) ) ;
DFFARX1_RVT tip_reg (.RSTB ( n6 ) , .D ( N116 ) , .CLK ( wb_clk_i ) 
    , .Q ( sr_1 ) ) ;
DFFARX1_RVT wb_inta_o_reg (.RSTB ( n7 ) , .D ( N121 ) , .CLK ( wb_clk_i ) 
    , .Q ( wb_inta_o ) ) ;
DFFARX1_RVT irq_flag_reg (.RSTB ( n6 ) , .D ( N117 ) , .CLK ( wb_clk_i ) 
    , .Q ( sr_0 ) ) ;
DFFARX1_RVT \cr_reg[3] (.RSTB ( n6 ) , .D ( n68 ) , .CLK ( wb_clk_i ) 
    , .Q ( cr[3] ) ) ;
DFFARX1_RVT \cr_reg[1] (.RSTB ( n7 ) , .D ( n62 ) , .CLK ( wb_clk_i ) 
    , .Q ( cr[1] ) ) ;
DFFARX1_RVT \cr_reg[2] (.RSTB ( n7 ) , .D ( n63 ) , .CLK ( wb_clk_i ) 
    , .Q ( cr[2] ) ) ;
DFFARX1_RVT \cr_reg[6] (.RSTB ( n6 ) , .D ( n65 ) , .CLK ( wb_clk_i ) 
    , .Q ( cr[6] ) ) ;
DFFARX1_RVT \cr_reg[5] (.RSTB ( n6 ) , .D ( n66 ) , .CLK ( wb_clk_i ) 
    , .Q ( cr[5] ) ) ;
DFFARX1_RVT \cr_reg[4] (.RSTB ( n6 ) , .D ( n67 ) , .CLK ( wb_clk_i ) 
    , .Q ( cr[4] ) ) ;
DFFARX1_RVT \ctr_reg[4] (.RSTB ( n7 ) , .D ( n97 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[4] ) ) ;
DFFARX1_RVT \ctr_reg[3] (.RSTB ( n7 ) , .D ( n96 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[3] ) ) ;
DFFARX1_RVT \ctr_reg[2] (.RSTB ( n7 ) , .D ( n95 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[2] ) ) ;
DFFARX1_RVT \ctr_reg[5] (.RSTB ( n7 ) , .D ( n98 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[5] ) ) ;
DFFARX1_RVT \ctr_reg[1] (.RSTB ( n7 ) , .D ( n94 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[1] ) ) ;
DFFARX1_RVT \ctr_reg[0] (.RSTB ( n7 ) , .D ( n93 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[0] ) ) ;
DFFARX1_RVT \txr_reg[4] (.RSTB ( n7 ) , .D ( n89 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[4] ) ) ;
DFFARX1_RVT \txr_reg[3] (.RSTB ( n7 ) , .D ( n88 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[3] ) ) ;
DFFARX1_RVT \txr_reg[2] (.RSTB ( n7 ) , .D ( n87 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[2] ) ) ;
DFFARX1_RVT \txr_reg[7] (.RSTB ( n7 ) , .D ( n92 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[7] ) ) ;
DFFARX1_RVT \txr_reg[6] (.RSTB ( n7 ) , .D ( n91 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[6] ) ) ;
DFFARX1_RVT \txr_reg[5] (.RSTB ( n7 ) , .D ( n90 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[5] ) ) ;
DFFARX1_RVT \txr_reg[1] (.RSTB ( n7 ) , .D ( n86 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[1] ) ) ;
DFFARX1_RVT \txr_reg[0] (.RSTB ( n7 ) , .D ( n85 ) , .CLK ( wb_clk_i ) 
    , .Q ( txr[0] ) ) ;
DFFARX1_RVT \ctr_reg[6] (.RSTB ( n7 ) , .D ( n99 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[6] ) ) ;
DFFARX1_RVT \ctr_reg[7] (.RSTB ( n7 ) , .D ( n100 ) , .CLK ( wb_clk_i ) 
    , .Q ( ctr[7] ) ) ;
AND3X1_RVT U114 (.A1 ( n134 ) , .Y ( n101 ) , .A2 ( n133 ) , .A3 ( wb_adr_i[0] ) ) ;
AND3X1_RVT U115 (.A1 ( n134 ) , .Y ( n102 ) , .A2 ( n133 ) , .A3 ( n135 ) ) ;
AND3X1_RVT U116 (.A1 ( n135 ) , .Y ( n103 ) , .A2 ( n133 ) , .A3 ( wb_adr_i[1] ) ) ;
AND3X1_RVT U117 (.A1 ( wb_adr_i[0] ) , .Y ( n104 ) , .A2 ( n133 ) 
    , .A3 ( wb_adr_i[1] ) ) ;
INVX1_RVT U120 (.A ( n31 ) , .Y ( n129 ) ) ;
INVX1_RVT U121 (.A ( n34 ) , .Y ( n128 ) ) ;
NAND2X0_RVT U122 (.A2 ( n15 ) , .A1 ( n101 ) , .Y ( n28 ) ) ;
NAND2X0_RVT U123 (.A2 ( n15 ) , .A1 ( n102 ) , .Y ( n26 ) ) ;
AO21X1_RVT U124 (.A1 ( n104 ) , .Y ( n31 ) , .A2 ( n15 ) , .A3 ( wb_rst_i ) ) ;
AO21X1_RVT U125 (.A1 ( n103 ) , .Y ( n34 ) , .A2 ( n15 ) , .A3 ( wb_rst_i ) ) ;
AND2X1_RVT U126 (.Y ( n30 ) , .A1 ( n15 ) , .A2 ( n31 ) ) ;
AND2X1_RVT U127 (.Y ( n33 ) , .A1 ( n15 ) , .A2 ( n34 ) ) ;
INVX1_RVT U128 (.A ( n19 ) , .Y ( n127 ) ) ;
AND2X1_RVT U129 (.Y ( n18 ) , .A1 ( n15 ) , .A2 ( n19 ) ) ;
AND2X1_RVT U130 (.Y ( n14 ) , .A1 ( n15 ) , .A2 ( n16 ) ) ;
INVX1_RVT U131 (.A ( n16 ) , .Y ( n132 ) ) ;
NOR2X0_RVT U132 (.Y ( n15 ) , .A2 ( wb_rst_i ) , .A1 ( n22 ) ) ;
NAND3X0_RVT U133 (.Y ( n19 ) , .A1 ( n17 ) , .A2 ( n2 ) , .A3 ( n20 ) ) ;
NAND2X0_RVT U134 (.A2 ( n22 ) , .A1 ( n21 ) , .Y ( n20 ) ) ;
NAND2X0_RVT U135 (.A2 ( n17 ) , .A1 ( n15 ) , .Y ( n16 ) ) ;
AO221X1_RVT U139 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n69 ) 
    , .A2 ( wb_dat_i[0] ) , .A3 ( prer[0] ) ) ;
AO221X1_RVT U140 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n70 ) 
    , .A2 ( wb_dat_i[1] ) , .A3 ( prer[1] ) ) ;
AO221X1_RVT U141 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n71 ) 
    , .A2 ( wb_dat_i[2] ) , .A3 ( prer[2] ) ) ;
AO221X1_RVT U142 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n72 ) 
    , .A2 ( wb_dat_i[3] ) , .A3 ( prer[3] ) ) ;
AO221X1_RVT U143 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n73 ) 
    , .A2 ( wb_dat_i[4] ) , .A3 ( prer[4] ) ) ;
AO221X1_RVT U144 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n74 ) 
    , .A2 ( wb_dat_i[5] ) , .A3 ( prer[5] ) ) ;
AO221X1_RVT U145 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n75 ) 
    , .A2 ( wb_dat_i[6] ) , .A3 ( prer[6] ) ) ;
AO221X1_RVT U146 (.A5 ( wb_rst_i ) , .A1 ( n9 ) , .A4 ( n26 ) , .Y ( n76 ) 
    , .A2 ( wb_dat_i[7] ) , .A3 ( prer[7] ) ) ;
AO221X1_RVT U147 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n77 ) 
    , .A2 ( wb_dat_i[0] ) , .A3 ( prer[8] ) ) ;
AO221X1_RVT U148 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n78 ) 
    , .A2 ( wb_dat_i[1] ) , .A3 ( prer[9] ) ) ;
AO221X1_RVT U149 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n79 ) 
    , .A2 ( wb_dat_i[2] ) , .A3 ( prer[10] ) ) ;
AO221X1_RVT U150 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n80 ) 
    , .A2 ( wb_dat_i[3] ) , .A3 ( prer[11] ) ) ;
AO221X1_RVT U151 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n81 ) 
    , .A2 ( wb_dat_i[4] ) , .A3 ( prer[12] ) ) ;
AO221X1_RVT U152 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n82 ) 
    , .A2 ( wb_dat_i[5] ) , .A3 ( prer[13] ) ) ;
AO221X1_RVT U153 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n83 ) 
    , .A2 ( wb_dat_i[6] ) , .A3 ( prer[14] ) ) ;
AO221X1_RVT U154 (.A5 ( wb_rst_i ) , .A1 ( n8 ) , .A4 ( n28 ) , .Y ( n84 ) 
    , .A2 ( wb_dat_i[7] ) , .A3 ( prer[15] ) ) ;
AO22X1_RVT U156 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n85 ) , .A4 ( wb_dat_i[0] ) 
    , .A1 ( txr[0] ) ) ;
AO22X1_RVT U157 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n86 ) , .A4 ( wb_dat_i[1] ) 
    , .A1 ( txr[1] ) ) ;
AO22X1_RVT U158 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n87 ) , .A4 ( wb_dat_i[2] ) 
    , .A1 ( txr[2] ) ) ;
AO22X1_RVT U159 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n88 ) , .A4 ( wb_dat_i[3] ) 
    , .A1 ( txr[3] ) ) ;
AO22X1_RVT U160 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n89 ) , .A4 ( wb_dat_i[4] ) 
    , .A1 ( txr[4] ) ) ;
AO22X1_RVT U161 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n90 ) , .A4 ( wb_dat_i[5] ) 
    , .A1 ( txr[5] ) ) ;
AO22X1_RVT U162 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n91 ) , .A4 ( wb_dat_i[6] ) 
    , .A1 ( txr[6] ) ) ;
AO22X1_RVT U163 (.A2 ( n129 ) , .A3 ( n30 ) , .Y ( n92 ) , .A4 ( wb_dat_i[7] ) 
    , .A1 ( txr[7] ) ) ;
AO22X1_RVT U164 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n93 ) , .A4 ( wb_dat_i[0] ) 
    , .A1 ( ctr[0] ) ) ;
AO22X1_RVT U165 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n94 ) , .A4 ( wb_dat_i[1] ) 
    , .A1 ( ctr[1] ) ) ;
AO22X1_RVT U166 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n95 ) , .A4 ( wb_dat_i[2] ) 
    , .A1 ( ctr[2] ) ) ;
AO22X1_RVT U167 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n96 ) , .A4 ( wb_dat_i[3] ) 
    , .A1 ( ctr[3] ) ) ;
AO22X1_RVT U168 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n97 ) , .A4 ( wb_dat_i[4] ) 
    , .A1 ( ctr[4] ) ) ;
AO22X1_RVT U169 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n98 ) , .A4 ( wb_dat_i[5] ) 
    , .A1 ( ctr[5] ) ) ;
AO22X1_RVT U170 (.A2 ( n128 ) , .A3 ( n33 ) , .Y ( n99 ) , .A4 ( wb_dat_i[6] ) 
    , .A1 ( ctr[6] ) ) ;
AO22X1_RVT U171 (.A2 ( ctr[7] ) , .A3 ( n33 ) , .Y ( n100 ) 
    , .A4 ( wb_dat_i[7] ) , .A1 ( n128 ) ) ;
NAND3X0_RVT U172 (.Y ( n22 ) , .A1 ( wb_stb_i ) , .A2 ( wb_cyc_i ) 
    , .A3 ( wb_we_i ) ) ;
AO22X1_RVT U173 (.A2 ( n127 ) , .A3 ( wb_dat_i[4] ) , .Y ( n67 ) , .A4 ( n18 ) 
    , .A1 ( cr[4] ) ) ;
AO22X1_RVT U174 (.A2 ( n127 ) , .A3 ( wb_dat_i[5] ) , .Y ( n66 ) , .A4 ( n18 ) 
    , .A1 ( cr[5] ) ) ;
AO22X1_RVT U175 (.A2 ( n127 ) , .A3 ( wb_dat_i[6] ) , .Y ( n65 ) , .A4 ( n18 ) 
    , .A1 ( cr[6] ) ) ;
AO22X1_RVT U176 (.A2 ( n127 ) , .A3 ( wb_dat_i[7] ) , .Y ( n64 ) , .A4 ( n18 ) 
    , .A1 ( cr[7] ) ) ;
NAND3X0_RVT U177 (.Y ( n17 ) , .A1 ( n15 ) , .A2 ( n25 ) , .A3 ( ctr[7] ) ) ;
AO22X1_RVT U178 (.A2 ( n132 ) , .A3 ( wb_dat_i[0] ) , .Y ( n61 ) , .A4 ( n14 ) 
    , .A1 ( cr[0] ) ) ;
DFFX1_RVT wb_ack_o_reg (.QN ( n1 ) , .D ( N20 ) , .CLK ( wb_clk_i ) 
    , .Q ( wb_ack_o ) ) ;
DFFARX1_RVT \cr_reg[0] (.QN ( n5 ) , .RSTB ( n7 ) , .D ( n61 ) 
    , .CLK ( wb_clk_i ) , .Q ( cr[0] ) ) ;
DFFASX1_RVT \prer_reg[4] (.D ( n73 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[4] ) ) ;
DFFASX1_RVT \prer_reg[3] (.D ( n72 ) , .SETB ( n3 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[3] ) ) ;
DFFASX1_RVT \prer_reg[2] (.D ( n71 ) , .SETB ( n3 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[2] ) ) ;
DFFASX1_RVT \prer_reg[12] (.D ( n81 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[12] ) ) ;
DFFASX1_RVT \prer_reg[11] (.D ( n80 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[11] ) ) ;
DFFASX1_RVT \prer_reg[10] (.D ( n79 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[10] ) ) ;
DFFASX1_RVT \prer_reg[15] (.D ( n84 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[15] ) ) ;
DFFASX1_RVT \prer_reg[14] (.D ( n83 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[14] ) ) ;
DFFASX1_RVT \prer_reg[13] (.D ( n82 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[13] ) ) ;
DFFASX1_RVT \prer_reg[9] (.D ( n78 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[9] ) ) ;
DFFASX1_RVT \prer_reg[8] (.D ( n77 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[8] ) ) ;
DFFASX1_RVT \prer_reg[7] (.D ( n76 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[7] ) ) ;
DFFASX1_RVT \prer_reg[6] (.D ( n75 ) , .SETB ( n7 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[6] ) ) ;
DFFASX1_RVT \prer_reg[5] (.D ( n74 ) , .SETB ( n3 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[5] ) ) ;
DFFASX1_RVT \prer_reg[1] (.D ( n70 ) , .SETB ( n3 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[1] ) ) ;
DFFASX1_RVT \prer_reg[0] (.D ( n69 ) , .SETB ( n3 ) , .CLK ( wb_clk_i ) 
    , .Q ( prer[0] ) ) ;
DFFARX1_RVT \cr_reg[7] (.QN ( n4 ) , .RSTB ( n6 ) , .D ( n64 ) 
    , .CLK ( wb_clk_i ) , .Q ( cr[7] ) ) ;
DFFX1_RVT \wb_dat_o_reg[6] (.D ( N49 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[6] ) ) ;
DFFX1_RVT \wb_dat_o_reg[4] (.D ( N47 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[4] ) ) ;
DFFX1_RVT \wb_dat_o_reg[3] (.D ( N46 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[3] ) ) ;
DFFX1_RVT \wb_dat_o_reg[2] (.D ( N45 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[2] ) ) ;
DFFX1_RVT \wb_dat_o_reg[5] (.D ( N48 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[5] ) ) ;
DFFX1_RVT \wb_dat_o_reg[7] (.D ( N50 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[7] ) ) ;
DFFX1_RVT \wb_dat_o_reg[1] (.D ( N44 ) , .CLK ( wb_clk_i ) , .Q ( wb_dat_o[1] ) ) ;
assign sda_pad_o = 1'b0;
endmodule


