//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/06/2025 at 09:31:14
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :pcm_slv_top.mw
// Cell Name    :pcm_slv_top
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./outputs/pcm_slv_top_extracted.v
//


module pcm_slv_top (din_i , ssel , dout_o , we_i , pcm_dout_o , re_i , 
    pcm_din_i , pcm_sync_i , pcm_clk_i , rst , clk );
input  [7:0] din_i ;
input  [2:0] ssel ;
output [7:0] dout_o ;
input  [1:0] we_i ;
output pcm_dout_o ;
input  re_i ;
input  pcm_din_i ;
input  pcm_sync_i ;
input  pcm_clk_i ;
input  rst ;
input  clk ;


wire [15:0] rx_reg ;
wire [15:0] rx_hold_reg ;
wire [7:0] tx_hold_byte_l ;
wire [14:0] tx_hold_reg ;
wire [3:0] tx_cnt ;
wire [7:0] psa ;
wire [7:0] tx_hold_byte_h ;

INVX2_RVT U11 (.A ( n126 ) , .Y ( n16 ) ) ;
INVX1_RVT U10 (.A ( n20 ) , .Y ( n15 ) ) ;
INVX0_RVT U9 (.A ( n127 ) , .Y ( n12 ) ) ;
INVX2_RVT U8 (.A ( n13 ) , .Y ( n11 ) ) ;
INVX0_RVT U7 (.A ( n21 ) , .Y ( n10 ) ) ;
INVX2_RVT U6 (.A ( n9 ) , .Y ( n8 ) ) ;
INVX2_RVT U5 (.A ( n19 ) , .Y ( n7 ) ) ;
INVX2_RVT U4 (.A ( n3 ) , .Y ( n6 ) ) ;
INVX1_RVT U3 (.A ( we_i[0] ) , .Y ( n5 ) ) ;
INVX1_RVT U2 (.A ( re_i ) , .Y ( n4 ) ) ;
INVX1_RVT U1 (.A ( we_i[1] ) , .Y ( n2 ) ) ;
NAND2X1_RVT U182 (.A2 ( n121 ) , .A1 ( pclk_s ) , .Y ( n3 ) ) ;
AO22X1_RVT U174 (.A2 ( n8 ) , .A3 ( rx_reg[11] ) , .Y ( n79 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[11] ) ) ;
AO22X1_RVT U175 (.A2 ( n8 ) , .A3 ( rx_reg[12] ) , .Y ( n80 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[12] ) ) ;
AO22X1_RVT U176 (.A2 ( n8 ) , .A3 ( rx_reg[13] ) , .Y ( n81 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[13] ) ) ;
AO22X1_RVT U177 (.A2 ( n8 ) , .A3 ( rx_reg[14] ) , .Y ( n82 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[14] ) ) ;
AO22X1_RVT U178 (.A2 ( n8 ) , .A3 ( rx_reg[15] ) , .Y ( n83 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[15] ) ) ;
AO22X1_RVT U179 (.A2 ( tx_hold_byte_l[0] ) , .A3 ( tx_hold_reg[0] ) 
    , .Y ( n114 ) , .A4 ( n17 ) , .A1 ( n7 ) ) ;
NAND3X0_RVT U180 (.Y ( n21 ) , .A1 ( tx_go ) , .A2 ( n6 ) , .A3 ( rst ) ) ;
NAND4X0_RVT U181 (.A2 ( tx_go_r1 ) , .A4 ( n122 ) , .A3 ( n6 ) , .Y ( n9 ) 
    , .A1 ( rst ) ) ;
AO22X1_RVT U183 (.A2 ( n123 ) , .A3 ( n35 ) , .Y ( n120 ) , .A4 ( tx_cnt[0] ) 
    , .A1 ( n10 ) ) ;
AND2X1_RVT U184 (.Y ( n35 ) , .A1 ( rst ) , .A2 ( n21 ) ) ;
AO22X1_RVT U185 (.A2 ( n3 ) , .A3 ( tx_go ) , .Y ( n40 ) , .A4 ( n6 ) 
    , .A1 ( tx_go_r1 ) ) ;
AO22X1_RVT U186 (.A2 ( n3 ) , .A3 ( psa[6] ) , .Y ( n58 ) , .A4 ( n6 ) 
    , .A1 ( psa[7] ) ) ;
AO22X1_RVT U187 (.A2 ( n3 ) , .A3 ( psa[5] ) , .Y ( n59 ) , .A4 ( n6 ) 
    , .A1 ( psa[6] ) ) ;
AO22X1_RVT U188 (.A2 ( n3 ) , .A3 ( psa[4] ) , .Y ( n60 ) , .A4 ( n6 ) 
    , .A1 ( psa[5] ) ) ;
AO22X1_RVT U189 (.A2 ( n3 ) , .A3 ( psa[3] ) , .Y ( n61 ) , .A4 ( n6 ) 
    , .A1 ( psa[4] ) ) ;
AO22X1_RVT U190 (.A2 ( n3 ) , .A3 ( psa[2] ) , .Y ( n62 ) , .A4 ( n6 ) 
    , .A1 ( psa[3] ) ) ;
AO22X1_RVT U191 (.A2 ( n3 ) , .A3 ( psa[1] ) , .Y ( n63 ) , .A4 ( n6 ) 
    , .A1 ( psa[2] ) ) ;
AO22X1_RVT U192 (.A2 ( n3 ) , .A3 ( psa[0] ) , .Y ( n64 ) , .A4 ( n6 ) 
    , .A1 ( psa[1] ) ) ;
AO22X1_RVT U193 (.A2 ( n3 ) , .A3 ( n38 ) , .Y ( n65 ) , .A4 ( n6 ) 
    , .A1 ( psa[0] ) ) ;
NAND2X0_RVT U194 (.A2 ( n19 ) , .A1 ( n29 ) , .Y ( n118 ) ) ;
NAND3X0_RVT U195 (.Y ( n29 ) , .A1 ( tx_go ) , .A2 ( n30 ) , .A3 ( rst ) ) ;
NAND3X0_RVT U196 (.Y ( n30 ) , .A1 ( n31 ) , .A2 ( n6 ) , .A3 ( tx_cnt[3] ) ) ;
OR2X1_RVT U200 (.Y ( n14 ) , .A2 ( tx_go_r1 ) , .A1 ( tx_go ) ) ;
AO22X1_RVT U201 (.A2 ( rx_reg[8] ) , .A3 ( rx_reg[0] ) , .Y ( dout_o[0] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U202 (.A2 ( rx_reg[9] ) , .A3 ( rx_reg[1] ) , .Y ( dout_o[1] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U203 (.A2 ( rx_reg[10] ) , .A3 ( rx_reg[2] ) , .Y ( dout_o[2] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U204 (.A2 ( rx_reg[11] ) , .A3 ( rx_reg[3] ) , .Y ( dout_o[3] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U205 (.A2 ( rx_reg[12] ) , .A3 ( rx_reg[4] ) , .Y ( dout_o[4] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U206 (.A2 ( rx_reg[13] ) , .A3 ( rx_reg[5] ) , .Y ( dout_o[5] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U207 (.A2 ( rx_reg[14] ) , .A3 ( rx_reg[6] ) , .Y ( dout_o[6] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U208 (.A2 ( rx_reg[15] ) , .A3 ( rx_reg[7] ) , .Y ( dout_o[7] ) 
    , .A4 ( n4 ) , .A1 ( re_i ) ) ;
AO22X1_RVT U209 (.A2 ( n5 ) , .A3 ( we_i[0] ) , .Y ( n41 ) , .A4 ( din_i[0] ) 
    , .A1 ( tx_hold_byte_l[0] ) ) ;
AO22X1_RVT U210 (.A2 ( n5 ) , .A3 ( din_i[1] ) , .Y ( n42 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[1] ) ) ;
AO22X1_RVT U211 (.A2 ( n5 ) , .A3 ( din_i[2] ) , .Y ( n43 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[2] ) ) ;
AO22X1_RVT U212 (.A2 ( n5 ) , .A3 ( din_i[3] ) , .Y ( n44 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[3] ) ) ;
AO22X1_RVT U213 (.A2 ( n5 ) , .A3 ( din_i[4] ) , .Y ( n45 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[4] ) ) ;
AO22X1_RVT U214 (.A2 ( n5 ) , .A3 ( din_i[5] ) , .Y ( n46 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[5] ) ) ;
AO22X1_RVT U215 (.A2 ( n5 ) , .A3 ( din_i[6] ) , .Y ( n47 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[6] ) ) ;
AO22X1_RVT U216 (.A2 ( n5 ) , .A3 ( din_i[7] ) , .Y ( n48 ) , .A4 ( we_i[0] ) 
    , .A1 ( tx_hold_byte_l[7] ) ) ;
AO22X1_RVT U217 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n49 ) , .A4 ( din_i[0] ) 
    , .A1 ( tx_hold_byte_h[0] ) ) ;
AO22X1_RVT U218 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n50 ) , .A4 ( din_i[1] ) 
    , .A1 ( tx_hold_byte_h[1] ) ) ;
AO22X1_RVT U219 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n51 ) , .A4 ( din_i[2] ) 
    , .A1 ( tx_hold_byte_h[2] ) ) ;
AO22X1_RVT U220 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n52 ) , .A4 ( din_i[3] ) 
    , .A1 ( tx_hold_byte_h[3] ) ) ;
AO22X1_RVT U221 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n53 ) , .A4 ( din_i[4] ) 
    , .A1 ( tx_hold_byte_h[4] ) ) ;
AO22X1_RVT U222 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n54 ) , .A4 ( din_i[5] ) 
    , .A1 ( tx_hold_byte_h[5] ) ) ;
AO22X1_RVT U223 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n55 ) , .A4 ( din_i[6] ) 
    , .A1 ( tx_hold_byte_h[6] ) ) ;
AO22X1_RVT U224 (.A2 ( n2 ) , .A3 ( we_i[1] ) , .Y ( n56 ) , .A4 ( din_i[7] ) 
    , .A1 ( tx_hold_byte_h[7] ) ) ;
AO22X1_RVT U225 (.A2 ( rx_hold_reg[14] ) , .A3 ( n12 ) , .Y ( n84 ) 
    , .A4 ( rx_hold_reg[15] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U226 (.A2 ( rx_hold_reg[13] ) , .A3 ( n12 ) , .Y ( n85 ) 
    , .A4 ( rx_hold_reg[14] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U227 (.A2 ( rx_hold_reg[12] ) , .A3 ( n12 ) , .Y ( n86 ) 
    , .A4 ( rx_hold_reg[13] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U228 (.A2 ( rx_hold_reg[11] ) , .A3 ( n12 ) , .Y ( n87 ) 
    , .A4 ( rx_hold_reg[12] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U229 (.A2 ( rx_hold_reg[10] ) , .A3 ( n12 ) , .Y ( n88 ) 
    , .A4 ( rx_hold_reg[11] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U230 (.A2 ( rx_hold_reg[9] ) , .A3 ( n12 ) , .Y ( n89 ) 
    , .A4 ( rx_hold_reg[10] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U231 (.A2 ( rx_hold_reg[8] ) , .A3 ( n12 ) , .Y ( n90 ) 
    , .A4 ( rx_hold_reg[9] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U232 (.A2 ( rx_hold_reg[7] ) , .A3 ( n12 ) , .Y ( n91 ) 
    , .A4 ( rx_hold_reg[8] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U233 (.A2 ( rx_hold_reg[6] ) , .A3 ( n12 ) , .Y ( n92 ) 
    , .A4 ( rx_hold_reg[7] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U234 (.A2 ( rx_hold_reg[5] ) , .A3 ( n12 ) , .Y ( n93 ) 
    , .A4 ( rx_hold_reg[6] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U235 (.A2 ( rx_hold_reg[4] ) , .A3 ( n12 ) , .Y ( n94 ) 
    , .A4 ( rx_hold_reg[5] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U236 (.A2 ( rx_hold_reg[3] ) , .A3 ( n12 ) , .Y ( n95 ) 
    , .A4 ( rx_hold_reg[4] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U237 (.A2 ( rx_hold_reg[2] ) , .A3 ( n12 ) , .Y ( n96 ) 
    , .A4 ( rx_hold_reg[3] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U238 (.A2 ( rx_hold_reg[1] ) , .A3 ( n12 ) , .Y ( n97 ) 
    , .A4 ( rx_hold_reg[2] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U239 (.A2 ( rx_hold_reg[0] ) , .A3 ( n12 ) , .Y ( n98 ) 
    , .A4 ( rx_hold_reg[1] ) , .A1 ( n11 ) ) ;
AO22X1_RVT U240 (.A2 ( n11 ) , .A3 ( n12 ) , .Y ( n99 ) , .A4 ( rx_hold_reg[0] ) 
    , .A1 ( rxd ) ) ;
NAND2X0_RVT U241 (.A2 ( n13 ) , .A1 ( rst ) , .Y ( n127 ) ) ;
OR2X1_RVT U242 (.Y ( n1 ) , .A2 ( pclk_s ) , .A1 ( n121 ) ) ;
INVX1_RVT U243 (.A ( ssel[0] ) , .Y ( n144 ) ) ;
AND3X1_RVT U244 (.A1 ( tx_cnt[1] ) , .Y ( n31 ) , .A2 ( tx_cnt[0] ) 
    , .A3 ( tx_cnt[2] ) ) ;
AO22X1_RVT U245 (.A2 ( n1 ) , .A3 ( pcm_din_i ) , .Y ( n39 ) , .A4 ( n155 ) 
    , .A1 ( rxd_t ) ) ;
AO22X1_RVT U246 (.A2 ( n1 ) , .A3 ( pcm_sync_i ) , .Y ( n66 ) , .A4 ( n155 ) 
    , .A1 ( n38 ) ) ;
INVX1_RVT U247 (.A ( ssel[2] ) , .Y ( n146 ) ) ;
INVX1_RVT U248 (.A ( ssel[1] ) , .Y ( n145 ) ) ;
NAND3X0_RVT U250 (.Y ( n13 ) , .A1 ( n155 ) , .A2 ( n14 ) , .A3 ( rst ) ) ;
NAND2X0_RVT U253 (.A2 ( rst ) , .A1 ( psync ) , .Y ( n19 ) ) ;
OR2X1_RVT U259 (.Y ( n20 ) , .A2 ( psync ) , .A1 ( n21 ) ) ;
AO22X1_RVT U260 (.A2 ( ssel[0] ) , .A3 ( psa[6] ) , .Y ( n139 ) , .A4 ( n144 ) 
    , .A1 ( psa[7] ) ) ;
AO22X1_RVT U261 (.A2 ( ssel[0] ) , .A3 ( psa[4] ) , .Y ( n138 ) , .A4 ( n144 ) 
    , .A1 ( psa[5] ) ) ;
AO22X1_RVT U262 (.A2 ( n139 ) , .A3 ( n138 ) , .Y ( n143 ) , .A4 ( n145 ) 
    , .A1 ( ssel[1] ) ) ;
AO22X1_RVT U263 (.A2 ( ssel[0] ) , .A3 ( psa[2] ) , .Y ( n141 ) , .A4 ( n144 ) 
    , .A1 ( psa[3] ) ) ;
AO22X1_RVT U264 (.A2 ( ssel[0] ) , .A3 ( psa[0] ) , .Y ( n140 ) , .A4 ( n144 ) 
    , .A1 ( psa[1] ) ) ;
AO22X1_RVT U265 (.A2 ( ssel[1] ) , .A3 ( n140 ) , .Y ( n142 ) , .A4 ( n145 ) 
    , .A1 ( n141 ) ) ;
AO22X1_RVT U266 (.A2 ( n143 ) , .A3 ( n142 ) , .Y ( N6 ) , .A4 ( n146 ) 
    , .A1 ( ssel[2] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[5] (.D ( n54 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[5] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[4] (.D ( n53 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[4] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[3] (.D ( n52 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[3] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[2] (.D ( n51 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[2] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[1] (.D ( n50 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[1] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[0] (.D ( n49 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[0] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[7] (.D ( n48 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[7] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[6] (.D ( n47 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[6] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[5] (.D ( n46 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[5] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[4] (.D ( n45 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[4] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[3] (.D ( n44 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[3] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[2] (.D ( n43 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[2] ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[1] (.D ( n42 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[1] ) ) ;
DFFX1_RVT \psa_reg[1] (.D ( n64 ) , .CLK ( clk ) , .Q ( psa[1] ) ) ;
DFFX1_RVT \psa_reg[3] (.D ( n62 ) , .CLK ( clk ) , .Q ( psa[3] ) ) ;
DFFX1_RVT \psa_reg[5] (.D ( n60 ) , .CLK ( clk ) , .Q ( psa[5] ) ) ;
DFFX1_RVT \psa_reg[0] (.D ( n65 ) , .CLK ( clk ) , .Q ( psa[0] ) ) ;
DFFX1_RVT \psa_reg[2] (.D ( n63 ) , .CLK ( clk ) , .Q ( psa[2] ) ) ;
DFFX1_RVT \psa_reg[4] (.D ( n61 ) , .CLK ( clk ) , .Q ( psa[4] ) ) ;
DFFX1_RVT \psa_reg[6] (.D ( n59 ) , .CLK ( clk ) , .Q ( psa[6] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[0] (.D ( n99 ) , .CLK ( clk ) , .Q ( rx_hold_reg[0] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[1] (.D ( n98 ) , .CLK ( clk ) , .Q ( rx_hold_reg[1] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[2] (.D ( n97 ) , .CLK ( clk ) , .Q ( rx_hold_reg[2] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[3] (.D ( n96 ) , .CLK ( clk ) , .Q ( rx_hold_reg[3] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[4] (.D ( n95 ) , .CLK ( clk ) , .Q ( rx_hold_reg[4] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[5] (.D ( n94 ) , .CLK ( clk ) , .Q ( rx_hold_reg[5] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[6] (.D ( n93 ) , .CLK ( clk ) , .Q ( rx_hold_reg[6] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[7] (.D ( n92 ) , .CLK ( clk ) , .Q ( rx_hold_reg[7] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[8] (.D ( n91 ) , .CLK ( clk ) , .Q ( rx_hold_reg[8] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[9] (.D ( n90 ) , .CLK ( clk ) , .Q ( rx_hold_reg[9] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[10] (.D ( n89 ) , .CLK ( clk ) 
    , .Q ( rx_hold_reg[10] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[11] (.D ( n88 ) , .CLK ( clk ) 
    , .Q ( rx_hold_reg[11] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[12] (.D ( n87 ) , .CLK ( clk ) 
    , .Q ( rx_hold_reg[12] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[13] (.D ( n86 ) , .CLK ( clk ) 
    , .Q ( rx_hold_reg[13] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[14] (.D ( n85 ) , .CLK ( clk ) 
    , .Q ( rx_hold_reg[14] ) ) ;
DFFX1_RVT \tx_cnt_reg[3] (.D ( n119 ) , .CLK ( clk ) , .Q ( tx_cnt[3] ) ) ;
DFFX1_RVT \tx_cnt_reg[2] (.QN ( n125 ) , .D ( n117 ) , .CLK ( clk ) 
    , .Q ( tx_cnt[2] ) ) ;
DFFX1_RVT \tx_cnt_reg[1] (.QN ( n124 ) , .D ( n116 ) , .CLK ( clk ) 
    , .Q ( tx_cnt[1] ) ) ;
DFFX1_RVT \tx_cnt_reg[0] (.QN ( n123 ) , .D ( n120 ) , .CLK ( clk ) 
    , .Q ( tx_cnt[0] ) ) ;
DFFX1_RVT tx_go_r1_reg (.D ( n40 ) , .CLK ( clk ) , .Q ( tx_go_r1 ) ) ;
DFFSSRX1_RVT psync_reg (.Q ( psync ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( pcm_sync_r2 ) , .RSTB ( n67 ) ) ;
DFFX1_RVT tx_go_reg (.QN ( n122 ) , .D ( n118 ) , .CLK ( clk ) , .Q ( tx_go ) ) ;
DFFX1_RVT pclk_r_reg (.QN ( n121 ) , .D ( pclk_s ) , .CLK ( clk ) ) ;
DFFX1_RVT pclk_s_reg (.D ( pclk_t ) , .CLK ( clk ) , .Q ( pclk_s ) ) ;
DFFX1_RVT pcm_sync_r2_reg (.D ( N6 ) , .CLK ( clk ) , .Q ( pcm_sync_r2 ) ) ;
DFFX1_RVT pclk_t_reg (.D ( pcm_clk_i ) , .CLK ( clk ) , .Q ( pclk_t ) ) ;
DFFX1_RVT pcm_sync_r3_reg (.QN ( n67 ) , .D ( pcm_sync_r2 ) , .CLK ( clk ) ) ;
AO21X1_RVT U130 (.A1 ( n10 ) , .Y ( n26 ) , .A2 ( n124 ) , .A3 ( n22 ) ) ;
INVX1_RVT U137 (.A ( n1 ) , .Y ( n155 ) ) ;
NAND2X0_RVT U138 (.A2 ( n9 ) , .A1 ( rst ) , .Y ( n126 ) ) ;
AND3X1_RVT U139 (.A1 ( n20 ) , .Y ( n17 ) , .A2 ( n19 ) , .A3 ( rst ) ) ;
AO22X1_RVT U140 (.A2 ( n21 ) , .A3 ( n10 ) , .Y ( n22 ) , .A4 ( n123 ) 
    , .A1 ( rst ) ) ;
AO222X1_RVT U141 (.A1 ( tx_hold_reg[14] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[7] ) , .A3 ( pcm_dout_o ) , .A2 ( n15 ) , .Y ( n100 ) 
    , .A4 ( n17 ) ) ;
AO222X1_RVT U142 (.A1 ( tx_hold_reg[13] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[6] ) , .A3 ( tx_hold_reg[14] ) , .A2 ( n15 ) 
    , .Y ( n101 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U143 (.A1 ( tx_hold_reg[12] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[5] ) , .A3 ( tx_hold_reg[13] ) , .A2 ( n15 ) 
    , .Y ( n102 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U144 (.A1 ( tx_hold_reg[11] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[4] ) , .A3 ( tx_hold_reg[12] ) , .A2 ( n15 ) 
    , .Y ( n103 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U145 (.A1 ( tx_hold_reg[10] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[3] ) , .A3 ( tx_hold_reg[11] ) , .A2 ( n15 ) 
    , .Y ( n104 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U146 (.A1 ( tx_hold_reg[9] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[2] ) , .A3 ( tx_hold_reg[10] ) , .A2 ( n15 ) 
    , .Y ( n105 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U147 (.A1 ( tx_hold_reg[8] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[1] ) , .A3 ( tx_hold_reg[9] ) , .A2 ( n15 ) 
    , .Y ( n106 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U148 (.A1 ( tx_hold_reg[7] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_h[0] ) , .A3 ( tx_hold_reg[8] ) , .A2 ( n15 ) 
    , .Y ( n107 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U149 (.A1 ( tx_hold_reg[6] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[7] ) , .A3 ( tx_hold_reg[7] ) , .A2 ( n15 ) 
    , .Y ( n108 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U150 (.A1 ( tx_hold_reg[5] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[6] ) , .A3 ( tx_hold_reg[6] ) , .A2 ( n15 ) 
    , .Y ( n109 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U151 (.A1 ( tx_hold_reg[4] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[5] ) , .A3 ( tx_hold_reg[5] ) , .A2 ( n15 ) 
    , .Y ( n110 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U152 (.A1 ( tx_hold_reg[3] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[4] ) , .A3 ( tx_hold_reg[4] ) , .A2 ( n15 ) 
    , .Y ( n111 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U153 (.A1 ( tx_hold_reg[2] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[3] ) , .A3 ( tx_hold_reg[3] ) , .A2 ( n15 ) 
    , .Y ( n112 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U154 (.A1 ( tx_hold_reg[1] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[2] ) , .A3 ( tx_hold_reg[2] ) , .A2 ( n15 ) 
    , .Y ( n113 ) , .A4 ( n17 ) ) ;
AO222X1_RVT U155 (.A1 ( tx_hold_reg[0] ) , .A5 ( n7 ) 
    , .A6 ( tx_hold_byte_l[1] ) , .A3 ( tx_hold_reg[1] ) , .A2 ( n15 ) 
    , .Y ( n115 ) , .A4 ( n17 ) ) ;
AO21X1_RVT U156 (.A1 ( tx_cnt[2] ) , .Y ( n117 ) , .A2 ( n26 ) , .A3 ( n27 ) ) ;
AND4X1_RVT U157 (.Y ( n27 ) , .A1 ( tx_cnt[1] ) , .A3 ( n10 ) , .A4 ( n125 ) 
    , .A2 ( tx_cnt[0] ) ) ;
AO22X1_RVT U158 (.A2 ( n32 ) , .A3 ( n33 ) , .Y ( n119 ) , .A4 ( n31 ) 
    , .A1 ( tx_cnt[3] ) ) ;
NOR2X0_RVT U159 (.Y ( n33 ) , .A2 ( tx_cnt[3] ) , .A1 ( n21 ) ) ;
AO21X1_RVT U160 (.A1 ( n10 ) , .Y ( n32 ) , .A2 ( n125 ) , .A3 ( n26 ) ) ;
AO22X1_RVT U161 (.A2 ( n22 ) , .A3 ( n23 ) , .Y ( n116 ) , .A4 ( tx_cnt[0] ) 
    , .A1 ( tx_cnt[1] ) ) ;
AND2X1_RVT U162 (.Y ( n23 ) , .A1 ( n10 ) , .A2 ( n124 ) ) ;
AO22X1_RVT U163 (.A2 ( n8 ) , .A3 ( rx_reg[0] ) , .Y ( n68 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[0] ) ) ;
AO22X1_RVT U164 (.A2 ( n8 ) , .A3 ( rx_reg[1] ) , .Y ( n69 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[1] ) ) ;
AO22X1_RVT U165 (.A2 ( n8 ) , .A3 ( rx_reg[2] ) , .Y ( n70 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[2] ) ) ;
AO22X1_RVT U166 (.A2 ( n8 ) , .A3 ( rx_reg[3] ) , .Y ( n71 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[3] ) ) ;
AO22X1_RVT U167 (.A2 ( n8 ) , .A3 ( rx_reg[4] ) , .Y ( n72 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[4] ) ) ;
AO22X1_RVT U168 (.A2 ( n8 ) , .A3 ( rx_reg[5] ) , .Y ( n73 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[5] ) ) ;
AO22X1_RVT U169 (.A2 ( n8 ) , .A3 ( rx_reg[6] ) , .Y ( n74 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[6] ) ) ;
AO22X1_RVT U170 (.A2 ( n8 ) , .A3 ( rx_reg[7] ) , .Y ( n75 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[7] ) ) ;
AO22X1_RVT U171 (.A2 ( n8 ) , .A3 ( rx_reg[8] ) , .Y ( n76 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[8] ) ) ;
AO22X1_RVT U172 (.A2 ( n8 ) , .A3 ( rx_reg[9] ) , .Y ( n77 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[9] ) ) ;
AO22X1_RVT U173 (.A2 ( n8 ) , .A3 ( rx_reg[10] ) , .Y ( n78 ) , .A4 ( n16 ) 
    , .A1 ( rx_hold_reg[10] ) ) ;
DFFX1_RVT rxd_reg (.D ( rxd_t ) , .CLK ( clk ) , .Q ( rxd ) ) ;
DFFX1_RVT \tx_hold_reg_reg[15] (.D ( n100 ) , .CLK ( clk ) , .Q ( pcm_dout_o ) ) ;
DFFX1_RVT \psa_reg[7] (.D ( n58 ) , .CLK ( clk ) , .Q ( psa[7] ) ) ;
DFFX1_RVT pcm_sync_r1_reg (.D ( n66 ) , .CLK ( clk ) , .Q ( n38 ) ) ;
DFFX1_RVT \tx_hold_byte_l_reg[0] (.D ( n41 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_l[0] ) ) ;
DFFX1_RVT \rx_hold_reg_reg[15] (.D ( n84 ) , .CLK ( clk ) 
    , .Q ( rx_hold_reg[15] ) ) ;
DFFX1_RVT rxd_t_reg (.D ( n39 ) , .CLK ( clk ) , .Q ( rxd_t ) ) ;
DFFX1_RVT \rx_reg_reg[7] (.D ( n75 ) , .CLK ( clk ) , .Q ( rx_reg[7] ) ) ;
DFFX1_RVT \rx_reg_reg[6] (.D ( n74 ) , .CLK ( clk ) , .Q ( rx_reg[6] ) ) ;
DFFX1_RVT \rx_reg_reg[5] (.D ( n73 ) , .CLK ( clk ) , .Q ( rx_reg[5] ) ) ;
DFFX1_RVT \rx_reg_reg[4] (.D ( n72 ) , .CLK ( clk ) , .Q ( rx_reg[4] ) ) ;
DFFX1_RVT \rx_reg_reg[3] (.D ( n71 ) , .CLK ( clk ) , .Q ( rx_reg[3] ) ) ;
DFFX1_RVT \rx_reg_reg[2] (.D ( n70 ) , .CLK ( clk ) , .Q ( rx_reg[2] ) ) ;
DFFX1_RVT \rx_reg_reg[1] (.D ( n69 ) , .CLK ( clk ) , .Q ( rx_reg[1] ) ) ;
DFFX1_RVT \rx_reg_reg[0] (.D ( n68 ) , .CLK ( clk ) , .Q ( rx_reg[0] ) ) ;
DFFX1_RVT \rx_reg_reg[15] (.D ( n83 ) , .CLK ( clk ) , .Q ( rx_reg[15] ) ) ;
DFFX1_RVT \rx_reg_reg[14] (.D ( n82 ) , .CLK ( clk ) , .Q ( rx_reg[14] ) ) ;
DFFX1_RVT \rx_reg_reg[13] (.D ( n81 ) , .CLK ( clk ) , .Q ( rx_reg[13] ) ) ;
DFFX1_RVT \rx_reg_reg[12] (.D ( n80 ) , .CLK ( clk ) , .Q ( rx_reg[12] ) ) ;
DFFX1_RVT \rx_reg_reg[11] (.D ( n79 ) , .CLK ( clk ) , .Q ( rx_reg[11] ) ) ;
DFFX1_RVT \rx_reg_reg[10] (.D ( n78 ) , .CLK ( clk ) , .Q ( rx_reg[10] ) ) ;
DFFX1_RVT \rx_reg_reg[9] (.D ( n77 ) , .CLK ( clk ) , .Q ( rx_reg[9] ) ) ;
DFFX1_RVT \rx_reg_reg[8] (.D ( n76 ) , .CLK ( clk ) , .Q ( rx_reg[8] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[0] (.D ( n114 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[0] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[1] (.D ( n115 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[1] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[2] (.D ( n113 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[2] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[3] (.D ( n112 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[3] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[4] (.D ( n111 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[4] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[5] (.D ( n110 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[5] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[6] (.D ( n109 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[6] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[7] (.D ( n108 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[7] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[8] (.D ( n107 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[8] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[9] (.D ( n106 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[9] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[10] (.D ( n105 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[10] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[11] (.D ( n104 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[11] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[12] (.D ( n103 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[12] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[13] (.D ( n102 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[13] ) ) ;
DFFX1_RVT \tx_hold_reg_reg[14] (.D ( n101 ) , .CLK ( clk ) 
    , .Q ( tx_hold_reg[14] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[7] (.D ( n56 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[7] ) ) ;
DFFX1_RVT \tx_hold_byte_h_reg[6] (.D ( n55 ) , .CLK ( clk ) 
    , .Q ( tx_hold_byte_h[6] ) ) ;
endmodule


