//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/06/2025 at 09:31:54
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :sasc_top.mw
// Cell Name    :sasc_top
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./outputs/sasc_top_extracted.v
//


module sasc_fifo4_0 (clk , rst , clr , we , re , full , empty , dout , 
    din );
input  clk ;
input  rst ;
input  clr ;
input  we ;
input  re ;
output full ;
output empty ;
output [7:0] dout ;
input  [7:0] din ;


wire [1:0] wp ;

INVX1_RVT U4 (.A ( n125 ) , .Y ( n19 ) ) ;
INVX1_RVT U3 (.A ( n128 ) , .Y ( n15 ) ) ;
INVX1_RVT U2 (.A ( n126 ) , .Y ( n12 ) ) ;
INVX1_RVT U1 (.A ( n129 ) , .Y ( n10 ) ) ;
NAND3X1_RVT U27 (.Y ( n129 ) , .A1 ( wp[0] ) , .A2 ( wp[1] ) , .A3 ( we ) ) ;
NAND3X1_RVT U28 (.Y ( n126 ) , .A1 ( wp[0] ) , .A2 ( n138 ) , .A3 ( we ) ) ;
NAND2X1_RVT U49 (.A2 ( n138 ) , .A1 ( n127 ) , .Y ( n125 ) ) ;
DFFX1_RVT \mem_reg[2][2] (.D ( n106 ) , .CLK ( clk ) , .Q ( \mem[2][2] ) ) ;
DFFX1_RVT \mem_reg[2][1] (.D ( n107 ) , .CLK ( clk ) , .Q ( \mem[2][1] ) ) ;
DFFX1_RVT \mem_reg[2][0] (.D ( n108 ) , .CLK ( clk ) , .Q ( \mem[2][0] ) ) ;
DFFX1_RVT gb_reg (.QN ( n136 ) , .D ( n117 ) , .CLK ( clk ) , .Q ( gb ) ) ;
DFFARX1_RVT \rp_reg[0] (.QN ( n17 ) , .RSTB ( rst ) , .D ( n83 ) , .CLK ( clk ) 
    , .Q ( N8 ) ) ;
DFFARX1_RVT \rp_reg[1] (.QN ( n16 ) , .RSTB ( rst ) , .D ( n84 ) , .CLK ( clk ) 
    , .Q ( N9 ) ) ;
DFFARX1_RVT \wp_reg[1] (.QN ( n138 ) , .RSTB ( rst ) , .D ( n82 ) , .CLK ( clk ) 
    , .Q ( wp[1] ) ) ;
DFFARX1_RVT \wp_reg[0] (.QN ( n137 ) , .RSTB ( rst ) , .D ( n81 ) , .CLK ( clk ) 
    , .Q ( wp[0] ) ) ;
INVX1_RVT U7 (.A ( n131 ) , .Y ( n78 ) ) ;
INVX1_RVT U8 (.A ( n119 ) , .Y ( n18 ) ) ;
INVX1_RVT U9 (.A ( n122 ) , .Y ( n80 ) ) ;
AO22X1_RVT U10 (.A2 ( n10 ) , .A3 ( \mem[3][0] ) , .Y ( n116 ) , .A4 ( n129 ) 
    , .A1 ( din[0] ) ) ;
AO22X1_RVT U11 (.A2 ( n10 ) , .A3 ( \mem[3][1] ) , .Y ( n115 ) , .A4 ( n129 ) 
    , .A1 ( din[1] ) ) ;
AO22X1_RVT U12 (.A2 ( n10 ) , .A3 ( \mem[3][2] ) , .Y ( n114 ) , .A4 ( n129 ) 
    , .A1 ( din[2] ) ) ;
AO22X1_RVT U13 (.A2 ( n10 ) , .A3 ( \mem[3][3] ) , .Y ( n113 ) , .A4 ( n129 ) 
    , .A1 ( din[3] ) ) ;
AO22X1_RVT U14 (.A2 ( n10 ) , .A3 ( \mem[3][4] ) , .Y ( n112 ) , .A4 ( n129 ) 
    , .A1 ( din[4] ) ) ;
AO22X1_RVT U15 (.A2 ( n10 ) , .A3 ( \mem[3][5] ) , .Y ( n111 ) , .A4 ( n129 ) 
    , .A1 ( din[5] ) ) ;
AO22X1_RVT U16 (.A2 ( n10 ) , .A3 ( \mem[3][6] ) , .Y ( n110 ) , .A4 ( n129 ) 
    , .A1 ( din[6] ) ) ;
AO22X1_RVT U17 (.A2 ( n10 ) , .A3 ( \mem[3][7] ) , .Y ( n109 ) , .A4 ( n129 ) 
    , .A1 ( din[7] ) ) ;
AO22X1_RVT U18 (.A2 ( din[0] ) , .A3 ( \mem[1][0] ) , .Y ( n100 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U19 (.A2 ( din[1] ) , .A3 ( \mem[1][1] ) , .Y ( n99 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U20 (.A2 ( din[2] ) , .A3 ( \mem[1][2] ) , .Y ( n98 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U21 (.A2 ( din[3] ) , .A3 ( \mem[1][3] ) , .Y ( n97 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U22 (.A2 ( din[4] ) , .A3 ( \mem[1][4] ) , .Y ( n96 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U23 (.A2 ( din[5] ) , .A3 ( \mem[1][5] ) , .Y ( n95 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U24 (.A2 ( din[6] ) , .A3 ( \mem[1][6] ) , .Y ( n94 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AO22X1_RVT U25 (.A2 ( din[7] ) , .A3 ( \mem[1][7] ) , .Y ( n93 ) , .A4 ( n126 ) 
    , .A1 ( n12 ) ) ;
AND3X1_RVT U26 (.A1 ( n118 ) , .Y ( full ) , .A2 ( gb ) , .A3 ( n78 ) ) ;
AO22X1_RVT U29 (.A2 ( din[0] ) , .A3 ( \mem[2][0] ) , .Y ( n108 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U30 (.A2 ( din[0] ) , .A3 ( \mem[0][0] ) , .Y ( n92 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U31 (.A2 ( din[1] ) , .A3 ( \mem[2][1] ) , .Y ( n107 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U32 (.A2 ( din[2] ) , .A3 ( \mem[2][2] ) , .Y ( n106 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U33 (.A2 ( din[3] ) , .A3 ( \mem[2][3] ) , .Y ( n105 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U34 (.A2 ( din[4] ) , .A3 ( \mem[2][4] ) , .Y ( n104 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U35 (.A2 ( din[5] ) , .A3 ( \mem[2][5] ) , .Y ( n103 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U36 (.A2 ( din[6] ) , .A3 ( \mem[2][6] ) , .Y ( n102 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U37 (.A2 ( din[7] ) , .A3 ( \mem[2][7] ) , .Y ( n101 ) , .A4 ( n128 ) 
    , .A1 ( n15 ) ) ;
AO22X1_RVT U38 (.A2 ( din[1] ) , .A3 ( \mem[0][1] ) , .Y ( n91 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U39 (.A2 ( din[2] ) , .A3 ( \mem[0][2] ) , .Y ( n90 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U40 (.A2 ( din[3] ) , .A3 ( \mem[0][3] ) , .Y ( n89 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U41 (.A2 ( din[4] ) , .A3 ( \mem[0][4] ) , .Y ( n88 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U42 (.A2 ( din[5] ) , .A3 ( \mem[0][5] ) , .Y ( n87 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U43 (.A2 ( din[6] ) , .A3 ( \mem[0][6] ) , .Y ( n86 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AO22X1_RVT U44 (.A2 ( din[7] ) , .A3 ( \mem[0][7] ) , .Y ( n85 ) , .A4 ( n125 ) 
    , .A1 ( n19 ) ) ;
AND2X1_RVT U45 (.Y ( n127 ) , .A1 ( we ) , .A2 ( n137 ) ) ;
XNOR2X1_RVT U46 (.A2 ( n137 ) , .A1 ( N8 ) , .Y ( n131 ) ) ;
XNOR2X1_RVT U47 (.A2 ( wp[1] ) , .A1 ( N9 ) , .Y ( n118 ) ) ;
NAND2X0_RVT U48 (.A2 ( wp[1] ) , .A1 ( n127 ) , .Y ( n128 ) ) ;
AND3X1_RVT U50 (.A1 ( rst ) , .Y ( n132 ) , .A2 ( n79 ) , .A3 ( n131 ) ) ;
NAND2X0_RVT U51 (.A2 ( n134 ) , .A1 ( n135 ) , .Y ( n117 ) ) ;
NAND3X0_RVT U52 (.Y ( n135 ) , .A1 ( n80 ) , .A2 ( rst ) , .A3 ( gb ) ) ;
NAND3X0_RVT U53 (.Y ( n134 ) , .A1 ( n133 ) , .A2 ( we ) , .A3 ( n132 ) ) ;
XNOR2X1_RVT U54 (.A2 ( n130 ) , .A1 ( N9 ) , .Y ( n133 ) ) ;
AO22X1_RVT U55 (.A2 ( wp[0] ) , .A3 ( n127 ) , .Y ( n81 ) , .A4 ( n79 ) 
    , .A1 ( n18 ) ) ;
AO22X1_RVT U56 (.A2 ( wp[1] ) , .A3 ( n120 ) , .Y ( n82 ) , .A4 ( n130 ) 
    , .A1 ( n18 ) ) ;
AND2X1_RVT U57 (.Y ( n120 ) , .A1 ( n119 ) , .A2 ( n79 ) ) ;
OR2X1_RVT U58 (.Y ( n119 ) , .A2 ( clr ) , .A1 ( we ) ) ;
AND3X1_RVT U59 (.A1 ( n118 ) , .Y ( empty ) , .A2 ( n136 ) , .A3 ( n78 ) ) ;
AO22X1_RVT U60 (.A2 ( N8 ) , .A3 ( n121 ) , .Y ( n83 ) , .A4 ( n122 ) 
    , .A1 ( n80 ) ) ;
AND2X1_RVT U61 (.Y ( n121 ) , .A1 ( n79 ) , .A2 ( n17 ) ) ;
AO22X1_RVT U62 (.A2 ( N9 ) , .A3 ( n124 ) , .Y ( n84 ) , .A4 ( n79 ) 
    , .A1 ( n80 ) ) ;
OAI22X1_RVT U63 (.Y ( n124 ) , .A4 ( n123 ) , .A3 ( n17 ) , .A2 ( n16 ) 
    , .A1 ( N8 ) ) ;
NAND2X0_RVT U64 (.A2 ( n16 ) , .A1 ( n122 ) , .Y ( n123 ) ) ;
XNOR2X1_RVT U65 (.A2 ( wp[1] ) , .A1 ( n137 ) , .Y ( n130 ) ) ;
OR2X1_RVT U66 (.Y ( n122 ) , .A2 ( re ) , .A1 ( clr ) ) ;
INVX1_RVT U67 (.A ( clr ) , .Y ( n79 ) ) ;
AND2X1_RVT U68 (.Y ( n14 ) , .A1 ( n17 ) , .A2 ( n16 ) ) ;
AND2X1_RVT U69 (.Y ( n13 ) , .A1 ( N8 ) , .A2 ( n16 ) ) ;
AND2X1_RVT U70 (.Y ( n9 ) , .A1 ( N9 ) , .A2 ( N8 ) ) ;
AND2X1_RVT U71 (.Y ( n8 ) , .A1 ( N9 ) , .A2 ( n17 ) ) ;
AO22X1_RVT U72 (.A2 ( n9 ) , .A3 ( \mem[2][0] ) , .Y ( n1 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][0] ) ) ;
AO221X1_RVT U73 (.A5 ( n1 ) , .A1 ( \mem[0][0] ) , .A4 ( n13 ) , .Y ( dout[0] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][0] ) ) ;
AO22X1_RVT U74 (.A2 ( n9 ) , .A3 ( \mem[2][1] ) , .Y ( n2 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][1] ) ) ;
AO221X1_RVT U75 (.A5 ( n2 ) , .A1 ( \mem[0][1] ) , .A4 ( n13 ) , .Y ( dout[1] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][1] ) ) ;
AO22X1_RVT U76 (.A2 ( n9 ) , .A3 ( \mem[2][2] ) , .Y ( n3 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][2] ) ) ;
AO221X1_RVT U77 (.A5 ( n3 ) , .A1 ( \mem[0][2] ) , .A4 ( n13 ) , .Y ( dout[2] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][2] ) ) ;
AO22X1_RVT U78 (.A2 ( n9 ) , .A3 ( \mem[2][3] ) , .Y ( n4 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][3] ) ) ;
AO221X1_RVT U79 (.A5 ( n4 ) , .A1 ( \mem[0][3] ) , .A4 ( n13 ) , .Y ( dout[3] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][3] ) ) ;
AO22X1_RVT U80 (.A2 ( n9 ) , .A3 ( \mem[2][4] ) , .Y ( n5 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][4] ) ) ;
AO221X1_RVT U81 (.A5 ( n5 ) , .A1 ( \mem[0][4] ) , .A4 ( n13 ) , .Y ( dout[4] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][4] ) ) ;
AO22X1_RVT U82 (.A2 ( n9 ) , .A3 ( \mem[2][5] ) , .Y ( n6 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][5] ) ) ;
AO221X1_RVT U83 (.A5 ( n6 ) , .A1 ( \mem[0][5] ) , .A4 ( n13 ) , .Y ( dout[5] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][5] ) ) ;
AO22X1_RVT U84 (.A2 ( n9 ) , .A3 ( \mem[2][6] ) , .Y ( n7 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][6] ) ) ;
AO221X1_RVT U85 (.A5 ( n7 ) , .A1 ( \mem[0][6] ) , .A4 ( n13 ) , .Y ( dout[6] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][6] ) ) ;
AO22X1_RVT U86 (.A2 ( n9 ) , .A3 ( \mem[2][7] ) , .Y ( n11 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][7] ) ) ;
AO221X1_RVT U87 (.A5 ( n11 ) , .A1 ( \mem[0][7] ) , .A4 ( n13 ) , .Y ( dout[7] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][7] ) ) ;
DFFX1_RVT \mem_reg[3][7] (.D ( n109 ) , .CLK ( clk ) , .Q ( \mem[3][7] ) ) ;
DFFX1_RVT \mem_reg[3][6] (.D ( n110 ) , .CLK ( clk ) , .Q ( \mem[3][6] ) ) ;
DFFX1_RVT \mem_reg[3][5] (.D ( n111 ) , .CLK ( clk ) , .Q ( \mem[3][5] ) ) ;
DFFX1_RVT \mem_reg[3][4] (.D ( n112 ) , .CLK ( clk ) , .Q ( \mem[3][4] ) ) ;
DFFX1_RVT \mem_reg[3][3] (.D ( n113 ) , .CLK ( clk ) , .Q ( \mem[3][3] ) ) ;
DFFX1_RVT \mem_reg[3][2] (.D ( n114 ) , .CLK ( clk ) , .Q ( \mem[3][2] ) ) ;
DFFX1_RVT \mem_reg[3][1] (.D ( n115 ) , .CLK ( clk ) , .Q ( \mem[3][1] ) ) ;
DFFX1_RVT \mem_reg[3][0] (.D ( n116 ) , .CLK ( clk ) , .Q ( \mem[3][0] ) ) ;
DFFX1_RVT \mem_reg[0][7] (.D ( n85 ) , .CLK ( clk ) , .Q ( \mem[0][7] ) ) ;
DFFX1_RVT \mem_reg[0][6] (.D ( n86 ) , .CLK ( clk ) , .Q ( \mem[0][6] ) ) ;
DFFX1_RVT \mem_reg[0][5] (.D ( n87 ) , .CLK ( clk ) , .Q ( \mem[0][5] ) ) ;
DFFX1_RVT \mem_reg[0][4] (.D ( n88 ) , .CLK ( clk ) , .Q ( \mem[0][4] ) ) ;
DFFX1_RVT \mem_reg[0][3] (.D ( n89 ) , .CLK ( clk ) , .Q ( \mem[0][3] ) ) ;
DFFX1_RVT \mem_reg[0][2] (.D ( n90 ) , .CLK ( clk ) , .Q ( \mem[0][2] ) ) ;
DFFX1_RVT \mem_reg[0][1] (.D ( n91 ) , .CLK ( clk ) , .Q ( \mem[0][1] ) ) ;
DFFX1_RVT \mem_reg[0][0] (.D ( n92 ) , .CLK ( clk ) , .Q ( \mem[0][0] ) ) ;
DFFX1_RVT \mem_reg[1][7] (.D ( n93 ) , .CLK ( clk ) , .Q ( \mem[1][7] ) ) ;
DFFX1_RVT \mem_reg[1][6] (.D ( n94 ) , .CLK ( clk ) , .Q ( \mem[1][6] ) ) ;
DFFX1_RVT \mem_reg[1][5] (.D ( n95 ) , .CLK ( clk ) , .Q ( \mem[1][5] ) ) ;
DFFX1_RVT \mem_reg[1][4] (.D ( n96 ) , .CLK ( clk ) , .Q ( \mem[1][4] ) ) ;
DFFX1_RVT \mem_reg[1][3] (.D ( n97 ) , .CLK ( clk ) , .Q ( \mem[1][3] ) ) ;
DFFX1_RVT \mem_reg[1][2] (.D ( n98 ) , .CLK ( clk ) , .Q ( \mem[1][2] ) ) ;
DFFX1_RVT \mem_reg[1][1] (.D ( n99 ) , .CLK ( clk ) , .Q ( \mem[1][1] ) ) ;
DFFX1_RVT \mem_reg[1][0] (.D ( n100 ) , .CLK ( clk ) , .Q ( \mem[1][0] ) ) ;
DFFX1_RVT \mem_reg[2][7] (.D ( n101 ) , .CLK ( clk ) , .Q ( \mem[2][7] ) ) ;
DFFX1_RVT \mem_reg[2][6] (.D ( n102 ) , .CLK ( clk ) , .Q ( \mem[2][6] ) ) ;
DFFX1_RVT \mem_reg[2][5] (.D ( n103 ) , .CLK ( clk ) , .Q ( \mem[2][5] ) ) ;
DFFX1_RVT \mem_reg[2][4] (.D ( n104 ) , .CLK ( clk ) , .Q ( \mem[2][4] ) ) ;
DFFX1_RVT \mem_reg[2][3] (.D ( n105 ) , .CLK ( clk ) , .Q ( \mem[2][3] ) ) ;
endmodule




module sasc_fifo4_1 (clk , rst , clr , we , re , full , empty , dout , 
    din );
input  clk ;
input  rst ;
input  clr ;
input  we ;
input  re ;
output full ;
output empty ;
output [7:0] dout ;
input  [7:0] din ;


wire [1:0] wp ;

INVX1_RVT U5 (.A ( n29 ) , .Y ( n82 ) ) ;
INVX1_RVT U4 (.A ( n26 ) , .Y ( n81 ) ) ;
INVX1_RVT U2 (.A ( n28 ) , .Y ( n76 ) ) ;
INVX1_RVT U1 (.A ( n25 ) , .Y ( n75 ) ) ;
NAND3X1_RVT U31 (.Y ( n25 ) , .A1 ( wp[0] ) , .A2 ( wp[1] ) , .A3 ( we ) ) ;
NAND3X1_RVT U32 (.Y ( n28 ) , .A1 ( wp[0] ) , .A2 ( n10 ) , .A3 ( we ) ) ;
NAND2X1_RVT U56 (.A2 ( wp[1] ) , .A1 ( n27 ) , .Y ( n26 ) ) ;
NAND2X1_RVT U57 (.A2 ( n10 ) , .A1 ( n27 ) , .Y ( n29 ) ) ;
AO22X1_RVT U24 (.A2 ( din[1] ) , .A3 ( \mem[1][1] ) , .Y ( n55 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U25 (.A2 ( din[2] ) , .A3 ( \mem[1][2] ) , .Y ( n56 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U26 (.A2 ( din[3] ) , .A3 ( \mem[1][3] ) , .Y ( n57 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U27 (.A2 ( din[4] ) , .A3 ( \mem[1][4] ) , .Y ( n58 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U28 (.A2 ( din[5] ) , .A3 ( \mem[1][5] ) , .Y ( n59 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U29 (.A2 ( din[6] ) , .A3 ( \mem[1][6] ) , .Y ( n60 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U30 (.A2 ( din[7] ) , .A3 ( \mem[1][7] ) , .Y ( n61 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
AO22X1_RVT U33 (.A2 ( N8 ) , .A3 ( n33 ) , .Y ( n71 ) , .A4 ( n32 ) , .A1 ( n80 ) ) ;
AND2X1_RVT U34 (.Y ( n33 ) , .A1 ( n78 ) , .A2 ( n14 ) ) ;
AO22X1_RVT U35 (.A2 ( N9 ) , .A3 ( n30 ) , .Y ( n70 ) , .A4 ( n78 ) , .A1 ( n80 ) ) ;
OAI22X1_RVT U36 (.Y ( n30 ) , .A4 ( n31 ) , .A3 ( n14 ) , .A2 ( n13 ) 
    , .A1 ( N8 ) ) ;
NAND2X0_RVT U37 (.A2 ( n13 ) , .A1 ( n32 ) , .Y ( n31 ) ) ;
AO22X1_RVT U38 (.A2 ( din[0] ) , .A3 ( \mem[2][0] ) , .Y ( n46 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U39 (.A2 ( din[1] ) , .A3 ( \mem[2][1] ) , .Y ( n47 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U40 (.A2 ( din[2] ) , .A3 ( \mem[2][2] ) , .Y ( n48 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U41 (.A2 ( din[3] ) , .A3 ( \mem[2][3] ) , .Y ( n49 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U42 (.A2 ( din[4] ) , .A3 ( \mem[2][4] ) , .Y ( n50 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U43 (.A2 ( din[5] ) , .A3 ( \mem[2][5] ) , .Y ( n51 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U44 (.A2 ( din[6] ) , .A3 ( \mem[2][6] ) , .Y ( n52 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U45 (.A2 ( din[7] ) , .A3 ( \mem[2][7] ) , .Y ( n53 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U46 (.A2 ( din[0] ) , .A3 ( \mem[0][0] ) , .Y ( n62 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U47 (.A2 ( din[1] ) , .A3 ( \mem[0][1] ) , .Y ( n63 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U48 (.A2 ( din[2] ) , .A3 ( \mem[0][2] ) , .Y ( n64 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U49 (.A2 ( din[3] ) , .A3 ( \mem[0][3] ) , .Y ( n65 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U50 (.A2 ( din[4] ) , .A3 ( \mem[0][4] ) , .Y ( n66 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U51 (.A2 ( din[5] ) , .A3 ( \mem[0][5] ) , .Y ( n67 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U52 (.A2 ( din[6] ) , .A3 ( \mem[0][6] ) , .Y ( n68 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U53 (.A2 ( din[7] ) , .A3 ( \mem[0][7] ) , .Y ( n69 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AND2X1_RVT U54 (.Y ( n27 ) , .A1 ( we ) , .A2 ( n12 ) ) ;
OR2X1_RVT U55 (.Y ( n32 ) , .A2 ( re ) , .A1 ( clr ) ) ;
AND3X1_RVT U58 (.A1 ( n36 ) , .Y ( empty ) , .A2 ( n15 ) , .A3 ( n18 ) ) ;
AND3X1_RVT U59 (.A1 ( n36 ) , .Y ( full ) , .A2 ( gb ) , .A3 ( n18 ) ) ;
AO22X1_RVT U60 (.A2 ( wp[0] ) , .A3 ( n27 ) , .Y ( n73 ) , .A4 ( n78 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U61 (.A2 ( wp[1] ) , .A3 ( n34 ) , .Y ( n72 ) , .A4 ( n24 ) 
    , .A1 ( n79 ) ) ;
AND2X1_RVT U62 (.Y ( n34 ) , .A1 ( n35 ) , .A2 ( n78 ) ) ;
XNOR2X1_RVT U63 (.A2 ( wp[1] ) , .A1 ( n12 ) , .Y ( n24 ) ) ;
XNOR2X1_RVT U64 (.A2 ( n12 ) , .A1 ( N8 ) , .Y ( n23 ) ) ;
XNOR2X1_RVT U65 (.A2 ( wp[1] ) , .A1 ( N9 ) , .Y ( n36 ) ) ;
OR2X1_RVT U66 (.Y ( n35 ) , .A2 ( clr ) , .A1 ( we ) ) ;
INVX1_RVT U67 (.A ( clr ) , .Y ( n78 ) ) ;
AND2X1_RVT U68 (.Y ( n17 ) , .A1 ( n14 ) , .A2 ( n13 ) ) ;
AND2X1_RVT U69 (.Y ( n16 ) , .A1 ( N8 ) , .A2 ( n13 ) ) ;
AND2X1_RVT U70 (.Y ( n9 ) , .A1 ( N9 ) , .A2 ( N8 ) ) ;
AND2X1_RVT U71 (.Y ( n8 ) , .A1 ( N9 ) , .A2 ( n14 ) ) ;
AO22X1_RVT U72 (.A2 ( n9 ) , .A3 ( \mem[2][0] ) , .Y ( n1 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][0] ) ) ;
AO221X1_RVT U73 (.A5 ( n1 ) , .A1 ( \mem[0][0] ) , .A4 ( n16 ) , .Y ( dout[0] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][0] ) ) ;
AO22X1_RVT U74 (.A2 ( n9 ) , .A3 ( \mem[2][1] ) , .Y ( n2 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][1] ) ) ;
AO221X1_RVT U75 (.A5 ( n2 ) , .A1 ( \mem[0][1] ) , .A4 ( n16 ) , .Y ( dout[1] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][1] ) ) ;
AO22X1_RVT U76 (.A2 ( n9 ) , .A3 ( \mem[2][2] ) , .Y ( n3 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][2] ) ) ;
AO221X1_RVT U77 (.A5 ( n3 ) , .A1 ( \mem[0][2] ) , .A4 ( n16 ) , .Y ( dout[2] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][2] ) ) ;
AO22X1_RVT U78 (.A2 ( n9 ) , .A3 ( \mem[2][3] ) , .Y ( n4 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][3] ) ) ;
AO221X1_RVT U79 (.A5 ( n4 ) , .A1 ( \mem[0][3] ) , .A4 ( n16 ) , .Y ( dout[3] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][3] ) ) ;
AO22X1_RVT U80 (.A2 ( n9 ) , .A3 ( \mem[2][4] ) , .Y ( n5 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][4] ) ) ;
AO221X1_RVT U81 (.A5 ( n5 ) , .A1 ( \mem[0][4] ) , .A4 ( n16 ) , .Y ( dout[4] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][4] ) ) ;
AO22X1_RVT U82 (.A2 ( n9 ) , .A3 ( \mem[2][5] ) , .Y ( n6 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][5] ) ) ;
AO221X1_RVT U83 (.A5 ( n6 ) , .A1 ( \mem[0][5] ) , .A4 ( n16 ) , .Y ( dout[5] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][5] ) ) ;
AO22X1_RVT U84 (.A2 ( n9 ) , .A3 ( \mem[2][6] ) , .Y ( n7 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][6] ) ) ;
AO221X1_RVT U85 (.A5 ( n7 ) , .A1 ( \mem[0][6] ) , .A4 ( n16 ) , .Y ( dout[6] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][6] ) ) ;
AO22X1_RVT U86 (.A2 ( n9 ) , .A3 ( \mem[2][7] ) , .Y ( n11 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][7] ) ) ;
AO221X1_RVT U87 (.A5 ( n11 ) , .A1 ( \mem[0][7] ) , .A4 ( n16 ) , .Y ( dout[7] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][7] ) ) ;
DFFX1_RVT gb_reg (.QN ( n15 ) , .D ( n37 ) , .CLK ( clk ) , .Q ( gb ) ) ;
DFFX1_RVT \mem_reg[3][7] (.D ( n45 ) , .CLK ( clk ) , .Q ( \mem[3][7] ) ) ;
DFFX1_RVT \mem_reg[3][6] (.D ( n44 ) , .CLK ( clk ) , .Q ( \mem[3][6] ) ) ;
DFFX1_RVT \mem_reg[3][5] (.D ( n43 ) , .CLK ( clk ) , .Q ( \mem[3][5] ) ) ;
DFFX1_RVT \mem_reg[3][4] (.D ( n42 ) , .CLK ( clk ) , .Q ( \mem[3][4] ) ) ;
DFFX1_RVT \mem_reg[3][3] (.D ( n41 ) , .CLK ( clk ) , .Q ( \mem[3][3] ) ) ;
DFFX1_RVT \mem_reg[3][2] (.D ( n40 ) , .CLK ( clk ) , .Q ( \mem[3][2] ) ) ;
DFFX1_RVT \mem_reg[3][1] (.D ( n39 ) , .CLK ( clk ) , .Q ( \mem[3][1] ) ) ;
DFFX1_RVT \mem_reg[3][0] (.D ( n38 ) , .CLK ( clk ) , .Q ( \mem[3][0] ) ) ;
DFFX1_RVT \mem_reg[0][7] (.D ( n69 ) , .CLK ( clk ) , .Q ( \mem[0][7] ) ) ;
DFFX1_RVT \mem_reg[0][6] (.D ( n68 ) , .CLK ( clk ) , .Q ( \mem[0][6] ) ) ;
DFFX1_RVT \mem_reg[0][5] (.D ( n67 ) , .CLK ( clk ) , .Q ( \mem[0][5] ) ) ;
DFFX1_RVT \mem_reg[0][4] (.D ( n66 ) , .CLK ( clk ) , .Q ( \mem[0][4] ) ) ;
DFFX1_RVT \mem_reg[0][3] (.D ( n65 ) , .CLK ( clk ) , .Q ( \mem[0][3] ) ) ;
DFFX1_RVT \mem_reg[0][2] (.D ( n64 ) , .CLK ( clk ) , .Q ( \mem[0][2] ) ) ;
DFFX1_RVT \mem_reg[0][1] (.D ( n63 ) , .CLK ( clk ) , .Q ( \mem[0][1] ) ) ;
DFFX1_RVT \mem_reg[0][0] (.D ( n62 ) , .CLK ( clk ) , .Q ( \mem[0][0] ) ) ;
DFFX1_RVT \mem_reg[1][7] (.D ( n61 ) , .CLK ( clk ) , .Q ( \mem[1][7] ) ) ;
DFFX1_RVT \mem_reg[1][6] (.D ( n60 ) , .CLK ( clk ) , .Q ( \mem[1][6] ) ) ;
DFFX1_RVT \mem_reg[1][5] (.D ( n59 ) , .CLK ( clk ) , .Q ( \mem[1][5] ) ) ;
DFFX1_RVT \mem_reg[1][4] (.D ( n58 ) , .CLK ( clk ) , .Q ( \mem[1][4] ) ) ;
DFFX1_RVT \mem_reg[1][3] (.D ( n57 ) , .CLK ( clk ) , .Q ( \mem[1][3] ) ) ;
DFFX1_RVT \mem_reg[1][2] (.D ( n56 ) , .CLK ( clk ) , .Q ( \mem[1][2] ) ) ;
DFFX1_RVT \mem_reg[1][1] (.D ( n55 ) , .CLK ( clk ) , .Q ( \mem[1][1] ) ) ;
DFFX1_RVT \mem_reg[1][0] (.D ( n54 ) , .CLK ( clk ) , .Q ( \mem[1][0] ) ) ;
DFFX1_RVT \mem_reg[2][7] (.D ( n53 ) , .CLK ( clk ) , .Q ( \mem[2][7] ) ) ;
DFFX1_RVT \mem_reg[2][6] (.D ( n52 ) , .CLK ( clk ) , .Q ( \mem[2][6] ) ) ;
DFFX1_RVT \mem_reg[2][5] (.D ( n51 ) , .CLK ( clk ) , .Q ( \mem[2][5] ) ) ;
DFFX1_RVT \mem_reg[2][4] (.D ( n50 ) , .CLK ( clk ) , .Q ( \mem[2][4] ) ) ;
DFFX1_RVT \mem_reg[2][3] (.D ( n49 ) , .CLK ( clk ) , .Q ( \mem[2][3] ) ) ;
DFFX1_RVT \mem_reg[2][2] (.D ( n48 ) , .CLK ( clk ) , .Q ( \mem[2][2] ) ) ;
DFFX1_RVT \mem_reg[2][1] (.D ( n47 ) , .CLK ( clk ) , .Q ( \mem[2][1] ) ) ;
DFFX1_RVT \mem_reg[2][0] (.D ( n46 ) , .CLK ( clk ) , .Q ( \mem[2][0] ) ) ;
DFFARX1_RVT \rp_reg[0] (.QN ( n14 ) , .RSTB ( rst ) , .D ( n71 ) , .CLK ( clk ) 
    , .Q ( N8 ) ) ;
DFFARX1_RVT \rp_reg[1] (.QN ( n13 ) , .RSTB ( rst ) , .D ( n70 ) , .CLK ( clk ) 
    , .Q ( N9 ) ) ;
DFFARX1_RVT \wp_reg[1] (.QN ( n10 ) , .RSTB ( rst ) , .D ( n72 ) , .CLK ( clk ) 
    , .Q ( wp[1] ) ) ;
DFFARX1_RVT \wp_reg[0] (.QN ( n12 ) , .RSTB ( rst ) , .D ( n73 ) , .CLK ( clk ) 
    , .Q ( wp[0] ) ) ;
AND3X1_RVT U3 (.A1 ( rst ) , .Y ( n22 ) , .A2 ( n78 ) , .A3 ( n23 ) ) ;
INVX1_RVT U8 (.A ( n32 ) , .Y ( n80 ) ) ;
INVX1_RVT U9 (.A ( n23 ) , .Y ( n18 ) ) ;
INVX1_RVT U10 (.A ( n35 ) , .Y ( n79 ) ) ;
NAND2X0_RVT U11 (.A2 ( n20 ) , .A1 ( n19 ) , .Y ( n37 ) ) ;
NAND3X0_RVT U12 (.Y ( n19 ) , .A1 ( n80 ) , .A2 ( rst ) , .A3 ( gb ) ) ;
NAND3X0_RVT U13 (.Y ( n20 ) , .A1 ( n21 ) , .A2 ( we ) , .A3 ( n22 ) ) ;
XNOR2X1_RVT U14 (.A2 ( n24 ) , .A1 ( N9 ) , .Y ( n21 ) ) ;
AO22X1_RVT U15 (.A2 ( n75 ) , .A3 ( \mem[3][0] ) , .Y ( n38 ) , .A4 ( n25 ) 
    , .A1 ( din[0] ) ) ;
AO22X1_RVT U16 (.A2 ( n75 ) , .A3 ( \mem[3][1] ) , .Y ( n39 ) , .A4 ( n25 ) 
    , .A1 ( din[1] ) ) ;
AO22X1_RVT U17 (.A2 ( n75 ) , .A3 ( \mem[3][2] ) , .Y ( n40 ) , .A4 ( n25 ) 
    , .A1 ( din[2] ) ) ;
AO22X1_RVT U18 (.A2 ( n75 ) , .A3 ( \mem[3][3] ) , .Y ( n41 ) , .A4 ( n25 ) 
    , .A1 ( din[3] ) ) ;
AO22X1_RVT U19 (.A2 ( n75 ) , .A3 ( \mem[3][4] ) , .Y ( n42 ) , .A4 ( n25 ) 
    , .A1 ( din[4] ) ) ;
AO22X1_RVT U20 (.A2 ( n75 ) , .A3 ( \mem[3][5] ) , .Y ( n43 ) , .A4 ( n25 ) 
    , .A1 ( din[5] ) ) ;
AO22X1_RVT U21 (.A2 ( n75 ) , .A3 ( \mem[3][6] ) , .Y ( n44 ) , .A4 ( n25 ) 
    , .A1 ( din[6] ) ) ;
AO22X1_RVT U22 (.A2 ( n75 ) , .A3 ( \mem[3][7] ) , .Y ( n45 ) , .A4 ( n25 ) 
    , .A1 ( din[7] ) ) ;
AO22X1_RVT U23 (.A2 ( din[0] ) , .A3 ( \mem[1][0] ) , .Y ( n54 ) , .A4 ( n28 ) 
    , .A1 ( n76 ) ) ;
endmodule




module sasc_top (din_i , dout_o , cts_i , rxd_i , rst , clk , empty_o , 
    full_o , rts_o , txd_o , we_i , re_i , sio_ce_x4 , sio_ce );
input  [7:0] din_i ;
output [7:0] dout_o ;
input  cts_i ;
input  rxd_i ;
input  rst ;
input  clk ;
output empty_o ;
output full_o ;
output rts_o ;
output txd_o ;
input  we_i ;
input  re_i ;
input  sio_ce_x4 ;
input  sio_ce ;

wire [9:2] rxr ;
wire [7:0] txd_p ;

wire [3:0] rx_bit_cnt ;
wire [1:0] dpll_state ;
wire [3:0] tx_bit_cnt ;


sasc_fifo4_0 rx_fifo (.clk ( clk ) , .rst ( rst ) , .clr ( 1'b0 ), 
    .we ( rx_we ) , .re ( re_i ) , .full ( rxf_full ) , .empty ( empty_o ) , 
    .dout ( dout_o ) , .din ( rxr ) ) ;


sasc_fifo4_1 tx_fifo (.clk ( clk ) , .rst ( rst ) , .clr ( 1'b0 ), 
    .we ( we_i ) , .re ( n5 ) , .full ( full_o ) , .empty ( txf_empty ) , 
    .dout ( txd_p ) , .din ( din_i ) ) ;

INVX1_RVT U4 (.A ( n47 ) , .Y ( n8 ) ) ;
INVX1_RVT U3 (.A ( n33 ) , .Y ( n5 ) ) ;
INVX1_RVT U2 (.A ( n48 ) , .Y ( n4 ) ) ;
INVX1_RVT U1 (.A ( rst ) , .Y ( n3 ) ) ;
OAI21X1_RVT U136 (.Y ( n18 ) , .A3 ( n81 ) , .A2 ( shift_en_r ) 
    , .A1 ( shift_en ) ) ;
AND2X1_RVT U137 (.Y ( n34 ) , .A1 ( n31 ) , .A2 ( n33 ) ) ;
NAND2X0_RVT U138 (.A2 ( n33 ) , .A1 ( n31 ) , .Y ( n32 ) ) ;
INVX1_RVT U139 (.A ( sio_ce ) , .Y ( n118 ) ) ;
XNOR2X1_RVT U140 (.A2 ( rxd_s ) , .A1 ( n63 ) , .Y ( n79 ) ) ;
NAND4X0_RVT U141 (.A2 ( rx_bit_cnt[1] ) , .A4 ( n107 ) , .A3 ( n108 ) 
    , .Y ( N128 ) , .A1 ( rx_bit_cnt[3] ) ) ;
AND4X1_RVT U142 (.Y ( n106 ) , .A1 ( rx_bit_cnt[3] ) , .A3 ( n109 ) 
    , .A4 ( n107 ) , .A2 ( rx_bit_cnt[0] ) ) ;
AO22X1_RVT U143 (.A2 ( n49 ) , .A3 ( n50 ) , .Y ( n77 ) , .A4 ( sio_ce_x4 ) 
    , .A1 ( dpll_state[1] ) ) ;
NOR2X0_RVT U144 (.Y ( n50 ) , .A2 ( n65 ) , .A1 ( dpll_state[1] ) ) ;
AO21X1_RVT U145 (.A1 ( n65 ) , .Y ( n49 ) , .A2 ( n83 ) , .A3 ( n121 ) ) ;
INVX1_RVT U146 (.A ( sio_ce_x4 ) , .Y ( n121 ) ) ;
NOR3X0_RVT U147 (.Y ( N19 ) , .A1 ( cts_i ) , .A3 ( shift_en ) 
    , .A2 ( txf_empty_r ) ) ;
NOR2X0_RVT U148 (.Y ( n85 ) , .A2 ( sio_ce_x4 ) , .A1 ( n83 ) ) ;
NAND4X0_RVT U149 (.A2 ( tx_bit_cnt[0] ) , .A4 ( n111 ) , .A3 ( n123 ) 
    , .Y ( N123 ) , .A1 ( tx_bit_cnt[3] ) ) ;
OAI22X1_RVT U150 (.Y ( n78 ) , .A4 ( n54 ) , .A3 ( dpll_state[0] ) , .A2 ( n52 ) 
    , .A1 ( n65 ) ) ;
OA21X1_RVT U151 (.Y ( n52 ) , .A3 ( sio_ce_x4 ) , .A2 ( dpll_state[1] ) 
    , .A1 ( n83 ) ) ;
NAND2X0_RVT U152 (.A2 ( sio_ce_x4 ) , .A1 ( n83 ) , .Y ( n54 ) ) ;
AO22X1_RVT U155 (.A2 ( n29 ) , .A3 ( n30 ) , .Y ( n94 ) , .A4 ( tx_bit_cnt[0] ) 
    , .A1 ( tx_bit_cnt[1] ) ) ;
OAI22X1_RVT U156 (.Y ( n29 ) , .A4 ( n32 ) , .A3 ( n3 ) , .A2 ( tx_bit_cnt[0] ) 
    , .A1 ( n31 ) ) ;
AO221X1_RVT U157 (.A5 ( n3 ) , .A1 ( txf_empty_r ) , .A4 ( sio_ce ) 
    , .Y ( n105 ) , .A2 ( n118 ) , .A3 ( txf_empty ) ) ;
AO221X1_RVT U158 (.A5 ( n3 ) , .A1 ( sio_ce ) , .A4 ( n118 ) , .Y ( n90 ) 
    , .A2 ( n18 ) , .A3 ( txd_o ) ) ;
INVX0_RVT U159 (.A ( n31 ) , .Y ( n117 ) ) ;
AO22X1_RVT U160 (.A2 ( tx_bit_cnt[2] ) , .A3 ( n26 ) , .Y ( n93 ) , .A4 ( n111 ) 
    , .A1 ( n25 ) ) ;
AND2X1_RVT U161 (.Y ( n21 ) , .A1 ( n26 ) , .A2 ( n113 ) ) ;
AO221X1_RVT U162 (.A5 ( n3 ) , .A1 ( n21 ) , .A4 ( tx_bit_cnt[3] ) , .Y ( n92 ) 
    , .A2 ( tx_bit_cnt[2] ) , .A3 ( n22 ) ) ;
NAND3X0_RVT U163 (.Y ( n47 ) , .A1 ( sio_ce ) , .A2 ( n33 ) , .A3 ( shift_en ) ) ;
AO221X1_RVT U164 (.A5 ( n3 ) , .A1 ( n34 ) , .A4 ( n122 ) , .Y ( n95 ) 
    , .A2 ( tx_bit_cnt[0] ) , .A3 ( n117 ) ) ;
AND2X1_RVT U165 (.Y ( n30 ) , .A1 ( n117 ) , .A2 ( n123 ) ) ;
AO21X1_RVT U166 (.A1 ( n117 ) , .Y ( n25 ) , .A2 ( n123 ) , .A3 ( n29 ) ) ;
AO21X1_RVT U167 (.A1 ( n117 ) , .Y ( n22 ) , .A2 ( n111 ) , .A3 ( n25 ) ) ;
NOR3X0_RVT U168 (.Y ( n26 ) , .A1 ( n122 ) , .A3 ( n123 ) , .A2 ( n31 ) ) ;
INVX0_RVT U169 (.A ( n15 ) , .Y ( n115 ) ) ;
NAND2X0_RVT U170 (.A2 ( n4 ) , .A1 ( rst ) , .Y ( n15 ) ) ;
DFFX1_RVT \tx_bit_cnt_reg[1] (.QN ( n123 ) , .D ( n94 ) , .CLK ( clk ) 
    , .Q ( tx_bit_cnt[1] ) ) ;
DFFX1_RVT \tx_bit_cnt_reg[0] (.QN ( n122 ) , .D ( n95 ) , .CLK ( clk ) 
    , .Q ( tx_bit_cnt[0] ) ) ;
DFFX1_RVT \tx_bit_cnt_reg[3] (.QN ( n113 ) , .D ( n92 ) , .CLK ( clk ) 
    , .Q ( tx_bit_cnt[3] ) ) ;
DFFX1_RVT txd_o_reg (.D ( n90 ) , .CLK ( clk ) , .Q ( txd_o ) ) ;
DFFX1_RVT txf_empty_r_reg (.D ( n105 ) , .CLK ( clk ) , .Q ( txf_empty_r ) ) ;
DFFX1_RVT shift_en_r_reg (.D ( n91 ) , .CLK ( clk ) , .Q ( shift_en_r ) ) ;
DFFX1_RVT \tx_bit_cnt_reg[2] (.QN ( n111 ) , .D ( n93 ) , .CLK ( clk ) 
    , .Q ( tx_bit_cnt[2] ) ) ;
DFFX1_RVT \rx_bit_cnt_reg[3] (.QN ( n112 ) , .D ( n86 ) , .CLK ( clk ) 
    , .Q ( rx_bit_cnt[3] ) ) ;
DFFX1_RVT \rxr_reg[2] (.D ( n67 ) , .CLK ( clk ) , .Q ( rxr[2] ) ) ;
DFFARX1_RVT \dpll_state_reg[1] (.QN ( n66 ) , .RSTB ( rst ) , .D ( n77 ) 
    , .CLK ( clk ) , .Q ( dpll_state[1] ) ) ;
DFFX1_RVT \hold_reg_reg[8] (.D ( n96 ) , .CLK ( clk ) , .Q ( n124 ) ) ;
DFFX1_RVT \hold_reg_reg[7] (.D ( n97 ) , .CLK ( clk ) , .Q ( n125 ) ) ;
DFFX1_RVT \hold_reg_reg[6] (.D ( n98 ) , .CLK ( clk ) , .Q ( n126 ) ) ;
DFFX1_RVT \hold_reg_reg[5] (.D ( n99 ) , .CLK ( clk ) , .Q ( n127 ) ) ;
DFFX1_RVT \hold_reg_reg[4] (.D ( n100 ) , .CLK ( clk ) , .Q ( n128 ) ) ;
DFFX1_RVT \hold_reg_reg[3] (.D ( n101 ) , .CLK ( clk ) , .Q ( n129 ) ) ;
DFFX1_RVT \hold_reg_reg[2] (.D ( n102 ) , .CLK ( clk ) , .Q ( n130 ) ) ;
DFFX1_RVT \hold_reg_reg[1] (.D ( n103 ) , .CLK ( clk ) , .Q ( n131 ) ) ;
DFFX1_RVT \hold_reg_reg[0] (.QN ( n81 ) , .D ( n104 ) , .CLK ( clk ) 
    , .Q ( n132 ) ) ;
DFFSSRX1_RVT change_reg (.QN ( n83 ) , .SETB ( n79 ) , .CLK ( clk ) , .D ( n85 ) 
    , .RSTB ( rst ) ) ;
DFFX1_RVT \rx_bit_cnt_reg[2] (.QN ( n107 ) , .D ( n87 ) , .CLK ( clk ) 
    , .Q ( rx_bit_cnt[2] ) ) ;
DFFX1_RVT \rx_bit_cnt_reg[1] (.QN ( n109 ) , .D ( n89 ) , .CLK ( clk ) 
    , .Q ( rx_bit_cnt[1] ) ) ;
DFFX1_RVT rxd_r_reg (.QN ( n110 ) , .D ( rxd_s ) , .CLK ( clk ) , .Q ( n63 ) ) ;
DFFX1_RVT \rx_bit_cnt_reg[0] (.QN ( n108 ) , .D ( n88 ) , .CLK ( clk ) 
    , .Q ( rx_bit_cnt[0] ) ) ;
DFFX1_RVT rxd_s_reg (.D ( rxd_i ) , .CLK ( clk ) , .Q ( rxd_s ) ) ;
DFFX1_RVT \rxr_reg[9] (.D ( n74 ) , .CLK ( clk ) , .Q ( rxr[9] ) ) ;
DFFX1_RVT \rxr_reg[8] (.D ( n73 ) , .CLK ( clk ) , .Q ( rxr[8] ) ) ;
DFFX1_RVT \rxr_reg[7] (.D ( n72 ) , .CLK ( clk ) , .Q ( rxr[7] ) ) ;
DFFX1_RVT \rxr_reg[6] (.D ( n71 ) , .CLK ( clk ) , .Q ( rxr[6] ) ) ;
DFFX1_RVT \rxr_reg[5] (.D ( n70 ) , .CLK ( clk ) , .Q ( rxr[5] ) ) ;
DFFX1_RVT \rxr_reg[4] (.D ( n69 ) , .CLK ( clk ) , .Q ( rxr[4] ) ) ;
DFFX1_RVT \rxr_reg[3] (.D ( n68 ) , .CLK ( clk ) , .Q ( rxr[3] ) ) ;
DFFX1_RVT load_reg (.D ( N19 ) , .CLK ( clk ) , .Q ( load ) ) ;
DFFX1_RVT shift_en_reg (.D ( N123 ) , .CLK ( clk ) , .Q ( shift_en ) ) ;
DFFX1_RVT rx_valid_r_reg (.D ( rx_valid ) , .CLK ( clk ) , .Q ( rx_valid_r ) ) ;
DFFX1_RVT rx_go_reg (.D ( N128 ) , .CLK ( clk ) , .Q ( rx_go ) ) ;
DFFSSRX1_RVT rx_sio_ce_reg (.Q ( n64 ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( rx_sio_ce_r1 ) , .RSTB ( n84 ) ) ;
DFFX1_RVT rx_valid_reg (.QN ( n82 ) , .D ( n106 ) , .CLK ( clk ) 
    , .Q ( rx_valid ) ) ;
DFFX1_RVT rts_o_reg (.D ( rxf_full ) , .CLK ( clk ) , .Q ( rts_o ) ) ;
DFFSSRX1_RVT rx_sio_ce_r1_reg (.Q ( rx_sio_ce_r1 ) , .SETB ( 1'b1 )
    , .CLK ( clk ) , .D ( dpll_state[0] ) , .RSTB ( n66 ) ) ;
DFFX1_RVT rx_sio_ce_r2_reg (.QN ( n84 ) , .D ( rx_sio_ce_r1 ) , .CLK ( clk ) ) ;
DFFASX1_RVT \dpll_state_reg[0] (.QN ( n65 ) , .D ( n78 ) , .SETB ( rst ) 
    , .CLK ( clk ) , .Q ( dpll_state[0] ) ) ;
AO21X1_RVT U99 (.A1 ( n115 ) , .Y ( n10 ) , .A2 ( n108 ) , .A3 ( n12 ) ) ;
AO21X1_RVT U100 (.A1 ( n115 ) , .Y ( n6 ) , .A2 ( n109 ) , .A3 ( n10 ) ) ;
AND2X1_RVT U102 (.Y ( n37 ) , .A1 ( n33 ) , .A2 ( n47 ) ) ;
OR2X1_RVT U103 (.Y ( n31 ) , .A2 ( n3 ) , .A1 ( n47 ) ) ;
AND2X1_RVT U104 (.Y ( n91 ) , .A1 ( rst ) , .A2 ( n20 ) ) ;
AO22X1_RVT U105 (.A2 ( n118 ) , .A3 ( shift_en ) , .Y ( n20 ) , .A4 ( sio_ce ) 
    , .A1 ( shift_en_r ) ) ;
NOR3X0_RVT U106 (.Y ( rx_we ) , .A1 ( n82 ) , .A3 ( rx_valid_r ) 
    , .A2 ( rxf_full ) ) ;
AND3X1_RVT U107 (.A1 ( n14 ) , .Y ( n12 ) , .A2 ( n15 ) , .A3 ( rst ) ) ;
OR3X2_RVT U108 (.A1 ( rx_go ) , .A3 ( n110 ) , .Y ( n14 ) , .A2 ( rxd_s ) ) ;
AND3X1_RVT U109 (.A1 ( rx_bit_cnt[0] ) , .Y ( n7 ) , .A2 ( n115 ) 
    , .A3 ( rx_bit_cnt[1] ) ) ;
AO221X1_RVT U110 (.A5 ( n3 ) , .A1 ( n13 ) , .A4 ( n10 ) , .Y ( n89 ) 
    , .A2 ( rx_bit_cnt[0] ) , .A3 ( rx_bit_cnt[1] ) ) ;
AND2X1_RVT U111 (.Y ( n13 ) , .A1 ( n115 ) , .A2 ( n109 ) ) ;
AO221X1_RVT U112 (.A5 ( n3 ) , .A1 ( n1 ) , .A4 ( n2 ) , .Y ( n86 ) 
    , .A2 ( rx_bit_cnt[2] ) , .A3 ( rx_bit_cnt[3] ) ) ;
AND2X1_RVT U113 (.Y ( n1 ) , .A1 ( n7 ) , .A2 ( n112 ) ) ;
AO21X1_RVT U114 (.A1 ( n115 ) , .Y ( n2 ) , .A2 ( n107 ) , .A3 ( n6 ) ) ;
AO22X1_RVT U115 (.A2 ( n6 ) , .A3 ( n7 ) , .Y ( n87 ) , .A4 ( n107 ) 
    , .A1 ( rx_bit_cnt[2] ) ) ;
AO22X1_RVT U116 (.A2 ( n48 ) , .A3 ( rxr[3] ) , .Y ( n67 ) , .A4 ( n4 ) 
    , .A1 ( rxr[2] ) ) ;
AO22X1_RVT U117 (.A2 ( n48 ) , .A3 ( rxr[4] ) , .Y ( n68 ) , .A4 ( n4 ) 
    , .A1 ( rxr[3] ) ) ;
AO22X1_RVT U118 (.A2 ( n48 ) , .A3 ( rxr[5] ) , .Y ( n69 ) , .A4 ( n4 ) 
    , .A1 ( rxr[4] ) ) ;
AO22X1_RVT U119 (.A2 ( n48 ) , .A3 ( rxr[6] ) , .Y ( n70 ) , .A4 ( n4 ) 
    , .A1 ( rxr[5] ) ) ;
AO22X1_RVT U120 (.A2 ( n48 ) , .A3 ( rxr[7] ) , .Y ( n71 ) , .A4 ( n4 ) 
    , .A1 ( rxr[6] ) ) ;
AO22X1_RVT U121 (.A2 ( n48 ) , .A3 ( rxr[8] ) , .Y ( n72 ) , .A4 ( n4 ) 
    , .A1 ( rxr[7] ) ) ;
AO22X1_RVT U122 (.A2 ( n48 ) , .A3 ( rxr[9] ) , .Y ( n73 ) , .A4 ( n4 ) 
    , .A1 ( rxr[8] ) ) ;
AO22X1_RVT U123 (.A2 ( n48 ) , .A3 ( rxd_s ) , .Y ( n74 ) , .A4 ( n4 ) 
    , .A1 ( rxr[9] ) ) ;
AO22X1_RVT U124 (.A2 ( n108 ) , .A3 ( n12 ) , .Y ( n88 ) , .A4 ( rx_bit_cnt[0] ) 
    , .A1 ( n115 ) ) ;
NAND2X0_RVT U125 (.A2 ( n64 ) , .A1 ( rx_go ) , .Y ( n48 ) ) ;
NAND2X0_RVT U126 (.A2 ( load ) , .A1 ( sio_ce ) , .Y ( n33 ) ) ;
AO221X1_RVT U127 (.A5 ( n8 ) , .A1 ( n37 ) , .A4 ( n5 ) , .Y ( n96 ) 
    , .A2 ( n124 ) , .A3 ( txd_p[7] ) ) ;
AO22X1_RVT U128 (.A2 ( n131 ) , .A3 ( n37 ) , .Y ( n104 ) , .A4 ( n132 ) 
    , .A1 ( n8 ) ) ;
AO222X1_RVT U129 (.A1 ( n8 ) , .A5 ( txd_p[0] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n130 ) , .Y ( n103 ) , .A4 ( n131 ) ) ;
AO222X1_RVT U130 (.A1 ( n8 ) , .A5 ( txd_p[1] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n129 ) , .Y ( n102 ) , .A4 ( n130 ) ) ;
AO222X1_RVT U131 (.A1 ( n8 ) , .A5 ( txd_p[2] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n128 ) , .Y ( n101 ) , .A4 ( n129 ) ) ;
AO222X1_RVT U132 (.A1 ( n8 ) , .A5 ( txd_p[3] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n127 ) , .Y ( n100 ) , .A4 ( n128 ) ) ;
AO222X1_RVT U133 (.A1 ( n8 ) , .A5 ( txd_p[4] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n126 ) , .Y ( n99 ) , .A4 ( n127 ) ) ;
AO222X1_RVT U134 (.A1 ( n8 ) , .A5 ( txd_p[5] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n125 ) , .Y ( n98 ) , .A4 ( n126 ) ) ;
AO222X1_RVT U135 (.A1 ( n8 ) , .A5 ( txd_p[6] ) , .A6 ( n5 ) , .A3 ( n37 ) 
    , .A2 ( n124 ) , .Y ( n97 ) , .A4 ( n125 ) ) ;
endmodule


