//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/06/2025 at 09:32:35
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :simple_spi_top.mw
// Cell Name    :simple_spi_top
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./outputs/simple_spi_top_extracted.v
//


module simple_spi_top_DW01_dec_0 (SUM , A );
output [11:0] SUM ;
input  [11:0] A ;



INVX1_RVT U7 (.A ( n17 ) , .Y ( n8 ) ) ;
INVX1_RVT U6 (.A ( n16 ) , .Y ( n7 ) ) ;
INVX1_RVT U5 (.A ( n14 ) , .Y ( n5 ) ) ;
INVX1_RVT U4 (.A ( n13 ) , .Y ( n4 ) ) ;
INVX1_RVT U3 (.A ( n12 ) , .Y ( n3 ) ) ;
INVX1_RVT U2 (.A ( n11 ) , .Y ( n2 ) ) ;
INVX1_RVT U1 (.A ( n20 ) , .Y ( n1 ) ) ;
AO21X1_RVT U15 (.A1 ( A[5] ) , .Y ( SUM[5] ) , .A2 ( n15 ) , .A3 ( n5 ) ) ;
AO21X1_RVT U14 (.A1 ( A[6] ) , .Y ( SUM[6] ) , .A2 ( n14 ) , .A3 ( n4 ) ) ;
AO21X1_RVT U13 (.A1 ( A[7] ) , .Y ( SUM[7] ) , .A2 ( n13 ) , .A3 ( n3 ) ) ;
AO21X1_RVT U12 (.A1 ( A[8] ) , .Y ( SUM[8] ) , .A2 ( n12 ) , .A3 ( n2 ) ) ;
AO21X1_RVT U11 (.A1 ( A[9] ) , .Y ( SUM[9] ) , .A2 ( n11 ) , .A3 ( n1 ) ) ;
INVX1_RVT U10 (.A ( A[0] ) , .Y ( SUM[0] ) ) ;
INVX1_RVT U9 (.A ( n15 ) , .Y ( n6 ) ) ;
INVX1_RVT U8 (.A ( n18 ) , .Y ( n9 ) ) ;
OR2X1_RVT U23 (.Y ( n20 ) , .A2 ( A[9] ) , .A1 ( n11 ) ) ;
XOR2X1_RVT U22 (.Y ( SUM[10] ) , .A2 ( n1 ) , .A1 ( A[10] ) ) ;
OR2X1_RVT U21 (.Y ( n19 ) , .A2 ( A[10] ) , .A1 ( n20 ) ) ;
XNOR2X1_RVT U20 (.A2 ( A[11] ) , .A1 ( n19 ) , .Y ( SUM[11] ) ) ;
AO21X1_RVT U19 (.A1 ( A[1] ) , .Y ( SUM[1] ) , .A2 ( A[0] ) , .A3 ( n9 ) ) ;
AO21X1_RVT U18 (.A1 ( A[2] ) , .Y ( SUM[2] ) , .A2 ( n18 ) , .A3 ( n8 ) ) ;
AO21X1_RVT U17 (.A1 ( A[3] ) , .Y ( SUM[3] ) , .A2 ( n17 ) , .A3 ( n7 ) ) ;
AO21X1_RVT U16 (.A1 ( A[4] ) , .Y ( SUM[4] ) , .A2 ( n16 ) , .A3 ( n6 ) ) ;
OR2X1_RVT U31 (.Y ( n18 ) , .A2 ( A[0] ) , .A1 ( A[1] ) ) ;
OR2X1_RVT U30 (.Y ( n17 ) , .A2 ( A[2] ) , .A1 ( n18 ) ) ;
OR2X1_RVT U29 (.Y ( n16 ) , .A2 ( A[3] ) , .A1 ( n17 ) ) ;
OR2X1_RVT U28 (.Y ( n15 ) , .A2 ( A[4] ) , .A1 ( n16 ) ) ;
OR2X1_RVT U27 (.Y ( n14 ) , .A2 ( A[5] ) , .A1 ( n15 ) ) ;
OR2X1_RVT U26 (.Y ( n13 ) , .A2 ( A[6] ) , .A1 ( n14 ) ) ;
OR2X1_RVT U25 (.Y ( n12 ) , .A2 ( A[7] ) , .A1 ( n13 ) ) ;
OR2X1_RVT U24 (.Y ( n11 ) , .A2 ( A[8] ) , .A1 ( n12 ) ) ;
endmodule




module fifo4_dw8_0 (clk , rst , clr , we , re , full , empty , IN0 , 
    dout , din );
input  clk ;
input  rst ;
input  clr ;
input  we ;
input  re ;
output full ;
output empty ;
input  IN0 ;
output [8:1] dout ;
input  [8:1] din ;


wire [1:0] wp ;

INVX1_RVT U5 (.A ( n125 ) , .Y ( n22 ) ) ;
INVX0_RVT U4 (.A ( n128 ) , .Y ( n21 ) ) ;
INVX1_RVT U2 (.A ( n126 ) , .Y ( n20 ) ) ;
INVX1_RVT U1 (.A ( n129 ) , .Y ( n19 ) ) ;
NAND3X1_RVT U32 (.Y ( n129 ) , .A1 ( wp[0] ) , .A2 ( wp[1] ) , .A3 ( we ) ) ;
NAND3X1_RVT U33 (.Y ( n126 ) , .A1 ( wp[0] ) , .A2 ( n138 ) , .A3 ( we ) ) ;
NAND2X1_RVT U52 (.A2 ( n138 ) , .A1 ( n127 ) , .Y ( n125 ) ) ;
AO22X1_RVT U26 (.A2 ( din[3] ) , .A3 ( \mem[1][3] ) , .Y ( n98 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U27 (.A2 ( din[4] ) , .A3 ( \mem[1][4] ) , .Y ( n97 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U28 (.A2 ( din[5] ) , .A3 ( \mem[1][5] ) , .Y ( n96 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U29 (.A2 ( din[6] ) , .A3 ( \mem[1][6] ) , .Y ( n95 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U30 (.A2 ( din[7] ) , .A3 ( \mem[1][7] ) , .Y ( n94 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U31 (.A2 ( din[8] ) , .A3 ( \mem[1][8] ) , .Y ( n93 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U34 (.A2 ( din[1] ) , .A3 ( \mem[2][1] ) , .Y ( n108 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U35 (.A2 ( din[2] ) , .A3 ( \mem[2][2] ) , .Y ( n107 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U36 (.A2 ( din[3] ) , .A3 ( \mem[2][3] ) , .Y ( n106 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U37 (.A2 ( din[4] ) , .A3 ( \mem[2][4] ) , .Y ( n105 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U38 (.A2 ( din[5] ) , .A3 ( \mem[2][5] ) , .Y ( n104 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U39 (.A2 ( din[6] ) , .A3 ( \mem[2][6] ) , .Y ( n103 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U40 (.A2 ( din[7] ) , .A3 ( \mem[2][7] ) , .Y ( n102 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U41 (.A2 ( din[8] ) , .A3 ( \mem[2][8] ) , .Y ( n101 ) , .A4 ( n128 ) 
    , .A1 ( n21 ) ) ;
AO22X1_RVT U42 (.A2 ( din[1] ) , .A3 ( \mem[0][1] ) , .Y ( n92 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U43 (.A2 ( din[2] ) , .A3 ( \mem[0][2] ) , .Y ( n91 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U44 (.A2 ( din[3] ) , .A3 ( \mem[0][3] ) , .Y ( n90 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U45 (.A2 ( din[4] ) , .A3 ( \mem[0][4] ) , .Y ( n89 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U46 (.A2 ( din[5] ) , .A3 ( \mem[0][5] ) , .Y ( n88 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U47 (.A2 ( din[6] ) , .A3 ( \mem[0][6] ) , .Y ( n87 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U48 (.A2 ( din[7] ) , .A3 ( \mem[0][7] ) , .Y ( n86 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AO22X1_RVT U49 (.A2 ( din[8] ) , .A3 ( \mem[0][8] ) , .Y ( n85 ) , .A4 ( n125 ) 
    , .A1 ( n22 ) ) ;
AND2X1_RVT U50 (.Y ( n127 ) , .A1 ( we ) , .A2 ( n137 ) ) ;
NAND2X0_RVT U51 (.A2 ( wp[1] ) , .A1 ( n127 ) , .Y ( n128 ) ) ;
AO22X1_RVT U53 (.A2 ( wp[1] ) , .A3 ( n120 ) , .Y ( n82 ) , .A4 ( n130 ) 
    , .A1 ( n78 ) ) ;
AND2X1_RVT U54 (.Y ( n120 ) , .A1 ( n119 ) , .A2 ( clr ) ) ;
AO22X1_RVT U55 (.A2 ( N9 ) , .A3 ( n124 ) , .Y ( n84 ) , .A4 ( clr ) 
    , .A1 ( n80 ) ) ;
OAI22X1_RVT U56 (.Y ( n124 ) , .A4 ( n123 ) , .A3 ( n17 ) , .A2 ( n16 ) 
    , .A1 ( N8 ) ) ;
NAND2X0_RVT U57 (.A2 ( n16 ) , .A1 ( n122 ) , .Y ( n123 ) ) ;
AO22X1_RVT U58 (.A2 ( wp[0] ) , .A3 ( n127 ) , .Y ( n81 ) , .A4 ( clr ) 
    , .A1 ( n78 ) ) ;
AO22X1_RVT U59 (.A2 ( N8 ) , .A3 ( n121 ) , .Y ( n83 ) , .A4 ( n122 ) 
    , .A1 ( n80 ) ) ;
AND2X1_RVT U60 (.Y ( n121 ) , .A1 ( clr ) , .A2 ( n17 ) ) ;
OR2X1_RVT U61 (.Y ( n122 ) , .A2 ( re ) , .A1 ( IN0 ) ) ;
OR2X1_RVT U62 (.Y ( n119 ) , .A2 ( IN0 ) , .A1 ( we ) ) ;
AND3X1_RVT U63 (.A1 ( n118 ) , .Y ( empty ) , .A2 ( n136 ) , .A3 ( n18 ) ) ;
XNOR2X1_RVT U64 (.A2 ( wp[1] ) , .A1 ( N9 ) , .Y ( n118 ) ) ;
AND3X1_RVT U65 (.A1 ( n118 ) , .Y ( full ) , .A2 ( gb ) , .A3 ( n18 ) ) ;
XNOR2X1_RVT U66 (.A2 ( n137 ) , .A1 ( N8 ) , .Y ( n131 ) ) ;
XNOR2X1_RVT U67 (.A2 ( wp[1] ) , .A1 ( n137 ) , .Y ( n130 ) ) ;
AND2X1_RVT U68 (.Y ( n14 ) , .A1 ( n17 ) , .A2 ( n16 ) ) ;
AND2X1_RVT U69 (.Y ( n13 ) , .A1 ( N8 ) , .A2 ( n16 ) ) ;
AND2X1_RVT U70 (.Y ( n9 ) , .A1 ( N9 ) , .A2 ( N8 ) ) ;
AND2X1_RVT U71 (.Y ( n8 ) , .A1 ( N9 ) , .A2 ( n17 ) ) ;
AO22X1_RVT U72 (.A2 ( n9 ) , .A3 ( \mem[2][1] ) , .Y ( n1 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][1] ) ) ;
AO221X1_RVT U73 (.A5 ( n1 ) , .A1 ( \mem[0][1] ) , .A4 ( n13 ) , .Y ( dout[1] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][1] ) ) ;
AO22X1_RVT U74 (.A2 ( n9 ) , .A3 ( \mem[2][2] ) , .Y ( n2 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][2] ) ) ;
AO221X1_RVT U75 (.A5 ( n2 ) , .A1 ( \mem[0][2] ) , .A4 ( n13 ) , .Y ( dout[2] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][2] ) ) ;
AO22X1_RVT U76 (.A2 ( n9 ) , .A3 ( \mem[2][3] ) , .Y ( n3 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][3] ) ) ;
AO221X1_RVT U77 (.A5 ( n3 ) , .A1 ( \mem[0][3] ) , .A4 ( n13 ) , .Y ( dout[3] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][3] ) ) ;
AO22X1_RVT U78 (.A2 ( n9 ) , .A3 ( \mem[2][4] ) , .Y ( n4 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][4] ) ) ;
AO221X1_RVT U79 (.A5 ( n4 ) , .A1 ( \mem[0][4] ) , .A4 ( n13 ) , .Y ( dout[4] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][4] ) ) ;
AO22X1_RVT U80 (.A2 ( n9 ) , .A3 ( \mem[2][5] ) , .Y ( n5 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][5] ) ) ;
AO221X1_RVT U81 (.A5 ( n5 ) , .A1 ( \mem[0][5] ) , .A4 ( n13 ) , .Y ( dout[5] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][5] ) ) ;
AO22X1_RVT U82 (.A2 ( n9 ) , .A3 ( \mem[2][6] ) , .Y ( n6 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][6] ) ) ;
AO221X1_RVT U83 (.A5 ( n6 ) , .A1 ( \mem[0][6] ) , .A4 ( n13 ) , .Y ( dout[6] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][6] ) ) ;
AO22X1_RVT U84 (.A2 ( n9 ) , .A3 ( \mem[2][7] ) , .Y ( n7 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][7] ) ) ;
AO221X1_RVT U85 (.A5 ( n7 ) , .A1 ( \mem[0][7] ) , .A4 ( n13 ) , .Y ( dout[7] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][7] ) ) ;
AO22X1_RVT U86 (.A2 ( n9 ) , .A3 ( \mem[2][8] ) , .Y ( n11 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][8] ) ) ;
AO221X1_RVT U87 (.A5 ( n11 ) , .A1 ( \mem[0][8] ) , .A4 ( n13 ) , .Y ( dout[8] ) 
    , .A2 ( n14 ) , .A3 ( \mem[1][8] ) ) ;
DFFX1_RVT \mem_reg[3][8] (.D ( n109 ) , .CLK ( clk ) , .Q ( \mem[3][8] ) ) ;
DFFX1_RVT \mem_reg[3][7] (.D ( n110 ) , .CLK ( clk ) , .Q ( \mem[3][7] ) ) ;
DFFX1_RVT \mem_reg[3][6] (.D ( n111 ) , .CLK ( clk ) , .Q ( \mem[3][6] ) ) ;
DFFX1_RVT \mem_reg[3][5] (.D ( n112 ) , .CLK ( clk ) , .Q ( \mem[3][5] ) ) ;
DFFX1_RVT \mem_reg[3][4] (.D ( n113 ) , .CLK ( clk ) , .Q ( \mem[3][4] ) ) ;
DFFX1_RVT \mem_reg[3][3] (.D ( n114 ) , .CLK ( clk ) , .Q ( \mem[3][3] ) ) ;
DFFX1_RVT \mem_reg[3][2] (.D ( n115 ) , .CLK ( clk ) , .Q ( \mem[3][2] ) ) ;
DFFX1_RVT \mem_reg[3][1] (.D ( n116 ) , .CLK ( clk ) , .Q ( \mem[3][1] ) ) ;
DFFX1_RVT \mem_reg[0][8] (.D ( n85 ) , .CLK ( clk ) , .Q ( \mem[0][8] ) ) ;
DFFX1_RVT \mem_reg[0][7] (.D ( n86 ) , .CLK ( clk ) , .Q ( \mem[0][7] ) ) ;
DFFX1_RVT \mem_reg[0][6] (.D ( n87 ) , .CLK ( clk ) , .Q ( \mem[0][6] ) ) ;
DFFX1_RVT \mem_reg[0][5] (.D ( n88 ) , .CLK ( clk ) , .Q ( \mem[0][5] ) ) ;
DFFX1_RVT \mem_reg[0][4] (.D ( n89 ) , .CLK ( clk ) , .Q ( \mem[0][4] ) ) ;
DFFX1_RVT \mem_reg[0][3] (.D ( n90 ) , .CLK ( clk ) , .Q ( \mem[0][3] ) ) ;
DFFX1_RVT \mem_reg[0][2] (.D ( n91 ) , .CLK ( clk ) , .Q ( \mem[0][2] ) ) ;
DFFX1_RVT \mem_reg[0][1] (.D ( n92 ) , .CLK ( clk ) , .Q ( \mem[0][1] ) ) ;
DFFX1_RVT \mem_reg[1][8] (.D ( n93 ) , .CLK ( clk ) , .Q ( \mem[1][8] ) ) ;
DFFX1_RVT \mem_reg[1][7] (.D ( n94 ) , .CLK ( clk ) , .Q ( \mem[1][7] ) ) ;
DFFX1_RVT \mem_reg[1][6] (.D ( n95 ) , .CLK ( clk ) , .Q ( \mem[1][6] ) ) ;
DFFX1_RVT \mem_reg[1][5] (.D ( n96 ) , .CLK ( clk ) , .Q ( \mem[1][5] ) ) ;
DFFX1_RVT \mem_reg[1][4] (.D ( n97 ) , .CLK ( clk ) , .Q ( \mem[1][4] ) ) ;
DFFX1_RVT \mem_reg[1][3] (.D ( n98 ) , .CLK ( clk ) , .Q ( \mem[1][3] ) ) ;
DFFX1_RVT \mem_reg[1][2] (.D ( n99 ) , .CLK ( clk ) , .Q ( \mem[1][2] ) ) ;
DFFX1_RVT \mem_reg[1][1] (.D ( n100 ) , .CLK ( clk ) , .Q ( \mem[1][1] ) ) ;
DFFX1_RVT \mem_reg[2][8] (.D ( n101 ) , .CLK ( clk ) , .Q ( \mem[2][8] ) ) ;
DFFX1_RVT \mem_reg[2][7] (.D ( n102 ) , .CLK ( clk ) , .Q ( \mem[2][7] ) ) ;
DFFX1_RVT \mem_reg[2][6] (.D ( n103 ) , .CLK ( clk ) , .Q ( \mem[2][6] ) ) ;
DFFX1_RVT \mem_reg[2][5] (.D ( n104 ) , .CLK ( clk ) , .Q ( \mem[2][5] ) ) ;
DFFX1_RVT \mem_reg[2][4] (.D ( n105 ) , .CLK ( clk ) , .Q ( \mem[2][4] ) ) ;
DFFX1_RVT \mem_reg[2][3] (.D ( n106 ) , .CLK ( clk ) , .Q ( \mem[2][3] ) ) ;
DFFX1_RVT \mem_reg[2][2] (.D ( n107 ) , .CLK ( clk ) , .Q ( \mem[2][2] ) ) ;
DFFX1_RVT \mem_reg[2][1] (.D ( n108 ) , .CLK ( clk ) , .Q ( \mem[2][1] ) ) ;
DFFX1_RVT gb_reg (.QN ( n136 ) , .D ( n117 ) , .CLK ( clk ) , .Q ( gb ) ) ;
DFFARX1_RVT \rp_reg[1] (.QN ( n16 ) , .RSTB ( rst ) , .D ( n84 ) , .CLK ( clk ) 
    , .Q ( N9 ) ) ;
DFFARX1_RVT \wp_reg[0] (.QN ( n137 ) , .RSTB ( rst ) , .D ( n81 ) , .CLK ( clk ) 
    , .Q ( wp[0] ) ) ;
DFFARX1_RVT \rp_reg[0] (.QN ( n17 ) , .RSTB ( rst ) , .D ( n83 ) , .CLK ( clk ) 
    , .Q ( N8 ) ) ;
DFFARX1_RVT \wp_reg[1] (.QN ( n138 ) , .RSTB ( rst ) , .D ( n82 ) , .CLK ( clk ) 
    , .Q ( wp[1] ) ) ;
AND3X1_RVT U3 (.A1 ( rst ) , .Y ( n132 ) , .A2 ( clr ) , .A3 ( n131 ) ) ;
INVX1_RVT U8 (.A ( n122 ) , .Y ( n80 ) ) ;
INVX1_RVT U9 (.A ( n119 ) , .Y ( n78 ) ) ;
INVX1_RVT U10 (.A ( n131 ) , .Y ( n18 ) ) ;
NAND2X0_RVT U11 (.A2 ( n134 ) , .A1 ( n135 ) , .Y ( n117 ) ) ;
NAND3X0_RVT U12 (.Y ( n135 ) , .A1 ( n80 ) , .A2 ( rst ) , .A3 ( gb ) ) ;
NAND3X0_RVT U13 (.Y ( n134 ) , .A1 ( n133 ) , .A2 ( we ) , .A3 ( n132 ) ) ;
XNOR2X1_RVT U14 (.A2 ( n130 ) , .A1 ( N9 ) , .Y ( n133 ) ) ;
AO22X1_RVT U16 (.A2 ( n19 ) , .A3 ( \mem[3][1] ) , .Y ( n116 ) , .A4 ( n129 ) 
    , .A1 ( din[1] ) ) ;
AO22X1_RVT U17 (.A2 ( n19 ) , .A3 ( \mem[3][2] ) , .Y ( n115 ) , .A4 ( n129 ) 
    , .A1 ( din[2] ) ) ;
AO22X1_RVT U18 (.A2 ( n19 ) , .A3 ( \mem[3][3] ) , .Y ( n114 ) , .A4 ( n129 ) 
    , .A1 ( din[3] ) ) ;
AO22X1_RVT U19 (.A2 ( n19 ) , .A3 ( \mem[3][4] ) , .Y ( n113 ) , .A4 ( n129 ) 
    , .A1 ( din[4] ) ) ;
AO22X1_RVT U20 (.A2 ( n19 ) , .A3 ( \mem[3][5] ) , .Y ( n112 ) , .A4 ( n129 ) 
    , .A1 ( din[5] ) ) ;
AO22X1_RVT U21 (.A2 ( n19 ) , .A3 ( \mem[3][6] ) , .Y ( n111 ) , .A4 ( n129 ) 
    , .A1 ( din[6] ) ) ;
AO22X1_RVT U22 (.A2 ( n19 ) , .A3 ( \mem[3][7] ) , .Y ( n110 ) , .A4 ( n129 ) 
    , .A1 ( din[7] ) ) ;
AO22X1_RVT U23 (.A2 ( n19 ) , .A3 ( \mem[3][8] ) , .Y ( n109 ) , .A4 ( n129 ) 
    , .A1 ( din[8] ) ) ;
AO22X1_RVT U24 (.A2 ( din[1] ) , .A3 ( \mem[1][1] ) , .Y ( n100 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
AO22X1_RVT U25 (.A2 ( din[2] ) , .A3 ( \mem[1][2] ) , .Y ( n99 ) , .A4 ( n126 ) 
    , .A1 ( n20 ) ) ;
endmodule




module fifo4_dw8_1 (clk , rst , clr , we , re , full , empty , IN0 , 
    dout , din );
input  clk ;
input  rst ;
input  clr ;
input  we ;
input  re ;
output full ;
output empty ;
input  IN0 ;
output [8:1] dout ;
input  [8:1] din ;


wire [1:0] wp ;

INVX1_RVT U5 (.A ( n29 ) , .Y ( n82 ) ) ;
INVX1_RVT U4 (.A ( n26 ) , .Y ( n81 ) ) ;
INVX1_RVT U2 (.A ( n28 ) , .Y ( n79 ) ) ;
INVX1_RVT U1 (.A ( n25 ) , .Y ( n77 ) ) ;
NAND3X1_RVT U32 (.Y ( n25 ) , .A1 ( wp[0] ) , .A2 ( wp[1] ) , .A3 ( we ) ) ;
NAND3X1_RVT U33 (.Y ( n28 ) , .A1 ( wp[0] ) , .A2 ( n10 ) , .A3 ( we ) ) ;
NAND2X1_RVT U51 (.A2 ( wp[1] ) , .A1 ( n27 ) , .Y ( n26 ) ) ;
NAND2X1_RVT U52 (.A2 ( n10 ) , .A1 ( n27 ) , .Y ( n29 ) ) ;
AO22X1_RVT U55 (.A2 ( N9 ) , .A3 ( n30 ) , .Y ( n70 ) , .A4 ( clr ) , .A1 ( n78 ) ) ;
OAI22X1_RVT U56 (.Y ( n30 ) , .A4 ( n31 ) , .A3 ( n14 ) , .A2 ( n13 ) 
    , .A1 ( N8 ) ) ;
NAND2X0_RVT U57 (.A2 ( n13 ) , .A1 ( n32 ) , .Y ( n31 ) ) ;
AO22X1_RVT U58 (.A2 ( wp[0] ) , .A3 ( n27 ) , .Y ( n73 ) , .A4 ( clr ) 
    , .A1 ( n80 ) ) ;
AO22X1_RVT U59 (.A2 ( N8 ) , .A3 ( n33 ) , .Y ( n71 ) , .A4 ( n32 ) , .A1 ( n78 ) ) ;
AND2X1_RVT U60 (.Y ( n33 ) , .A1 ( clr ) , .A2 ( n14 ) ) ;
OR2X1_RVT U61 (.Y ( n32 ) , .A2 ( re ) , .A1 ( IN0 ) ) ;
OR2X1_RVT U62 (.Y ( n35 ) , .A2 ( IN0 ) , .A1 ( we ) ) ;
AND3X1_RVT U63 (.A1 ( n36 ) , .Y ( full ) , .A2 ( gb ) , .A3 ( n18 ) ) ;
AND3X1_RVT U64 (.A1 ( n36 ) , .Y ( empty ) , .A2 ( n15 ) , .A3 ( n18 ) ) ;
XNOR2X1_RVT U65 (.A2 ( wp[1] ) , .A1 ( N9 ) , .Y ( n36 ) ) ;
XNOR2X1_RVT U66 (.A2 ( wp[1] ) , .A1 ( n12 ) , .Y ( n24 ) ) ;
XNOR2X1_RVT U67 (.A2 ( n12 ) , .A1 ( N8 ) , .Y ( n23 ) ) ;
AND2X1_RVT U68 (.Y ( n17 ) , .A1 ( n14 ) , .A2 ( n13 ) ) ;
AND2X1_RVT U69 (.Y ( n16 ) , .A1 ( N8 ) , .A2 ( n13 ) ) ;
AND2X1_RVT U70 (.Y ( n9 ) , .A1 ( N9 ) , .A2 ( N8 ) ) ;
AND2X1_RVT U71 (.Y ( n8 ) , .A1 ( N9 ) , .A2 ( n14 ) ) ;
AO22X1_RVT U72 (.A2 ( n9 ) , .A3 ( \mem[2][1] ) , .Y ( n1 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][1] ) ) ;
AO221X1_RVT U73 (.A5 ( n1 ) , .A1 ( \mem[0][1] ) , .A4 ( n16 ) , .Y ( dout[1] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][1] ) ) ;
AO22X1_RVT U74 (.A2 ( n9 ) , .A3 ( \mem[2][2] ) , .Y ( n2 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][2] ) ) ;
AO221X1_RVT U75 (.A5 ( n2 ) , .A1 ( \mem[0][2] ) , .A4 ( n16 ) , .Y ( dout[2] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][2] ) ) ;
AO22X1_RVT U76 (.A2 ( n9 ) , .A3 ( \mem[2][3] ) , .Y ( n3 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][3] ) ) ;
AO221X1_RVT U77 (.A5 ( n3 ) , .A1 ( \mem[0][3] ) , .A4 ( n16 ) , .Y ( dout[3] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][3] ) ) ;
AO22X1_RVT U78 (.A2 ( n9 ) , .A3 ( \mem[2][4] ) , .Y ( n4 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][4] ) ) ;
AO221X1_RVT U79 (.A5 ( n4 ) , .A1 ( \mem[0][4] ) , .A4 ( n16 ) , .Y ( dout[4] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][4] ) ) ;
AO22X1_RVT U80 (.A2 ( n9 ) , .A3 ( \mem[2][5] ) , .Y ( n5 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][5] ) ) ;
AO221X1_RVT U81 (.A5 ( n5 ) , .A1 ( \mem[0][5] ) , .A4 ( n16 ) , .Y ( dout[5] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][5] ) ) ;
AO22X1_RVT U82 (.A2 ( n9 ) , .A3 ( \mem[2][6] ) , .Y ( n6 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][6] ) ) ;
AO221X1_RVT U83 (.A5 ( n6 ) , .A1 ( \mem[0][6] ) , .A4 ( n16 ) , .Y ( dout[6] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][6] ) ) ;
AO22X1_RVT U84 (.A2 ( n9 ) , .A3 ( \mem[2][7] ) , .Y ( n7 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][7] ) ) ;
AO221X1_RVT U85 (.A5 ( n7 ) , .A1 ( \mem[0][7] ) , .A4 ( n16 ) , .Y ( dout[7] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][7] ) ) ;
AO22X1_RVT U86 (.A2 ( n9 ) , .A3 ( \mem[2][8] ) , .Y ( n11 ) , .A4 ( n8 ) 
    , .A1 ( \mem[3][8] ) ) ;
AO221X1_RVT U87 (.A5 ( n11 ) , .A1 ( \mem[0][8] ) , .A4 ( n16 ) , .Y ( dout[8] ) 
    , .A2 ( n17 ) , .A3 ( \mem[1][8] ) ) ;
DFFX1_RVT gb_reg (.QN ( n15 ) , .D ( n37 ) , .CLK ( clk ) , .Q ( gb ) ) ;
DFFX1_RVT \mem_reg[3][8] (.D ( n45 ) , .CLK ( clk ) , .Q ( \mem[3][8] ) ) ;
DFFX1_RVT \mem_reg[3][7] (.D ( n44 ) , .CLK ( clk ) , .Q ( \mem[3][7] ) ) ;
DFFX1_RVT \mem_reg[3][6] (.D ( n43 ) , .CLK ( clk ) , .Q ( \mem[3][6] ) ) ;
DFFX1_RVT \mem_reg[3][5] (.D ( n42 ) , .CLK ( clk ) , .Q ( \mem[3][5] ) ) ;
DFFX1_RVT \mem_reg[3][4] (.D ( n41 ) , .CLK ( clk ) , .Q ( \mem[3][4] ) ) ;
DFFX1_RVT \mem_reg[3][3] (.D ( n40 ) , .CLK ( clk ) , .Q ( \mem[3][3] ) ) ;
DFFX1_RVT \mem_reg[3][2] (.D ( n39 ) , .CLK ( clk ) , .Q ( \mem[3][2] ) ) ;
DFFX1_RVT \mem_reg[3][1] (.D ( n38 ) , .CLK ( clk ) , .Q ( \mem[3][1] ) ) ;
DFFX1_RVT \mem_reg[0][8] (.D ( n69 ) , .CLK ( clk ) , .Q ( \mem[0][8] ) ) ;
DFFX1_RVT \mem_reg[0][7] (.D ( n68 ) , .CLK ( clk ) , .Q ( \mem[0][7] ) ) ;
DFFX1_RVT \mem_reg[0][6] (.D ( n67 ) , .CLK ( clk ) , .Q ( \mem[0][6] ) ) ;
DFFX1_RVT \mem_reg[0][5] (.D ( n66 ) , .CLK ( clk ) , .Q ( \mem[0][5] ) ) ;
DFFX1_RVT \mem_reg[0][4] (.D ( n65 ) , .CLK ( clk ) , .Q ( \mem[0][4] ) ) ;
DFFX1_RVT \mem_reg[0][3] (.D ( n64 ) , .CLK ( clk ) , .Q ( \mem[0][3] ) ) ;
DFFX1_RVT \mem_reg[0][2] (.D ( n63 ) , .CLK ( clk ) , .Q ( \mem[0][2] ) ) ;
DFFX1_RVT \mem_reg[0][1] (.D ( n62 ) , .CLK ( clk ) , .Q ( \mem[0][1] ) ) ;
DFFX1_RVT \mem_reg[1][8] (.D ( n61 ) , .CLK ( clk ) , .Q ( \mem[1][8] ) ) ;
DFFX1_RVT \mem_reg[1][7] (.D ( n60 ) , .CLK ( clk ) , .Q ( \mem[1][7] ) ) ;
DFFX1_RVT \mem_reg[1][6] (.D ( n59 ) , .CLK ( clk ) , .Q ( \mem[1][6] ) ) ;
DFFX1_RVT \mem_reg[1][5] (.D ( n58 ) , .CLK ( clk ) , .Q ( \mem[1][5] ) ) ;
DFFX1_RVT \mem_reg[1][4] (.D ( n57 ) , .CLK ( clk ) , .Q ( \mem[1][4] ) ) ;
DFFX1_RVT \mem_reg[1][3] (.D ( n56 ) , .CLK ( clk ) , .Q ( \mem[1][3] ) ) ;
DFFX1_RVT \mem_reg[1][2] (.D ( n55 ) , .CLK ( clk ) , .Q ( \mem[1][2] ) ) ;
DFFX1_RVT \mem_reg[1][1] (.D ( n54 ) , .CLK ( clk ) , .Q ( \mem[1][1] ) ) ;
DFFX1_RVT \mem_reg[2][8] (.D ( n53 ) , .CLK ( clk ) , .Q ( \mem[2][8] ) ) ;
DFFX1_RVT \mem_reg[2][7] (.D ( n52 ) , .CLK ( clk ) , .Q ( \mem[2][7] ) ) ;
DFFX1_RVT \mem_reg[2][6] (.D ( n51 ) , .CLK ( clk ) , .Q ( \mem[2][6] ) ) ;
DFFX1_RVT \mem_reg[2][5] (.D ( n50 ) , .CLK ( clk ) , .Q ( \mem[2][5] ) ) ;
DFFX1_RVT \mem_reg[2][4] (.D ( n49 ) , .CLK ( clk ) , .Q ( \mem[2][4] ) ) ;
DFFX1_RVT \mem_reg[2][3] (.D ( n48 ) , .CLK ( clk ) , .Q ( \mem[2][3] ) ) ;
DFFX1_RVT \mem_reg[2][2] (.D ( n47 ) , .CLK ( clk ) , .Q ( \mem[2][2] ) ) ;
DFFX1_RVT \mem_reg[2][1] (.D ( n46 ) , .CLK ( clk ) , .Q ( \mem[2][1] ) ) ;
DFFARX1_RVT \rp_reg[0] (.QN ( n14 ) , .RSTB ( rst ) , .D ( n71 ) , .CLK ( clk ) 
    , .Q ( N8 ) ) ;
DFFARX1_RVT \rp_reg[1] (.QN ( n13 ) , .RSTB ( rst ) , .D ( n70 ) , .CLK ( clk ) 
    , .Q ( N9 ) ) ;
DFFARX1_RVT \wp_reg[1] (.QN ( n10 ) , .RSTB ( rst ) , .D ( n72 ) , .CLK ( clk ) 
    , .Q ( wp[1] ) ) ;
DFFARX1_RVT \wp_reg[0] (.QN ( n12 ) , .RSTB ( rst ) , .D ( n73 ) , .CLK ( clk ) 
    , .Q ( wp[0] ) ) ;
AND3X1_RVT U3 (.A1 ( rst ) , .Y ( n22 ) , .A2 ( clr ) , .A3 ( n23 ) ) ;
INVX1_RVT U8 (.A ( n32 ) , .Y ( n78 ) ) ;
INVX1_RVT U9 (.A ( n35 ) , .Y ( n80 ) ) ;
INVX1_RVT U10 (.A ( n23 ) , .Y ( n18 ) ) ;
NAND2X0_RVT U11 (.A2 ( n20 ) , .A1 ( n19 ) , .Y ( n37 ) ) ;
NAND3X0_RVT U12 (.Y ( n19 ) , .A1 ( n78 ) , .A2 ( rst ) , .A3 ( gb ) ) ;
NAND3X0_RVT U13 (.Y ( n20 ) , .A1 ( n21 ) , .A2 ( we ) , .A3 ( n22 ) ) ;
XNOR2X1_RVT U14 (.A2 ( n24 ) , .A1 ( N9 ) , .Y ( n21 ) ) ;
AO22X1_RVT U16 (.A2 ( n77 ) , .A3 ( \mem[3][1] ) , .Y ( n38 ) , .A4 ( n25 ) 
    , .A1 ( din[1] ) ) ;
AO22X1_RVT U17 (.A2 ( n77 ) , .A3 ( \mem[3][2] ) , .Y ( n39 ) , .A4 ( n25 ) 
    , .A1 ( din[2] ) ) ;
AO22X1_RVT U18 (.A2 ( n77 ) , .A3 ( \mem[3][3] ) , .Y ( n40 ) , .A4 ( n25 ) 
    , .A1 ( din[3] ) ) ;
AO22X1_RVT U19 (.A2 ( n77 ) , .A3 ( \mem[3][4] ) , .Y ( n41 ) , .A4 ( n25 ) 
    , .A1 ( din[4] ) ) ;
AO22X1_RVT U20 (.A2 ( n77 ) , .A3 ( \mem[3][5] ) , .Y ( n42 ) , .A4 ( n25 ) 
    , .A1 ( din[5] ) ) ;
AO22X1_RVT U21 (.A2 ( n77 ) , .A3 ( \mem[3][6] ) , .Y ( n43 ) , .A4 ( n25 ) 
    , .A1 ( din[6] ) ) ;
AO22X1_RVT U22 (.A2 ( n77 ) , .A3 ( \mem[3][7] ) , .Y ( n44 ) , .A4 ( n25 ) 
    , .A1 ( din[7] ) ) ;
AO22X1_RVT U23 (.A2 ( n77 ) , .A3 ( \mem[3][8] ) , .Y ( n45 ) , .A4 ( n25 ) 
    , .A1 ( din[8] ) ) ;
AO22X1_RVT U24 (.A2 ( din[1] ) , .A3 ( \mem[1][1] ) , .Y ( n54 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U25 (.A2 ( din[2] ) , .A3 ( \mem[1][2] ) , .Y ( n55 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U26 (.A2 ( din[3] ) , .A3 ( \mem[1][3] ) , .Y ( n56 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U27 (.A2 ( din[4] ) , .A3 ( \mem[1][4] ) , .Y ( n57 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U28 (.A2 ( din[5] ) , .A3 ( \mem[1][5] ) , .Y ( n58 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U29 (.A2 ( din[6] ) , .A3 ( \mem[1][6] ) , .Y ( n59 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U30 (.A2 ( din[7] ) , .A3 ( \mem[1][7] ) , .Y ( n60 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U31 (.A2 ( din[8] ) , .A3 ( \mem[1][8] ) , .Y ( n61 ) , .A4 ( n28 ) 
    , .A1 ( n79 ) ) ;
AO22X1_RVT U34 (.A2 ( din[8] ) , .A3 ( \mem[2][8] ) , .Y ( n53 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U35 (.A2 ( din[8] ) , .A3 ( \mem[0][8] ) , .Y ( n69 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U36 (.A2 ( din[1] ) , .A3 ( \mem[2][1] ) , .Y ( n46 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U37 (.A2 ( din[2] ) , .A3 ( \mem[2][2] ) , .Y ( n47 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U38 (.A2 ( din[3] ) , .A3 ( \mem[2][3] ) , .Y ( n48 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U39 (.A2 ( din[4] ) , .A3 ( \mem[2][4] ) , .Y ( n49 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U40 (.A2 ( din[5] ) , .A3 ( \mem[2][5] ) , .Y ( n50 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U41 (.A2 ( din[6] ) , .A3 ( \mem[2][6] ) , .Y ( n51 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U42 (.A2 ( din[7] ) , .A3 ( \mem[2][7] ) , .Y ( n52 ) , .A4 ( n26 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U43 (.A2 ( din[1] ) , .A3 ( \mem[0][1] ) , .Y ( n62 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U44 (.A2 ( din[2] ) , .A3 ( \mem[0][2] ) , .Y ( n63 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U45 (.A2 ( din[3] ) , .A3 ( \mem[0][3] ) , .Y ( n64 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U46 (.A2 ( din[4] ) , .A3 ( \mem[0][4] ) , .Y ( n65 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U47 (.A2 ( din[5] ) , .A3 ( \mem[0][5] ) , .Y ( n66 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U48 (.A2 ( din[6] ) , .A3 ( \mem[0][6] ) , .Y ( n67 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AO22X1_RVT U49 (.A2 ( din[7] ) , .A3 ( \mem[0][7] ) , .Y ( n68 ) , .A4 ( n29 ) 
    , .A1 ( n82 ) ) ;
AND2X1_RVT U50 (.Y ( n27 ) , .A1 ( we ) , .A2 ( n12 ) ) ;
AO22X1_RVT U53 (.A2 ( wp[1] ) , .A3 ( n34 ) , .Y ( n72 ) , .A4 ( n24 ) 
    , .A1 ( n80 ) ) ;
AND2X1_RVT U54 (.Y ( n34 ) , .A1 ( n35 ) , .A2 ( clr ) ) ;
endmodule




module simple_spi_top (dat_i , adr_i , dat_o , rst_i , clk_i , mosi_o , 
    sck_o , inta_o , ack_o , miso_i , we_i , stb_i , cyc_i );
input  [7:0] dat_i ;
input  [1:0] adr_i ;
output [7:0] dat_o ;
input  rst_i ;
input  clk_i ;
output mosi_o ;
output sck_o ;
output inta_o ;
output ack_o ;
input  miso_i ;
input  we_i ;
input  stb_i ;
input  cyc_i ;

wire [11:0] clkcnt ;
wire [3:0] spsr ;
wire [7:0] wfdout ;
wire [7:0] rfdout ;
wire [6:0] treg ;

wire [1:0] state ;
wire [2:0] bcnt ;
wire [7:0] sper ;
wire [1:0] tcnt ;
wire [7:0] spcr ;


simple_spi_top_DW01_dec_0 sub_237 (
    .SUM ( {N93 , N92 , N91 , N90 , N89 , N88 , N87 , N86 , N85 , N84 , 
	N83 , N82 } ) , 
    .A ( clkcnt ) ) ;


fifo4_dw8_0 wfifo (.clk ( clk_i ) , .rst ( rst_i ) , .clr ( n1 ) , 
    .we ( wfwe ) , .re ( wfre ) , .full ( spsr[3] ) , .empty ( spsr[2] ) , 
    .IN0 ( n20 ) , .dout ( wfdout ) , .din ( dat_i ) ) ;


fifo4_dw8_1 rfifo (.clk ( clk_i ) , .rst ( rst_i ) , .clr ( n1 ) , 
    .we ( rfwe ) , .re ( rfre ) , .full ( spsr[1] ) , .empty ( spsr[0] ) , 
    .IN0 ( n20 ) , .dout ( rfdout ) , 
    .din ( {mosi_o , treg[6] , treg[5] , treg[4] , treg[3] , treg[2] , 
	treg[1] , treg[0] } ) ) ;

INVX1_RVT U5 (.A ( n58 ) , .Y ( n5 ) ) ;
INVX1_RVT U4 (.A ( n93 ) , .Y ( n4 ) ) ;
INVX1_RVT U3 (.A ( n74 ) , .Y ( n3 ) ) ;
INVX1_RVT U2 (.A ( n75 ) , .Y ( n2 ) ) ;
INVX1_RVT U1 (.A ( n20 ) , .Y ( n1 ) ) ;
NAND2X1_RVT U154 (.A2 ( n77 ) , .A1 ( n76 ) , .Y ( n75 ) ) ;
NAND2X0_RVT U264 (.A2 ( n30 ) , .A1 ( state[0] ) , .Y ( n68 ) ) ;
NAND2X0_RVT U265 (.A2 ( n147 ) , .A1 ( adr_i[0] ) , .Y ( n81 ) ) ;
OR3X2_RVT U266 (.A1 ( bcnt[1] ) , .A3 ( bcnt[0] ) , .Y ( n72 ) , .A2 ( bcnt[2] ) ) ;
AND2X1_RVT U267 (.Y ( N73 ) , .A1 ( n42 ) , .A2 ( n23 ) ) ;
AO221X1_RVT U172 (.A5 ( n136 ) , .A1 ( n64 ) , .A4 ( n63 ) , .Y ( n117 ) 
    , .A2 ( n135 ) , .A3 ( bcnt[1] ) ) ;
NOR2X0_RVT U173 (.Y ( n64 ) , .A2 ( bcnt[1] ) , .A1 ( bcnt[0] ) ) ;
AO221X1_RVT U174 (.A5 ( n136 ) , .A1 ( bcnt[2] ) , .A4 ( n157 ) , .Y ( n115 ) 
    , .A2 ( n61 ) , .A3 ( n135 ) ) ;
AO21X1_RVT U175 (.A1 ( bcnt[1] ) , .Y ( n61 ) , .A2 ( n62 ) , .A3 ( n63 ) ) ;
AO21X1_RVT U176 (.A1 ( n56 ) , .Y ( n66 ) , .A2 ( n158 ) , .A3 ( n20 ) ) ;
AO21X1_RVT U177 (.A1 ( bcnt[0] ) , .Y ( n63 ) , .A2 ( n62 ) , .A3 ( n5 ) ) ;
AO222X1_RVT U179 (.A1 ( wfdout[7] ) , .A5 ( mosi_o ) , .A6 ( n5 ) 
    , .A3 ( treg[6] ) , .A2 ( n136 ) , .Y ( n107 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U180 (.A1 ( wfdout[5] ) , .A5 ( treg[5] ) , .A6 ( n5 ) 
    , .A3 ( treg[4] ) , .A2 ( n136 ) , .Y ( n109 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U181 (.A1 ( wfdout[3] ) , .A5 ( treg[3] ) , .A6 ( n5 ) 
    , .A3 ( treg[2] ) , .A2 ( n136 ) , .Y ( n111 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U182 (.A1 ( wfdout[6] ) , .A5 ( treg[6] ) , .A6 ( n5 ) 
    , .A3 ( treg[5] ) , .A2 ( n136 ) , .Y ( n108 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U183 (.A1 ( wfdout[4] ) , .A5 ( treg[4] ) , .A6 ( n5 ) 
    , .A3 ( treg[3] ) , .A2 ( n136 ) , .Y ( n110 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U184 (.A1 ( wfdout[2] ) , .A5 ( treg[2] ) , .A6 ( n5 ) 
    , .A3 ( treg[1] ) , .A2 ( n136 ) , .Y ( n112 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U185 (.A1 ( wfdout[1] ) , .A5 ( treg[1] ) , .A6 ( n5 ) 
    , .A3 ( treg[0] ) , .A2 ( n136 ) , .Y ( n113 ) , .A4 ( n135 ) ) ;
AO222X1_RVT U186 (.A1 ( wfdout[0] ) , .A5 ( treg[0] ) , .A6 ( n5 ) 
    , .A3 ( miso_i ) , .A2 ( n136 ) , .Y ( n114 ) , .A4 ( n135 ) ) ;
AO221X1_RVT U187 (.A5 ( n136 ) , .A1 ( n135 ) , .A4 ( n5 ) , .Y ( n116 ) 
    , .A2 ( n27 ) , .A3 ( bcnt[0] ) ) ;
AND3X1_RVT U188 (.A1 ( n77 ) , .Y ( wfwe ) , .A2 ( n137 ) , .A3 ( ack_o ) ) ;
INVX1_RVT U189 (.A ( adr_i[0] ) , .Y ( n148 ) ) ;
AND2X1_RVT U190 (.Y ( n76 ) , .A1 ( adr_i[0] ) , .A2 ( adr_i[1] ) ) ;
AND2X1_RVT U191 (.Y ( n77 ) , .A1 ( we_i ) , .A2 ( n42 ) ) ;
AO22X1_RVT U192 (.A2 ( n2 ) , .A3 ( sper[4] ) , .Y ( n131 ) , .A4 ( n75 ) 
    , .A1 ( dat_i[4] ) ) ;
AO22X1_RVT U193 (.A2 ( dat_i[0] ) , .A3 ( sper[0] ) , .Y ( n127 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AO22X1_RVT U194 (.A2 ( dat_i[1] ) , .A3 ( sper[1] ) , .Y ( n128 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AO22X1_RVT U195 (.A2 ( dat_i[2] ) , .A3 ( sper[2] ) , .Y ( n129 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AO22X1_RVT U196 (.A2 ( dat_i[3] ) , .A3 ( sper[3] ) , .Y ( n130 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AO22X1_RVT U197 (.A2 ( dat_i[5] ) , .A3 ( sper[5] ) , .Y ( n132 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AO22X1_RVT U198 (.A2 ( dat_i[6] ) , .A3 ( sper[6] ) , .Y ( n133 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AO22X1_RVT U199 (.A2 ( dat_i[7] ) , .A3 ( sper[7] ) , .Y ( n134 ) , .A4 ( n75 ) 
    , .A1 ( n2 ) ) ;
AND2X1_RVT U200 (.Y ( n42 ) , .A1 ( stb_i ) , .A2 ( cyc_i ) ) ;
AO221X1_RVT U201 (.A5 ( n47 ) , .A1 ( sper[6] ) , .A4 ( tcnt[0] ) , .Y ( n105 ) 
    , .A2 ( n46 ) , .A3 ( n152 ) ) ;
AO21X1_RVT U202 (.A1 ( rfwe ) , .Y ( n46 ) , .A2 ( n159 ) , .A3 ( n20 ) ) ;
AND3X1_RVT U203 (.A1 ( n48 ) , .Y ( n47 ) , .A2 ( n34 ) , .A3 ( n45 ) ) ;
INVX1_RVT U204 (.A ( adr_i[1] ) , .Y ( n147 ) ) ;
AND2X1_RVT U205 (.Y ( n56 ) , .A1 ( state[1] ) , .A2 ( state[0] ) ) ;
AO221X1_RVT U206 (.A5 ( n73 ) , .A1 ( n156 ) , .A4 ( n143 ) , .Y ( n67 ) 
    , .A2 ( n158 ) , .A3 ( n155 ) ) ;
AO21X1_RVT U207 (.A1 ( state[1] ) , .Y ( n73 ) , .A2 ( n31 ) , .A3 ( n66 ) ) ;
AO22X1_RVT U208 (.A2 ( n43 ) , .A3 ( sper[7] ) , .Y ( n104 ) , .A4 ( n44 ) 
    , .A1 ( tcnt[1] ) ) ;
AO21X1_RVT U209 (.A1 ( n45 ) , .Y ( n44 ) , .A2 ( n159 ) , .A3 ( n20 ) ) ;
AO21X1_RVT U210 (.A1 ( tcnt[0] ) , .Y ( n43 ) , .A2 ( n45 ) , .A3 ( n152 ) ) ;
OAI22X1_RVT U211 (.Y ( n119 ) , .A4 ( n139 ) , .A3 ( n138 ) , .A2 ( n31 ) 
    , .A1 ( n67 ) ) ;
NAND2X0_RVT U212 (.A2 ( spcr[6] ) , .A1 ( n67 ) , .Y ( n138 ) ) ;
NOR2X0_RVT U213 (.Y ( n139 ) , .A2 ( n155 ) , .A1 ( n54 ) ) ;
AO22X1_RVT U214 (.A2 ( n3 ) , .A3 ( spcr[0] ) , .Y ( n120 ) , .A4 ( n74 ) 
    , .A1 ( dat_i[0] ) ) ;
AO22X1_RVT U215 (.A2 ( n3 ) , .A3 ( spcr[1] ) , .Y ( n121 ) , .A4 ( n74 ) 
    , .A1 ( dat_i[1] ) ) ;
AO22X1_RVT U216 (.A2 ( n3 ) , .A3 ( spcr[2] ) , .Y ( n122 ) , .A4 ( n74 ) 
    , .A1 ( dat_i[2] ) ) ;
AO22X1_RVT U217 (.A2 ( n3 ) , .A3 ( spcr[3] ) , .Y ( n123 ) , .A4 ( n74 ) 
    , .A1 ( dat_i[3] ) ) ;
AO22X1_RVT U218 (.A2 ( n3 ) , .A3 ( spcr[5] ) , .Y ( n124 ) , .A4 ( n74 ) 
    , .A1 ( dat_i[5] ) ) ;
AO22X1_RVT U219 (.A2 ( n3 ) , .A3 ( n74 ) , .Y ( n125 ) , .A4 ( spcr[6] ) 
    , .A1 ( dat_i[6] ) ) ;
AO22X1_RVT U220 (.A2 ( n3 ) , .A3 ( spcr[7] ) , .Y ( n126 ) , .A4 ( n74 ) 
    , .A1 ( dat_i[7] ) ) ;
AO22X1_RVT U221 (.A2 ( n151 ) , .A3 ( n50 ) , .Y ( n106 ) , .A4 ( n51 ) 
    , .A1 ( sck_o ) ) ;
AO22X1_RVT U222 (.A2 ( spcr[6] ) , .A3 ( n53 ) , .Y ( n50 ) , .A4 ( spcr[2] ) 
    , .A1 ( n52 ) ) ;
INVX1_RVT U223 (.A ( n51 ) , .Y ( n151 ) ) ;
AND2X1_RVT U224 (.Y ( n53 ) , .A1 ( N185 ) , .A2 ( n32 ) ) ;
AND4X1_RVT U225 (.Y ( rfre ) , .A1 ( ack_o ) , .A3 ( n42 ) , .A4 ( n149 ) 
    , .A2 ( n137 ) ) ;
INVX1_RVT U226 (.A ( we_i ) , .Y ( n149 ) ) ;
OR2X1_RVT U227 (.Y ( n49 ) , .A2 ( rfwe ) , .A1 ( n20 ) ) ;
NAND2X0_RVT U228 (.A2 ( n30 ) , .A1 ( n31 ) , .Y ( n91 ) ) ;
NAND2X0_RVT U229 (.A2 ( n101 ) , .A1 ( n100 ) , .Y ( n90 ) ) ;
OR3X2_RVT U230 (.A1 ( clkcnt[3] ) , .A3 ( clkcnt[1] ) , .Y ( n103 ) 
    , .A2 ( clkcnt[2] ) ) ;
OAI22X1_RVT U231 (.Y ( n118 ) , .A4 ( n69 ) , .A3 ( n68 ) , .A2 ( n67 ) 
    , .A1 ( n30 ) ) ;
NAND2X0_RVT U232 (.A2 ( spcr[6] ) , .A1 ( n67 ) , .Y ( n69 ) ) ;
OR3X2_RVT U233 (.A1 ( clkcnt[9] ) , .A3 ( clkcnt[7] ) , .Y ( n102 ) 
    , .A2 ( clkcnt[8] ) ) ;
AO221X1_RVT U234 (.A5 ( n83 ) , .A1 ( n76 ) , .A4 ( n137 ) , .Y ( N71 ) 
    , .A2 ( sper[7] ) , .A3 ( rfdout[7] ) ) ;
AO22X1_RVT U235 (.A2 ( n84 ) , .A3 ( n146 ) , .Y ( n83 ) , .A4 ( spsr_7 ) 
    , .A1 ( spcr[7] ) ) ;
AO221X1_RVT U236 (.A5 ( n85 ) , .A1 ( n76 ) , .A4 ( n137 ) , .Y ( N70 ) 
    , .A2 ( sper[6] ) , .A3 ( rfdout[6] ) ) ;
AO22X1_RVT U237 (.A2 ( spcr[6] ) , .A3 ( spsr_6 ) , .Y ( n85 ) , .A4 ( n146 ) 
    , .A1 ( n84 ) ) ;
AO221X1_RVT U238 (.A5 ( n84 ) , .A1 ( sper[4] ) , .A4 ( n137 ) , .Y ( N68 ) 
    , .A2 ( n76 ) , .A3 ( rfdout[4] ) ) ;
AO221X1_RVT U239 (.A5 ( n86 ) , .A1 ( sper[3] ) , .A4 ( n137 ) , .Y ( N67 ) 
    , .A2 ( n76 ) , .A3 ( rfdout[3] ) ) ;
AO22X1_RVT U240 (.A2 ( spcr[3] ) , .A3 ( spsr[3] ) , .Y ( n86 ) , .A4 ( n146 ) 
    , .A1 ( n84 ) ) ;
AO221X1_RVT U241 (.A5 ( n87 ) , .A1 ( sper[2] ) , .A4 ( n137 ) , .Y ( N66 ) 
    , .A2 ( n76 ) , .A3 ( rfdout[2] ) ) ;
AO22X1_RVT U242 (.A2 ( spcr[2] ) , .A3 ( spsr[2] ) , .Y ( n87 ) , .A4 ( n146 ) 
    , .A1 ( n84 ) ) ;
AO221X1_RVT U243 (.A5 ( n88 ) , .A1 ( sper[1] ) , .A4 ( n137 ) , .Y ( N65 ) 
    , .A2 ( n76 ) , .A3 ( rfdout[1] ) ) ;
AO22X1_RVT U244 (.A2 ( n84 ) , .A3 ( spsr[1] ) , .Y ( n88 ) , .A4 ( n146 ) 
    , .A1 ( spcr[1] ) ) ;
AO221X1_RVT U245 (.A5 ( n89 ) , .A1 ( sper[0] ) , .A4 ( n137 ) , .Y ( N64 ) 
    , .A2 ( n76 ) , .A3 ( rfdout[0] ) ) ;
AO22X1_RVT U246 (.A2 ( n84 ) , .A3 ( spsr[0] ) , .Y ( n89 ) , .A4 ( n146 ) 
    , .A1 ( spcr[0] ) ) ;
AO222X1_RVT U247 (.A1 ( rfdout[5] ) , .A5 ( spcr[5] ) , .A6 ( n84 ) 
    , .A3 ( sper[5] ) , .A2 ( n137 ) , .Y ( N69 ) , .A4 ( n76 ) ) ;
AND3X1_RVT U248 (.A1 ( n78 ) , .Y ( N78 ) , .A2 ( spcr[6] ) , .A3 ( n79 ) ) ;
NAND3X0_RVT U249 (.Y ( n78 ) , .A1 ( dat_i[6] ) , .A2 ( n77 ) , .A3 ( n146 ) ) ;
AO21X1_RVT U250 (.A1 ( spsr[3] ) , .Y ( n79 ) , .A2 ( wfwe ) , .A3 ( spsr_6 ) ) ;
AO21X1_RVT U251 (.A1 ( sper[0] ) , .Y ( n96 ) , .A2 ( n22 ) , .A3 ( n95 ) ) ;
AO22X1_RVT U252 (.A2 ( n32 ) , .A3 ( spcr[3] ) , .Y ( n52 ) , .A4 ( n55 ) 
    , .A1 ( n54 ) ) ;
AO22X1_RVT U253 (.A2 ( n56 ) , .A3 ( n155 ) , .Y ( n55 ) , .A4 ( n57 ) 
    , .A1 ( n157 ) ) ;
NAND2X0_RVT U254 (.A2 ( n143 ) , .A1 ( spcr[2] ) , .Y ( n57 ) ) ;
AO21X1_RVT U255 (.A1 ( sper[0] ) , .Y ( n95 ) , .A2 ( spcr[1] ) , .A3 ( n94 ) ) ;
AO21X1_RVT U256 (.A1 ( n92 ) , .Y ( n94 ) , .A2 ( sper[0] ) , .A3 ( sper[1] ) ) ;
AND2X1_RVT U257 (.Y ( n92 ) , .A1 ( spcr[1] ) , .A2 ( spcr[0] ) ) ;
OR2X1_RVT U258 (.Y ( n98 ) , .A2 ( sper[0] ) , .A1 ( n97 ) ) ;
OR2X1_RVT U259 (.Y ( n99 ) , .A2 ( spcr[1] ) , .A1 ( n98 ) ) ;
OA221X1_RVT U260 (.A1 ( n80 ) , .A4 ( n82 ) , .A2 ( spsr_7 ) , .A5 ( spcr[6] ) 
    , .Y ( N76 ) , .A3 ( n81 ) ) ;
NAND2X0_RVT U261 (.A2 ( n77 ) , .A1 ( dat_i[7] ) , .Y ( n82 ) ) ;
AND2X1_RVT U262 (.Y ( n80 ) , .A1 ( rfwe ) , .A2 ( n159 ) ) ;
OR2X1_RVT U263 (.Y ( n48 ) , .A2 ( tcnt[0] ) , .A1 ( tcnt[1] ) ) ;
NOR4X1_RVT U120 (.Y ( n101 ) , .A4 ( clkcnt[5] ) , .A2 ( clkcnt[4] ) 
    , .A3 ( clkcnt[6] ) , .A1 ( n102 ) ) ;
NOR4X1_RVT U122 (.Y ( n100 ) , .A4 ( clkcnt[10] ) , .A2 ( clkcnt[0] ) 
    , .A3 ( clkcnt[11] ) , .A1 ( n103 ) ) ;
DFFX1_RVT wcol_reg (.D ( N78 ) , .CLK ( clk_i ) , .Q ( spsr_6 ) ) ;
DFFX1_RVT spif_reg (.D ( N76 ) , .CLK ( clk_i ) , .Q ( spsr_7 ) ) ;
DFFARX1_RVT \sper_reg[4] (.RSTB ( rst_i ) , .D ( n131 ) , .CLK ( clk_i ) 
    , .Q ( sper[4] ) ) ;
DFFARX1_RVT \sper_reg[3] (.RSTB ( rst_i ) , .D ( n130 ) , .CLK ( clk_i ) 
    , .Q ( sper[3] ) ) ;
DFFARX1_RVT \sper_reg[2] (.RSTB ( rst_i ) , .D ( n129 ) , .CLK ( clk_i ) 
    , .Q ( sper[2] ) ) ;
DFFARX1_RVT \sper_reg[5] (.RSTB ( rst_i ) , .D ( n132 ) , .CLK ( clk_i ) 
    , .Q ( sper[5] ) ) ;
DFFARX1_RVT \spcr_reg[5] (.RSTB ( rst_i ) , .D ( n124 ) , .CLK ( clk_i ) 
    , .Q ( spcr[5] ) ) ;
DFFARX1_RVT \spcr_reg[3] (.RSTB ( rst_i ) , .D ( n123 ) , .CLK ( clk_i ) 
    , .Q ( spcr[3] ) ) ;
DFFARX1_RVT \sper_reg[6] (.RSTB ( rst_i ) , .D ( n133 ) , .CLK ( clk_i ) 
    , .Q ( sper[6] ) ) ;
DFFARX1_RVT \sper_reg[7] (.RSTB ( rst_i ) , .D ( n134 ) , .CLK ( clk_i ) 
    , .Q ( sper[7] ) ) ;
DFFARX1_RVT \spcr_reg[7] (.RSTB ( rst_i ) , .D ( n126 ) , .CLK ( clk_i ) 
    , .Q ( spcr[7] ) ) ;
DFFX1_RVT sck_o_reg (.QN ( n32 ) , .D ( n106 ) , .CLK ( clk_i ) , .Q ( sck_o ) ) ;
DFFX1_RVT \tcnt_reg[1] (.D ( n104 ) , .CLK ( clk_i ) , .Q ( tcnt[1] ) ) ;
DFFX1_RVT \bcnt_reg[2] (.D ( n115 ) , .CLK ( clk_i ) , .Q ( bcnt[2] ) ) ;
DFFX1_RVT \tcnt_reg[0] (.QN ( n34 ) , .D ( n105 ) , .CLK ( clk_i ) 
    , .Q ( tcnt[0] ) ) ;
SDFFSSRX1_RVT wfre_reg (.SI ( 1'b0 ), .D ( n143 ) , .SE ( n20 ) , .RSTB ( n155 ) 
    , .Q ( wfre ) , .SETB ( 1'b1 ), .CLK ( clk_i ) ) ;
DFFX1_RVT \bcnt_reg[0] (.QN ( n27 ) , .D ( n116 ) , .CLK ( clk_i ) 
    , .Q ( bcnt[0] ) ) ;
DFFX1_RVT \bcnt_reg[1] (.D ( n117 ) , .CLK ( clk_i ) , .Q ( bcnt[1] ) ) ;
DFFX1_RVT \treg_reg[7] (.D ( n107 ) , .CLK ( clk_i ) , .Q ( mosi_o ) ) ;
DFFX1_RVT \treg_reg[0] (.D ( n114 ) , .CLK ( clk_i ) , .Q ( treg[0] ) ) ;
DFFX1_RVT \treg_reg[1] (.D ( n113 ) , .CLK ( clk_i ) , .Q ( treg[1] ) ) ;
DFFX1_RVT \treg_reg[2] (.D ( n112 ) , .CLK ( clk_i ) , .Q ( treg[2] ) ) ;
DFFX1_RVT \treg_reg[3] (.D ( n111 ) , .CLK ( clk_i ) , .Q ( treg[3] ) ) ;
DFFX1_RVT \treg_reg[4] (.D ( n110 ) , .CLK ( clk_i ) , .Q ( treg[4] ) ) ;
DFFX1_RVT \treg_reg[5] (.D ( n109 ) , .CLK ( clk_i ) , .Q ( treg[5] ) ) ;
DFFX1_RVT \treg_reg[6] (.D ( n108 ) , .CLK ( clk_i ) , .Q ( treg[6] ) ) ;
DFFARX1_RVT \spcr_reg[2] (.RSTB ( rst_i ) , .D ( n122 ) , .CLK ( clk_i ) 
    , .Q ( spcr[2] ) ) ;
DFFARX1_RVT \spcr_reg[0] (.QN ( n22 ) , .RSTB ( rst_i ) , .D ( n120 ) 
    , .CLK ( clk_i ) , .Q ( spcr[0] ) ) ;
DFFARX1_RVT \sper_reg[0] (.QN ( n15 ) , .RSTB ( rst_i ) , .D ( n127 ) 
    , .CLK ( clk_i ) , .Q ( sper[0] ) ) ;
DFFARX1_RVT \spcr_reg[1] (.QN ( n14 ) , .RSTB ( rst_i ) , .D ( n121 ) 
    , .CLK ( clk_i ) , .Q ( spcr[1] ) ) ;
DFFARX1_RVT \sper_reg[1] (.RSTB ( rst_i ) , .D ( n128 ) , .CLK ( clk_i ) 
    , .Q ( sper[1] ) ) ;
SDFFX1_RVT \clkcnt_reg[4] (.Q ( clkcnt[4] ) , .CLK ( clk_i ) , .D ( N86 ) 
    , .SE ( n93 ) , .SI ( n96 ) ) ;
SDFFX1_RVT \clkcnt_reg[6] (.Q ( clkcnt[6] ) , .CLK ( clk_i ) , .D ( N88 ) 
    , .SE ( n93 ) , .SI ( n94 ) ) ;
SDFFX1_RVT \clkcnt_reg[5] (.Q ( clkcnt[5] ) , .CLK ( clk_i ) , .D ( N87 ) 
    , .SE ( n93 ) , .SI ( n95 ) ) ;
SDFFX1_RVT \clkcnt_reg[7] (.Q ( clkcnt[7] ) , .CLK ( clk_i ) , .D ( N89 ) 
    , .SE ( n93 ) , .SI ( sper[1] ) ) ;
DFFARX1_RVT ack_o_reg (.QN ( n23 ) , .RSTB ( rst_i ) , .D ( N73 ) 
    , .CLK ( clk_i ) , .Q ( ack_o ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[3] (.SI ( N85 ) , .D ( n96 ) , .SE ( n4 ) 
    , .RSTB ( 1'b1 ), .Q ( clkcnt[3] ) , .SETB ( n154 ) , .CLK ( clk_i ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[9] (.SI ( N91 ) , .D ( sper[1] ) , .SE ( n4 ) 
    , .RSTB ( spcr[1] ) , .Q ( clkcnt[9] ) , .SETB ( 1'b1 ), .CLK ( clk_i ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[1] (.SI ( N83 ) , .D ( n98 ) , .SE ( n4 ) 
    , .RSTB ( 1'b1 ), .Q ( clkcnt[1] ) , .SETB ( n14 ) , .CLK ( clk_i ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[2] (.SI ( N84 ) , .D ( n97 ) , .SE ( n4 ) 
    , .RSTB ( 1'b1 ), .Q ( clkcnt[2] ) , .SETB ( n15 ) , .CLK ( clk_i ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[8] (.SI ( N90 ) , .D ( spcr[0] ) , .SE ( n4 ) 
    , .RSTB ( sper[1] ) , .Q ( clkcnt[8] ) , .SETB ( n14 ) , .CLK ( clk_i ) ) ;
DFFSSRX1_RVT \clkcnt_reg[11] (.Q ( clkcnt[11] ) , .SETB ( 1'b1 ), .CLK ( clk_i ) 
    , .D ( N93 ) , .RSTB ( n4 ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[10] (.SI ( N92 ) , .D ( sper[1] ) , .SE ( n4 ) 
    , .RSTB ( n92 ) , .Q ( clkcnt[10] ) , .SETB ( 1'b1 ), .CLK ( clk_i ) ) ;
SDFFSSRX1_RVT \clkcnt_reg[0] (.SI ( N82 ) , .D ( n99 ) , .SE ( n4 ) 
    , .RSTB ( 1'b1 ), .Q ( clkcnt[0] ) , .SETB ( n22 ) , .CLK ( clk_i ) ) ;
DFFX1_RVT \state_reg[0] (.QN ( n31 ) , .D ( n119 ) , .CLK ( clk_i ) 
    , .Q ( state[0] ) ) ;
DFFX1_RVT \state_reg[1] (.QN ( n30 ) , .D ( n118 ) , .CLK ( clk_i ) 
    , .Q ( state[1] ) ) ;
SDFFSSRX1_RVT rfwe_reg (.SI ( 1'b0 ), .D ( n158 ) , .SE ( n72 ) , .RSTB ( n62 ) 
    , .Q ( rfwe ) , .SETB ( 1'b1 ), .CLK ( clk_i ) ) ;
DFFARX1_RVT \spcr_reg[6] (.QN ( n20 ) , .RSTB ( rst_i ) , .D ( n125 ) 
    , .CLK ( clk_i ) , .Q ( spcr[6] ) ) ;
DFFX1_RVT \dat_o_reg[0] (.D ( N64 ) , .CLK ( clk_i ) , .Q ( dat_o[0] ) ) ;
DFFX1_RVT \dat_o_reg[1] (.D ( N65 ) , .CLK ( clk_i ) , .Q ( dat_o[1] ) ) ;
DFFX1_RVT \dat_o_reg[2] (.D ( N66 ) , .CLK ( clk_i ) , .Q ( dat_o[2] ) ) ;
DFFX1_RVT \dat_o_reg[3] (.D ( N67 ) , .CLK ( clk_i ) , .Q ( dat_o[3] ) ) ;
DFFX1_RVT \dat_o_reg[4] (.D ( N68 ) , .CLK ( clk_i ) , .Q ( dat_o[4] ) ) ;
DFFX1_RVT \dat_o_reg[5] (.D ( N69 ) , .CLK ( clk_i ) , .Q ( dat_o[5] ) ) ;
DFFX1_RVT \dat_o_reg[6] (.D ( N70 ) , .CLK ( clk_i ) , .Q ( dat_o[6] ) ) ;
DFFX1_RVT \dat_o_reg[7] (.D ( N71 ) , .CLK ( clk_i ) , .Q ( dat_o[7] ) ) ;
DFFSSRX1_RVT inta_o_reg (.Q ( inta_o ) , .SETB ( 1'b1 ), .CLK ( clk_i ) 
    , .D ( spsr_7 ) , .RSTB ( spcr[7] ) ) ;
AND2X1_RVT U142 (.Y ( n135 ) , .A1 ( n65 ) , .A2 ( n56 ) ) ;
AND2X1_RVT U143 (.Y ( n136 ) , .A1 ( n65 ) , .A2 ( n155 ) ) ;
AND2X1_RVT U144 (.Y ( n137 ) , .A1 ( adr_i[1] ) , .A2 ( n148 ) ) ;
AND2X1_RVT U147 (.Y ( n65 ) , .A1 ( n58 ) , .A2 ( spcr[6] ) ) ;
AO21X1_RVT U150 (.A1 ( n156 ) , .Y ( n51 ) , .A2 ( n158 ) , .A3 ( n58 ) ) ;
AND3X1_RVT U151 (.A1 ( spcr[6] ) , .Y ( N185 ) , .A2 ( n143 ) , .A3 ( n155 ) ) ;
OR2X1_RVT U153 (.Y ( n58 ) , .A2 ( n155 ) , .A1 ( n66 ) ) ;
INVX1_RVT U155 (.A ( n91 ) , .Y ( n155 ) ) ;
INVX1_RVT U156 (.A ( n90 ) , .Y ( n158 ) ) ;
AND2X1_RVT U157 (.Y ( n84 ) , .A1 ( n148 ) , .A2 ( n147 ) ) ;
NAND3X0_RVT U158 (.Y ( n93 ) , .A1 ( n91 ) , .A2 ( spcr[6] ) , .A3 ( n90 ) ) ;
AND2X1_RVT U159 (.Y ( n45 ) , .A1 ( n49 ) , .A2 ( spcr[6] ) ) ;
INVX1_RVT U160 (.A ( n49 ) , .Y ( n152 ) ) ;
NAND2X0_RVT U161 (.A2 ( n77 ) , .A1 ( n84 ) , .Y ( n74 ) ) ;
INVX1_RVT U162 (.A ( spsr[2] ) , .Y ( n143 ) ) ;
OR2X1_RVT U163 (.Y ( n97 ) , .A2 ( n92 ) , .A1 ( n96 ) ) ;
INVX1_RVT U164 (.A ( n81 ) , .Y ( n146 ) ) ;
INVX1_RVT U165 (.A ( n92 ) , .Y ( n154 ) ) ;
AO21X1_RVT U166 (.A1 ( n56 ) , .Y ( n54 ) , .A2 ( n72 ) , .A3 ( n156 ) ) ;
AND2X1_RVT U167 (.Y ( n62 ) , .A1 ( n56 ) , .A2 ( spcr[6] ) ) ;
INVX1_RVT U168 (.A ( n68 ) , .Y ( n156 ) ) ;
INVX1_RVT U169 (.A ( n72 ) , .Y ( n157 ) ) ;
INVX1_RVT U170 (.A ( n48 ) , .Y ( n159 ) ) ;
endmodule


