//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/06/2025 at 09:38:05
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :usb_phy.mw
// Cell Name    :usb_phy
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./outputs/usb_phy_extracted.v
//


module usb_rx_phy (fs_ce , RxValid_o , RxActive_o , RxError_o , IN0 , 
    LineState , clk , rst , rxd , rxdp , rxdn , RxEn_i , DataIn_o );
output fs_ce ;
output RxValid_o ;
output RxActive_o ;
output RxError_o ;
input  IN0 ;
output [1:0] LineState ;
input  clk ;
input  rst ;
input  rxd ;
input  rxdp ;
input  rxdn ;
input  RxEn_i ;
output [7:0] DataIn_o ;


wire [2:0] one_cnt ;

INVX0_RVT U1 (.A ( n3 ) , .Y ( n57 ) ) ;
DFFX1_RVT \hold_reg_reg[5] (.D ( n96 ) , .CLK ( clk ) , .Q ( DataIn_o[5] ) ) ;
DFFX1_RVT \hold_reg_reg[4] (.D ( n95 ) , .CLK ( clk ) , .Q ( DataIn_o[4] ) ) ;
DFFX1_RVT \hold_reg_reg[3] (.D ( n94 ) , .CLK ( clk ) , .Q ( DataIn_o[3] ) ) ;
DFFX1_RVT \hold_reg_reg[2] (.D ( n93 ) , .CLK ( clk ) , .Q ( DataIn_o[2] ) ) ;
DFFX1_RVT \hold_reg_reg[1] (.D ( n92 ) , .CLK ( clk ) , .Q ( DataIn_o[1] ) ) ;
DFFX1_RVT \hold_reg_reg[7] (.D ( n98 ) , .CLK ( clk ) , .Q ( DataIn_o[7] ) ) ;
INVX1_RVT U3 (.A ( n22 ) , .Y ( n46 ) ) ;
INVX1_RVT U4 (.A ( n44 ) , .Y ( n21 ) ) ;
INVX1_RVT U5 (.A ( n14 ) , .Y ( n36 ) ) ;
AO22X1_RVT U7 (.A2 ( DataIn_o[1] ) , .A3 ( n57 ) , .Y ( n92 ) 
    , .A4 ( DataIn_o[2] ) , .A1 ( n3 ) ) ;
AO22X1_RVT U8 (.A2 ( DataIn_o[2] ) , .A3 ( n57 ) , .Y ( n93 ) 
    , .A4 ( DataIn_o[3] ) , .A1 ( n3 ) ) ;
AO22X1_RVT U9 (.A2 ( DataIn_o[3] ) , .A3 ( n57 ) , .Y ( n94 ) 
    , .A4 ( DataIn_o[4] ) , .A1 ( n3 ) ) ;
AO22X1_RVT U10 (.A2 ( DataIn_o[4] ) , .A3 ( n57 ) , .Y ( n95 ) 
    , .A4 ( DataIn_o[5] ) , .A1 ( n3 ) ) ;
AO22X1_RVT U11 (.A2 ( DataIn_o[5] ) , .A3 ( n57 ) , .Y ( n96 ) 
    , .A4 ( DataIn_o[6] ) , .A1 ( n3 ) ) ;
AO22X1_RVT U12 (.A2 ( DataIn_o[6] ) , .A3 ( n57 ) , .Y ( n97 ) 
    , .A4 ( DataIn_o[7] ) , .A1 ( n3 ) ) ;
NAND2X0_RVT U13 (.A2 ( n119 ) , .A1 ( fs_ce ) , .Y ( n22 ) ) ;
AO22X1_RVT U14 (.A2 ( n6 ) , .A3 ( n19 ) , .Y ( n37 ) , .A4 ( n40 ) , .A1 ( n34 ) ) ;
OR2X1_RVT U15 (.Y ( n49 ) , .A2 ( n120 ) , .A1 ( rst ) ) ;
NAND4X0_RVT U16 (.A2 ( n25 ) , .A4 ( n39 ) , .A3 ( n7 ) , .Y ( n44 ) 
    , .A1 ( n120 ) ) ;
INVX1_RVT U17 (.A ( n67 ) , .Y ( n25 ) ) ;
INVX1_RVT U18 (.A ( n73 ) , .Y ( n28 ) ) ;
NAND2X0_RVT U19 (.A2 ( n42 ) , .A1 ( n39 ) , .Y ( n14 ) ) ;
AO22X1_RVT U20 (.A2 ( DataIn_o[0] ) , .A3 ( n57 ) , .Y ( n91 ) 
    , .A4 ( DataIn_o[1] ) , .A1 ( n3 ) ) ;
AO22X1_RVT U21 (.A2 ( DataIn_o[7] ) , .A3 ( sd_nrzi ) , .Y ( n98 ) , .A4 ( n57 ) 
    , .A1 ( n3 ) ) ;
NAND2X0_RVT U22 (.A2 ( n46 ) , .A1 ( shift_en ) , .Y ( n3 ) ) ;
NAND3X0_RVT U23 (.Y ( n119 ) , .A1 ( one_cnt[1] ) , .A2 ( n6 ) 
    , .A3 ( one_cnt[2] ) ) ;
AO22X1_RVT U24 (.A2 ( n6 ) , .A3 ( n41 ) , .Y ( n129 ) , .A4 ( one_cnt[0] ) 
    , .A1 ( n34 ) ) ;
AND2X1_RVT U25 (.Y ( n38 ) , .A1 ( n34 ) , .A2 ( n10 ) ) ;
AND2X1_RVT U26 (.Y ( n27 ) , .A1 ( n47 ) , .A2 ( n5 ) ) ;
AND4X1_RVT U27 (.Y ( n24 ) , .A1 ( n115 ) , .A3 ( n5 ) , .A4 ( n4 ) , .A2 ( n47 ) ) ;
AND4X1_RVT U28 (.Y ( n33 ) , .A1 ( one_cnt[0] ) , .A3 ( one_cnt[1] ) 
    , .A4 ( n11 ) , .A2 ( n34 ) ) ;
AOI21X1_RVT U29 (.Y ( n123 ) , .A2 ( n17 ) , .A3 ( rst ) , .A1 ( n16 ) ) ;
NAND2X0_RVT U30 (.A2 ( n22 ) , .A1 ( rx_valid1 ) , .Y ( n16 ) ) ;
NAND4X0_RVT U31 (.A2 ( n5 ) , .A4 ( n9 ) , .A3 ( n4 ) , .Y ( n17 ) , .A1 ( n46 ) ) ;
AND3X1_RVT U32 (.A1 ( n14 ) , .Y ( n122 ) , .A2 ( fs_ce ) , .A3 ( sd_nrzi ) ) ;
AO22X1_RVT U33 (.A2 ( shift_en ) , .A3 ( n43 ) , .Y ( n130 ) , .A4 ( fs_ce ) 
    , .A1 ( n110 ) ) ;
NAND2X0_RVT U34 (.A2 ( n44 ) , .A1 ( n114 ) , .Y ( n43 ) ) ;
AO22X1_RVT U35 (.A2 ( n110 ) , .A3 ( rxd_s ) , .Y ( n100 ) , .A4 ( fs_ce ) 
    , .A1 ( sd_r ) ) ;
AO22X1_RVT U36 (.A2 ( n110 ) , .A3 ( n36 ) , .Y ( n101 ) , .A4 ( fs_ce ) 
    , .A1 ( se0_s ) ) ;
AO22X1_RVT U37 (.A2 ( RxActive_o ) , .A3 ( n62 ) , .Y ( n135 ) , .A4 ( n21 ) 
    , .A1 ( n20 ) ) ;
AND2X1_RVT U38 (.Y ( n62 ) , .A1 ( IN0 ) , .A2 ( n64 ) ) ;
INVX1_RVT U39 (.A ( n64 ) , .Y ( n20 ) ) ;
AND2X1_RVT U40 (.Y ( n134 ) , .A1 ( IN0 ) , .A2 ( n58 ) ) ;
AO221X1_RVT U41 (.A5 ( n114 ) , .A1 ( n59 ) , .A4 ( sd_nrzi ) , .Y ( n58 ) 
    , .A2 ( fs_ce ) , .A3 ( n110 ) ) ;
XNOR2X1_RVT U42 (.A2 ( rxd_s ) , .A1 ( sd_r ) , .Y ( n59 ) ) ;
OAI21X1_RVT U43 (.Y ( n131 ) , .A3 ( n13 ) , .A2 ( n111 ) , .A1 ( n12 ) ) ;
AOI21X1_RVT U44 (.Y ( n12 ) , .A2 ( n112 ) , .A3 ( n51 ) , .A1 ( n48 ) ) ;
NAND4X0_RVT U45 (.A2 ( n48 ) , .A4 ( n8 ) , .A3 ( n49 ) , .Y ( n13 ) 
    , .A1 ( n111 ) ) ;
AO22X1_RVT U46 (.A2 ( n8 ) , .A3 ( n52 ) , .Y ( n132 ) , .A4 ( n48 ) 
    , .A1 ( n51 ) ) ;
NOR3X0_RVT U47 (.Y ( n121 ) , .A1 ( n1 ) , .A3 ( n28 ) , .A2 ( n2 ) ) ;
NAND2X0_RVT U48 (.A2 ( n74 ) , .A1 ( rx_en ) , .Y ( n73 ) ) ;
XOR2X1_RVT U49 (.Y ( n74 ) , .A2 ( rxd_r ) , .A1 ( rxd_s ) ) ;
OAI22X1_RVT U51 (.Y ( n133 ) , .A4 ( n35 ) , .A3 ( n54 ) , .A2 ( n113 ) 
    , .A1 ( n49 ) ) ;
AO21X1_RVT U52 (.A1 ( n112 ) , .Y ( n67 ) , .A2 ( n56 ) , .A3 ( n111 ) ) ;
AO21X1_RVT U53 (.A1 ( rx_valid_r ) , .Y ( n136 ) , .A2 ( n110 ) 
    , .A3 ( RxValid_o ) ) ;
NAND2X0_RVT U54 (.A2 ( n70 ) , .A1 ( n69 ) , .Y ( N87 ) ) ;
NAND3X0_RVT U55 (.Y ( n70 ) , .A1 ( n71 ) , .A2 ( n56 ) , .A3 ( n113 ) ) ;
NAND3X0_RVT U56 (.Y ( n69 ) , .A1 ( n67 ) , .A2 ( n7 ) , .A3 ( n53 ) ) ;
NAND2X0_RVT U57 (.A2 ( n112 ) , .A1 ( n111 ) , .Y ( n71 ) ) ;
NAND3X0_RVT U58 (.Y ( n56 ) , .A1 ( rx_en ) , .A2 ( n39 ) , .A3 ( rxdn_s ) ) ;
NAND3X0_RVT U59 (.Y ( n53 ) , .A1 ( rx_en ) , .A2 ( n42 ) , .A3 ( rxdp_s ) ) ;
NOR3X0_RVT U60 (.Y ( n48 ) , .A1 ( rst ) , .A3 ( n53 ) , .A2 ( n113 ) ) ;
AO22X1_RVT U61 (.A2 ( rxd_s ) , .A3 ( rxd_s1 ) , .Y ( n137 ) , .A4 ( n68 ) 
    , .A1 ( rxd_s0 ) ) ;
OR2X1_RVT U62 (.Y ( n68 ) , .A2 ( rxd_s ) , .A1 ( rxd_s0 ) ) ;
OAI221X1_RVT U63 (.Y ( N31 ) , .A5 ( IN0 ) , .A1 ( n73 ) , .A4 ( n1 ) 
    , .A3 ( n28 ) , .A2 ( n103 ) ) ;
AND4X1_RVT U64 (.Y ( N166 ) , .A1 ( n36 ) , .A3 ( RxActive_o ) , .A4 ( n76 ) 
    , .A2 ( n75 ) ) ;
NAND3X0_RVT U65 (.Y ( RxError_o ) , .A1 ( n78 ) , .A2 ( n79 ) , .A3 ( n77 ) ) ;
NAND2X0_RVT U66 (.A2 ( n1 ) , .A1 ( n2 ) , .Y ( n103 ) ) ;
AO221X1_RVT U67 (.A5 ( rst ) , .A1 ( rx_valid_r ) , .A4 ( rx_en ) , .Y ( n64 ) 
    , .A2 ( n36 ) , .A3 ( n21 ) ) ;
OR3X2_RVT U68 (.A1 ( n56 ) , .A3 ( n7 ) , .Y ( n54 ) , .A2 ( rst ) ) ;
INVX0_RVT U69 (.A ( n49 ) , .Y ( n35 ) ) ;
NAND2X0_RVT U70 (.A2 ( n54 ) , .A1 ( n49 ) , .Y ( n51 ) ) ;
AND2X1_RVT U71 (.Y ( n52 ) , .A1 ( n112 ) , .A2 ( n49 ) ) ;
OR2X1_RVT U72 (.Y ( n30 ) , .A2 ( n18 ) , .A1 ( rst ) ) ;
NAND2X0_RVT U73 (.A2 ( n115 ) , .A1 ( n116 ) , .Y ( n75 ) ) ;
AO22X1_RVT U74 (.A2 ( n4 ) , .A3 ( n27 ) , .Y ( n125 ) , .A4 ( n116 ) 
    , .A1 ( n26 ) ) ;
AO21X1_RVT U75 (.A1 ( n23 ) , .Y ( n124 ) , .A2 ( n9 ) , .A3 ( n24 ) ) ;
NOR2X0_RVT U76 (.Y ( n34 ) , .A2 ( n15 ) , .A1 ( n29 ) ) ;
INVX0_RVT U77 (.A ( n30 ) , .Y ( n19 ) ) ;
AO21X1_RVT U78 (.A1 ( one_cnt[2] ) , .Y ( n127 ) , .A2 ( n32 ) , .A3 ( n33 ) ) ;
AO22X1_RVT U79 (.A2 ( one_cnt[1] ) , .A3 ( n38 ) , .Y ( n128 ) 
    , .A4 ( one_cnt[0] ) , .A1 ( n37 ) ) ;
AO21X1_RVT U80 (.A1 ( n34 ) , .Y ( n32 ) , .A2 ( n10 ) , .A3 ( n37 ) ) ;
OAI22X1_RVT U81 (.Y ( n126 ) , .A4 ( n31 ) , .A3 ( n30 ) , .A2 ( n5 ) 
    , .A1 ( n29 ) ) ;
NAND2X0_RVT U82 (.A2 ( n5 ) , .A1 ( n29 ) , .Y ( n31 ) ) ;
AO22X1_RVT U83 (.A2 ( n47 ) , .A3 ( n19 ) , .Y ( n26 ) , .A4 ( n29 ) 
    , .A1 ( n117 ) ) ;
AO21X1_RVT U84 (.A1 ( n116 ) , .Y ( n23 ) , .A2 ( n47 ) , .A3 ( n26 ) ) ;
INVX0_RVT U85 (.A ( n29 ) , .Y ( n47 ) ) ;
NAND2X0_RVT U87 (.A2 ( n119 ) , .A1 ( n50 ) , .Y ( n29 ) ) ;
AND2X1_RVT U88 (.Y ( n41 ) , .A1 ( n19 ) , .A2 ( n40 ) ) ;
NAND2X0_RVT U89 (.A2 ( fs_ce ) , .A1 ( n19 ) , .Y ( n40 ) ) ;
INVX0_RVT U90 (.A ( n40 ) , .Y ( n50 ) ) ;
NOR4X1_RVT U86 (.Y ( n120 ) , .A4 ( se0_s ) , .A2 ( n36 ) , .A3 ( n110 ) 
    , .A1 ( RxActive_o ) ) ;
DFFX1_RVT \one_cnt_reg[2] (.QN ( n11 ) , .D ( n127 ) , .CLK ( clk ) 
    , .Q ( one_cnt[2] ) ) ;
DFFX1_RVT \bit_cnt_reg[2] (.QN ( n115 ) , .D ( n124 ) , .CLK ( clk ) , .Q ( n9 ) ) ;
DFFX1_RVT rxd_s1_reg (.D ( rxd_s0 ) , .CLK ( clk ) , .Q ( rxd_s1 ) ) ;
DFFX1_RVT \hold_reg_reg[0] (.D ( n91 ) , .CLK ( clk ) , .Q ( DataIn_o[0] ) ) ;
DFFX1_RVT rx_valid_r_reg (.D ( n136 ) , .CLK ( clk ) , .Q ( rx_valid_r ) ) ;
DFFX1_RVT rx_valid1_reg (.D ( n123 ) , .CLK ( clk ) , .Q ( rx_valid1 ) ) ;
DFFX1_RVT rxd_s0_reg (.D ( rxd ) , .CLK ( clk ) , .Q ( rxd_s0 ) ) ;
DFFSSRX1_RVT rx_valid_reg (.Q ( RxValid_o ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( rx_valid1 ) , .RSTB ( n46 ) ) ;
DFFX1_RVT sd_r_reg (.D ( n100 ) , .CLK ( clk ) , .Q ( sd_r ) ) ;
DFFX1_RVT \dpll_state_reg[0] (.D ( N31 ) , .CLK ( clk ) , .Q ( n1 ) ) ;
DFFX1_RVT byte_err_reg (.QN ( n78 ) , .D ( N166 ) , .CLK ( clk ) ) ;
SDFFSSRX1_RVT bit_stuff_err_reg (.SI ( 1'b0 ), .D ( RxActive_o ) , .SE ( n119 ) 
    , .RSTB ( n122 ) , .QN ( n77 ) , .SETB ( 1'b1 ), .CLK ( clk ) ) ;
DFFSSRX1_RVT se0_r_reg (.QN ( n76 ) , .SETB ( 1'b1 ), .CLK ( clk ) , .D ( n42 ) 
    , .RSTB ( n39 ) ) ;
DFFSSRX1_RVT sync_err_reg (.QN ( n79 ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( N87 ) , .RSTB ( n120 ) ) ;
DFFSSRX1_RVT \dpll_state_reg[1] (.QN ( n2 ) , .SETB ( n103 ) , .CLK ( clk ) 
    , .D ( n121 ) , .RSTB ( IN0 ) ) ;
DFFX1_RVT se0_s_reg (.D ( n101 ) , .CLK ( clk ) , .Q ( se0_s ) ) ;
DFFX1_RVT rxd_r_reg (.D ( rxd_s ) , .CLK ( clk ) , .Q ( rxd_r ) ) ;
DFFX1_RVT rx_en_reg (.D ( RxEn_i ) , .CLK ( clk ) , .Q ( rx_en ) ) ;
DFFX1_RVT rxdp_s1_reg (.D ( rxdp_s0 ) , .CLK ( clk ) , .Q ( LineState[0] ) ) ;
DFFX1_RVT rxdn_s1_reg (.D ( rxdn_s0 ) , .CLK ( clk ) , .Q ( LineState[1] ) ) ;
DFFX1_RVT \bit_cnt_reg[0] (.QN ( n117 ) , .D ( n126 ) , .CLK ( clk ) , .Q ( n5 ) ) ;
DFFX1_RVT \fs_state_reg[0] (.QN ( n113 ) , .D ( n133 ) , .CLK ( clk ) , .Q ( n7 ) ) ;
DFFX1_RVT \fs_state_reg[2] (.QN ( n111 ) , .D ( n131 ) , .CLK ( clk ) ) ;
DFFX1_RVT \bit_cnt_reg[1] (.QN ( n116 ) , .D ( n125 ) , .CLK ( clk ) , .Q ( n4 ) ) ;
DFFX1_RVT \fs_state_reg[1] (.QN ( n112 ) , .D ( n132 ) , .CLK ( clk ) , .Q ( n8 ) ) ;
SDFFSSRX1_RVT rxdp_s_reg (.SI ( 1'b1 ), .D ( rxdp_s0 ) , .SE ( rxdp_s_r ) 
    , .RSTB ( LineState[0] ) , .QN ( n39 ) , .Q ( rxdp_s ) , .SETB ( 1'b1 )
    , .CLK ( clk ) ) ;
SDFFSSRX1_RVT rxdn_s_reg (.SI ( 1'b1 ), .D ( rxdn_s0 ) , .SE ( rxdn_s_r ) 
    , .RSTB ( LineState[1] ) , .QN ( n42 ) , .Q ( rxdn_s ) , .SETB ( 1'b1 )
    , .CLK ( clk ) ) ;
DFFX1_RVT rxd_s_reg (.D ( n137 ) , .CLK ( clk ) , .Q ( rxd_s ) ) ;
DFFX1_RVT \one_cnt_reg[1] (.QN ( n10 ) , .D ( n128 ) , .CLK ( clk ) 
    , .Q ( one_cnt[1] ) ) ;
DFFX1_RVT \one_cnt_reg[0] (.QN ( n6 ) , .D ( n129 ) , .CLK ( clk ) 
    , .Q ( one_cnt[0] ) ) ;
DFFX1_RVT fs_ce_r2_reg (.D ( fs_ce_r1 ) , .CLK ( clk ) , .Q ( fs_ce_r2 ) ) ;
DFFX1_RVT rxdp_s0_reg (.D ( rxdp ) , .CLK ( clk ) , .Q ( rxdp_s0 ) ) ;
DFFX1_RVT rxdn_s0_reg (.D ( rxdn ) , .CLK ( clk ) , .Q ( rxdn_s0 ) ) ;
DFFSSRX1_RVT fs_ce_r1_reg (.Q ( fs_ce_r1 ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( n1 ) , .RSTB ( n2 ) ) ;
DFFSSRX1_RVT rxdp_s_r_reg (.Q ( rxdp_s_r ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( rxdp_s0 ) , .RSTB ( LineState[0] ) ) ;
DFFSSRX1_RVT rxdn_s_r_reg (.Q ( rxdn_s_r ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( rxdn_s0 ) , .RSTB ( LineState[1] ) ) ;
DFFX1_RVT fs_ce_reg (.QN ( n110 ) , .D ( fs_ce_r2 ) , .CLK ( clk ) 
    , .Q ( fs_ce ) ) ;
DFFX1_RVT rx_active_reg (.QN ( n114 ) , .D ( n135 ) , .CLK ( clk ) 
    , .Q ( RxActive_o ) ) ;
DFFX1_RVT shift_en_reg (.QN ( n18 ) , .D ( n130 ) , .CLK ( clk ) 
    , .Q ( shift_en ) ) ;
DFFX1_RVT sd_nrzi_reg (.QN ( n15 ) , .D ( n134 ) , .CLK ( clk ) , .Q ( sd_nrzi ) ) ;
DFFX1_RVT \hold_reg_reg[6] (.D ( n97 ) , .CLK ( clk ) , .Q ( DataIn_o[6] ) ) ;
endmodule




module usb_tx_phy (TxReady_o , IN0 , clk , rst , fs_ce , phy_mode , 
    TxValid_i , txdp , txdn , txoe , DataOut_i );
output TxReady_o ;
input  IN0 ;
input  clk ;
input  rst ;
input  fs_ce ;
input  phy_mode ;
input  TxValid_i ;
output txdp ;
output txdn ;
output txoe ;
input  [7:0] DataOut_i ;


wire [2:0] state ;
wire [7:0] hold_reg ;
wire [2:0] bit_cnt ;
wire [7:0] hold_reg_d ;
wire [2:0] one_cnt ;

INVX1_RVT U4 (.A ( n4 ) , .Y ( n27 ) ) ;
INVX1_RVT U3 (.A ( n54 ) , .Y ( n21 ) ) ;
INVX1_RVT U2 (.A ( n66 ) , .Y ( n8 ) ) ;
INVX0_RVT U1 (.A ( fs_ce ) , .Y ( n7 ) ) ;
INVX1_RVT U54 (.A ( n58 ) , .Y ( n68 ) ) ;
NAND3X0_RVT U55 (.Y ( n58 ) , .A1 ( TxValid_i ) , .A2 ( IN0 ) , .A3 ( tx_ip ) ) ;
AND2X1_RVT U56 (.Y ( n38 ) , .A1 ( tx_ip_sync ) , .A2 ( IN0 ) ) ;
AND2X1_RVT U57 (.Y ( n36 ) , .A1 ( n38 ) , .A2 ( txoe_r1 ) ) ;
AND2X1_RVT U58 (.Y ( n37 ) , .A1 ( sd_bs_o ) , .A2 ( n26 ) ) ;
NAND3X0_RVT U59 (.Y ( n69 ) , .A1 ( IN0 ) , .A2 ( n70 ) , .A3 ( n71 ) ) ;
OR2X1_RVT U60 (.Y ( n70 ) , .A2 ( n76 ) , .A1 ( n64 ) ) ;
OA221X1_RVT U61 (.A1 ( state[2] ) , .A4 ( n7 ) , .A2 ( n72 ) , .A5 ( n56 ) 
    , .Y ( n71 ) , .A3 ( n73 ) ) ;
OA22X1_RVT U62 (.Y ( n73 ) , .A4 ( n5 ) , .A3 ( append_eop_sync3 ) , .A2 ( n23 ) 
    , .A1 ( n74 ) ) ;
AO21X1_RVT U63 (.A1 ( n8 ) , .Y ( n65 ) , .A2 ( n20 ) , .A3 ( n27 ) ) ;
AO221X1_RVT U64 (.A5 ( n28 ) , .A1 ( hold_reg[7] ) , .A4 ( n21 ) , .Y ( n93 ) 
    , .A2 ( n54 ) , .A3 ( DataOut_i[7] ) ) ;
INVX1_RVT U65 (.A ( n56 ) , .Y ( n28 ) ) ;
NAND4X0_RVT U66 (.A2 ( n25 ) , .A4 ( n23 ) , .A3 ( n24 ) , .Y ( n56 ) 
    , .A1 ( TxValid_i ) ) ;
AO22X1_RVT U67 (.A2 ( n21 ) , .A3 ( hold_reg[0] ) , .Y ( n100 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[0] ) ) ;
AO22X1_RVT U68 (.A2 ( n21 ) , .A3 ( hold_reg[1] ) , .Y ( n99 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[1] ) ) ;
AO22X1_RVT U69 (.A2 ( n21 ) , .A3 ( hold_reg[2] ) , .Y ( n98 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[2] ) ) ;
AO22X1_RVT U70 (.A2 ( n21 ) , .A3 ( hold_reg[3] ) , .Y ( n97 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[3] ) ) ;
AO22X1_RVT U71 (.A2 ( n21 ) , .A3 ( hold_reg[4] ) , .Y ( n96 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[4] ) ) ;
AO22X1_RVT U72 (.A2 ( n21 ) , .A3 ( hold_reg[5] ) , .Y ( n95 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[5] ) ) ;
AO22X1_RVT U73 (.A2 ( n21 ) , .A3 ( hold_reg[6] ) , .Y ( n94 ) , .A4 ( n55 ) 
    , .A1 ( DataOut_i[6] ) ) ;
NAND2X0_RVT U74 (.A2 ( n56 ) , .A1 ( ld_data ) , .Y ( n54 ) ) ;
OA22X1_RVT U75 (.Y ( n74 ) , .A4 ( n19 ) , .A3 ( n25 ) 
    , .A2 ( append_eop_sync3 ) , .A1 ( state[1] ) ) ;
AND2X1_RVT U76 (.Y ( n72 ) , .A1 ( n5 ) , .A2 ( n75 ) ) ;
NAND3X0_RVT U77 (.Y ( n75 ) , .A1 ( state[0] ) , .A2 ( state[1] ) 
    , .A3 ( append_eop_sync3 ) ) ;
AND3X1_RVT U78 (.A1 ( n42 ) , .Y ( N88 ) , .A2 ( n47 ) , .A3 ( bit_cnt[2] ) ) ;
AO22X1_RVT U79 (.A2 ( n78 ) , .A3 ( n79 ) , .Y ( n77 ) , .A4 ( n11 ) 
    , .A1 ( bit_cnt[2] ) ) ;
AO222X1_RVT U80 (.A1 ( hold_reg_d[1] ) , .A5 ( hold_reg_d[3] ) , .A6 ( n42 ) 
    , .A3 ( n80 ) , .A2 ( n45 ) , .Y ( n79 ) , .A4 ( n13 ) ) ;
AO222X1_RVT U81 (.A1 ( hold_reg_d[5] ) , .A5 ( hold_reg_d[7] ) , .A6 ( n42 ) 
    , .A3 ( n81 ) , .A2 ( n45 ) , .Y ( n78 ) , .A4 ( n13 ) ) ;
AO22X1_RVT U82 (.A2 ( bit_cnt[1] ) , .A3 ( hold_reg_d[0] ) , .Y ( n80 ) 
    , .A4 ( n12 ) , .A1 ( hold_reg_d[2] ) ) ;
AND2X1_RVT U83 (.Y ( n42 ) , .A1 ( bit_cnt[1] ) , .A2 ( bit_cnt[0] ) ) ;
AO22X1_RVT U84 (.A2 ( bit_cnt[1] ) , .A3 ( hold_reg_d[4] ) , .Y ( n81 ) 
    , .A4 ( n12 ) , .A1 ( hold_reg_d[6] ) ) ;
OR4X1_RVT U85 (.A4 ( state[0] ) , .A3 ( data_done ) , .A1 ( n76 ) , .Y ( n5 ) 
    , .A2 ( n24 ) ) ;
AND2X1_RVT U86 (.Y ( n45 ) , .A1 ( bit_cnt[0] ) , .A2 ( n12 ) ) ;
NAND3X0_RVT U87 (.Y ( n64 ) , .A1 ( n24 ) , .A2 ( n23 ) , .A3 ( state[0] ) ) ;
NAND3X0_RVT U88 (.Y ( n47 ) , .A1 ( one_cnt[1] ) , .A2 ( n17 ) 
    , .A3 ( one_cnt[2] ) ) ;
NAND3X0_RVT U89 (.Y ( n82 ) , .A1 ( data_done ) , .A2 ( n25 ) , .A3 ( state[1] ) ) ;
NAND2X0_RVT U91 (.A2 ( n14 ) , .A1 ( sft_done ) , .Y ( n76 ) ) ;
INVX1_RVT U92 (.A ( phy_mode ) , .Y ( n114 ) ) ;
AND2X1_RVT U93 (.Y ( n60 ) , .A1 ( tx_ip ) , .A2 ( n19 ) ) ;
AND2X1_RVT U94 (.Y ( n67 ) , .A1 ( append_eop ) , .A2 ( n18 ) ) ;
AO22X1_RVT U96 (.A2 ( one_cnt[0] ) , .A3 ( n39 ) , .Y ( n92 ) , .A4 ( n17 ) 
    , .A1 ( n52 ) ) ;
AO22X1_RVT U97 (.A2 ( n8 ) , .A3 ( append_eop_sync3 ) , .Y ( n109 ) 
    , .A4 ( n65 ) , .A1 ( append_eop_sync2 ) ) ;
AO221X1_RVT U98 (.A5 ( rst ) , .A1 ( n59 ) , .A4 ( n27 ) , .Y ( n102 ) 
    , .A2 ( n8 ) , .A3 ( txoe ) ) ;
AO21X1_RVT U99 (.A1 ( n39 ) , .Y ( n48 ) , .A2 ( n16 ) , .A3 ( n50 ) ) ;
AND4X1_RVT U100 (.Y ( n49 ) , .A1 ( one_cnt[0] ) , .A3 ( one_cnt[1] ) 
    , .A4 ( n15 ) , .A2 ( n39 ) ) ;
AO21X1_RVT U101 (.A1 ( n39 ) , .Y ( n50 ) , .A2 ( n17 ) , .A3 ( n52 ) ) ;
AND3X1_RVT U102 (.A1 ( n26 ) , .Y ( n39 ) , .A2 ( n47 ) , .A3 ( sd_raw_o ) ) ;
INVX0_RVT U103 (.A ( n53 ) , .Y ( n26 ) ) ;
NAND2X0_RVT U104 (.A2 ( fs_ce ) , .A1 ( IN0 ) , .Y ( n66 ) ) ;
DFFX1_RVT \hold_reg_d_reg[2] (.D ( hold_reg[2] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[2] ) ) ;
DFFX1_RVT txdn_reg (.D ( n84 ) , .CLK ( clk ) , .Q ( txdn ) ) ;
DFFX1_RVT \hold_reg_d_reg[4] (.D ( hold_reg[4] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[4] ) ) ;
DFFX1_RVT \hold_reg_d_reg[0] (.D ( hold_reg[0] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[0] ) ) ;
DFFX1_RVT \hold_reg_d_reg[5] (.D ( hold_reg[5] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[5] ) ) ;
DFFX1_RVT \hold_reg_d_reg[1] (.D ( hold_reg[1] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[1] ) ) ;
DFFX1_RVT txdp_reg (.D ( n83 ) , .CLK ( clk ) , .Q ( txdp ) ) ;
DFFX1_RVT \hold_reg_d_reg[3] (.D ( hold_reg[3] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[3] ) ) ;
DFFX1_RVT \hold_reg_d_reg[7] (.D ( hold_reg[7] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[7] ) ) ;
DFFX1_RVT append_eop_sync1_reg (.D ( n111 ) , .CLK ( clk ) 
    , .Q ( append_eop_sync1 ) ) ;
DFFX1_RVT sd_bs_o_reg (.D ( n86 ) , .CLK ( clk ) , .Q ( sd_bs_o ) ) ;
DFFX1_RVT \hold_reg_reg[7] (.D ( n93 ) , .CLK ( clk ) , .Q ( hold_reg[7] ) ) ;
DFFX1_RVT txoe_reg (.D ( n102 ) , .CLK ( clk ) , .Q ( txoe ) ) ;
DFFX1_RVT \hold_reg_reg[6] (.D ( n94 ) , .CLK ( clk ) , .Q ( hold_reg[6] ) ) ;
DFFX1_RVT \hold_reg_reg[5] (.D ( n95 ) , .CLK ( clk ) , .Q ( hold_reg[5] ) ) ;
DFFX1_RVT \hold_reg_reg[4] (.D ( n96 ) , .CLK ( clk ) , .Q ( hold_reg[4] ) ) ;
DFFX1_RVT \hold_reg_reg[3] (.D ( n97 ) , .CLK ( clk ) , .Q ( hold_reg[3] ) ) ;
DFFX1_RVT \hold_reg_reg[2] (.D ( n98 ) , .CLK ( clk ) , .Q ( hold_reg[2] ) ) ;
DFFX1_RVT \hold_reg_reg[1] (.D ( n99 ) , .CLK ( clk ) , .Q ( hold_reg[1] ) ) ;
DFFX1_RVT \hold_reg_reg[0] (.D ( n100 ) , .CLK ( clk ) , .Q ( hold_reg[0] ) ) ;
DFFX1_RVT txoe_r2_reg (.D ( n103 ) , .CLK ( clk ) , .Q ( txoe_r2 ) ) ;
DFFX1_RVT sd_nrzi_o_reg (.D ( n85 ) , .CLK ( clk ) , .Q ( sd_nrzi_o ) ) ;
DFFSSRX1_RVT append_eop_reg (.Q ( append_eop ) , .SETB ( n5 ) , .CLK ( clk ) 
    , .D ( n67 ) , .RSTB ( IN0 ) ) ;
DFFSSRX1_RVT tx_ip_reg (.Q ( tx_ip ) , .SETB ( n56 ) , .CLK ( clk ) , .D ( n60 ) 
    , .RSTB ( IN0 ) ) ;
DFFX1_RVT data_done_reg (.D ( n101 ) , .CLK ( clk ) , .Q ( data_done ) ) ;
DFFSSRX1_RVT sd_raw_o_reg (.Q ( sd_raw_o ) , .SETB ( 1'b1 ), .CLK ( clk ) 
    , .D ( tx_ip_sync ) , .RSTB ( n77 ) ) ;
DFFX1_RVT txoe_r1_reg (.D ( n104 ) , .CLK ( clk ) , .Q ( txoe_r1 ) ) ;
DFFX1_RVT sft_done_r_reg (.QN ( n14 ) , .D ( sft_done ) , .CLK ( clk ) ) ;
SDFFSSRX1_RVT ld_data_reg (.SI ( 1'b0 ), .D ( n31 ) , .SE ( n2 ) , .RSTB ( n14 ) 
    , .Q ( ld_data ) , .SETB ( n82 ) , .CLK ( clk ) ) ;
DFFX1_RVT TxReady_o_reg (.D ( N18 ) , .CLK ( clk ) , .Q ( TxReady_o ) ) ;
DFFX1_RVT sft_done_reg (.QN ( n2 ) , .D ( N88 ) , .CLK ( clk ) , .Q ( sft_done ) ) ;
DFFX1_RVT \state_reg[0] (.QN ( n25 ) , .D ( n112 ) , .CLK ( clk ) 
    , .Q ( state[0] ) ) ;
DFFX1_RVT \state_reg[2] (.QN ( n23 ) , .D ( n106 ) , .CLK ( clk ) 
    , .Q ( state[2] ) ) ;
DFFX1_RVT \state_reg[1] (.QN ( n24 ) , .D ( n107 ) , .CLK ( clk ) 
    , .Q ( state[1] ) ) ;
DFFX1_RVT tx_ip_sync_reg (.QN ( n6 ) , .D ( n105 ) , .CLK ( clk ) 
    , .Q ( tx_ip_sync ) ) ;
DFFX1_RVT append_eop_sync2_reg (.QN ( n18 ) , .D ( n110 ) , .CLK ( clk ) 
    , .Q ( append_eop_sync2 ) ) ;
DFFX1_RVT append_eop_sync4_reg (.QN ( n20 ) , .D ( n108 ) , .CLK ( clk ) 
    , .Q ( append_eop_sync4 ) ) ;
DFFX1_RVT append_eop_sync3_reg (.QN ( n19 ) , .D ( n109 ) , .CLK ( clk ) 
    , .Q ( append_eop_sync3 ) ) ;
DFFX1_RVT \bit_cnt_reg[0] (.QN ( n13 ) , .D ( n88 ) , .CLK ( clk ) 
    , .Q ( bit_cnt[0] ) ) ;
DFFX1_RVT \one_cnt_reg[0] (.QN ( n17 ) , .D ( n92 ) , .CLK ( clk ) 
    , .Q ( one_cnt[0] ) ) ;
DFFX1_RVT \bit_cnt_reg[1] (.QN ( n12 ) , .D ( n89 ) , .CLK ( clk ) 
    , .Q ( bit_cnt[1] ) ) ;
DFFX1_RVT \bit_cnt_reg[2] (.QN ( n11 ) , .D ( n87 ) , .CLK ( clk ) 
    , .Q ( bit_cnt[2] ) ) ;
DFFX1_RVT \one_cnt_reg[1] (.QN ( n16 ) , .D ( n91 ) , .CLK ( clk ) 
    , .Q ( one_cnt[1] ) ) ;
DFFX1_RVT \one_cnt_reg[2] (.QN ( n15 ) , .D ( n90 ) , .CLK ( clk ) 
    , .Q ( one_cnt[2] ) ) ;
INVX1_RVT U5 (.A ( n46 ) , .Y ( n22 ) ) ;
AND2X1_RVT U8 (.Y ( n44 ) , .A1 ( n38 ) , .A2 ( n46 ) ) ;
NAND2X0_RVT U9 (.A2 ( n47 ) , .A1 ( n26 ) , .Y ( n46 ) ) ;
NAND2X0_RVT U11 (.A2 ( n66 ) , .A1 ( IN0 ) , .Y ( n4 ) ) ;
INVX1_RVT U12 (.A ( n69 ) , .Y ( n10 ) ) ;
AND2X1_RVT U13 (.Y ( n63 ) , .A1 ( IN0 ) , .A2 ( n69 ) ) ;
AND2X1_RVT U14 (.Y ( n52 ) , .A1 ( n38 ) , .A2 ( n53 ) ) ;
AND2X1_RVT U16 (.Y ( n55 ) , .A1 ( n54 ) , .A2 ( n56 ) ) ;
INVX1_RVT U17 (.A ( n64 ) , .Y ( n31 ) ) ;
AO21X1_RVT U18 (.A1 ( n22 ) , .Y ( n43 ) , .A2 ( n13 ) , .A3 ( n44 ) ) ;
AO21X1_RVT U19 (.A1 ( sd_bs_o ) , .Y ( n86 ) , .A2 ( n27 ) , .A3 ( n39 ) ) ;
AO22X1_RVT U20 (.A2 ( n50 ) , .A3 ( n51 ) , .Y ( n91 ) , .A4 ( one_cnt[0] ) 
    , .A1 ( one_cnt[1] ) ) ;
AND2X1_RVT U21 (.Y ( n51 ) , .A1 ( n39 ) , .A2 ( n16 ) ) ;
AO22X1_RVT U22 (.A2 ( n40 ) , .A3 ( n41 ) , .Y ( n87 ) , .A4 ( n22 ) 
    , .A1 ( bit_cnt[2] ) ) ;
AND2X1_RVT U23 (.Y ( n41 ) , .A1 ( n42 ) , .A2 ( n11 ) ) ;
AO21X1_RVT U24 (.A1 ( n22 ) , .Y ( n40 ) , .A2 ( n12 ) , .A3 ( n43 ) ) ;
AO22X1_RVT U25 (.A2 ( n43 ) , .A3 ( n45 ) , .Y ( n89 ) , .A4 ( n22 ) 
    , .A1 ( bit_cnt[1] ) ) ;
AO22X1_RVT U26 (.A2 ( bit_cnt[0] ) , .A3 ( n22 ) , .Y ( n88 ) , .A4 ( n13 ) 
    , .A1 ( n44 ) ) ;
AO21X1_RVT U27 (.A1 ( one_cnt[2] ) , .Y ( n90 ) , .A2 ( n48 ) , .A3 ( n49 ) ) ;
OR2X1_RVT U28 (.Y ( n53 ) , .A2 ( n66 ) , .A1 ( n6 ) ) ;
AO22X1_RVT U29 (.A2 ( n34 ) , .A3 ( n9 ) , .Y ( n85 ) , .A4 ( n35 ) 
    , .A1 ( sd_nrzi_o ) ) ;
NAND2X0_RVT U30 (.A2 ( sd_nrzi_o ) , .A1 ( n36 ) , .Y ( n35 ) ) ;
INVX1_RVT U31 (.A ( n34 ) , .Y ( n9 ) ) ;
AO22X1_RVT U32 (.A2 ( n7 ) , .A3 ( n37 ) , .Y ( n34 ) , .A4 ( txoe_r1 ) 
    , .A1 ( n36 ) ) ;
AND3X1_RVT U33 (.A1 ( TxValid_i ) , .Y ( N18 ) , .A2 ( IN0 ) 
    , .A3 ( tx_ready_d ) ) ;
AOI21X1_RVT U34 (.Y ( tx_ready_d ) , .A2 ( n82 ) , .A3 ( n76 ) , .A1 ( n64 ) ) ;
AO221X1_RVT U35 (.A5 ( rst ) , .A1 ( n30 ) , .A4 ( n27 ) , .Y ( n83 ) 
    , .A2 ( sd_nrzi_o ) , .A3 ( txdp ) ) ;
OA21X1_RVT U36 (.Y ( n30 ) , .A3 ( n8 ) , .A2 ( n114 ) , .A1 ( n19 ) ) ;
NOR2X0_RVT U37 (.Y ( n59 ) , .A2 ( txoe_r2 ) , .A1 ( txoe_r1 ) ) ;
AO21X1_RVT U38 (.A1 ( IN0 ) , .Y ( n61 ) , .A2 ( n25 ) , .A3 ( n10 ) ) ;
AO21X1_RVT U39 (.A1 ( txoe_r1 ) , .Y ( n104 ) , .A2 ( n27 ) , .A3 ( n26 ) ) ;
AO22X1_RVT U40 (.A2 ( n27 ) , .A3 ( append_eop ) , .Y ( n111 ) , .A4 ( n8 ) 
    , .A1 ( append_eop_sync1 ) ) ;
AO22X1_RVT U41 (.A2 ( state[0] ) , .A3 ( n63 ) , .Y ( n112 ) , .A4 ( n25 ) 
    , .A1 ( n10 ) ) ;
AO22X1_RVT U42 (.A2 ( n27 ) , .A3 ( txoe_r1 ) , .Y ( n103 ) , .A4 ( n8 ) 
    , .A1 ( txoe_r2 ) ) ;
AO22X1_RVT U43 (.A2 ( n27 ) , .A3 ( n8 ) , .Y ( n84 ) , .A4 ( n32 ) 
    , .A1 ( txdn ) ) ;
AO22X1_RVT U44 (.A2 ( n114 ) , .A3 ( n33 ) , .Y ( n32 ) , .A4 ( phy_mode ) 
    , .A1 ( append_eop_sync3 ) ) ;
NOR2X0_RVT U45 (.Y ( n33 ) , .A2 ( sd_nrzi_o ) , .A1 ( append_eop_sync3 ) ) ;
AO22X1_RVT U46 (.A2 ( n27 ) , .A3 ( n8 ) , .Y ( n108 ) 
    , .A4 ( append_eop_sync3 ) , .A1 ( append_eop_sync4 ) ) ;
AO22X1_RVT U47 (.A2 ( n27 ) , .A3 ( append_eop_sync1 ) , .Y ( n110 ) 
    , .A4 ( n8 ) , .A1 ( append_eop_sync2 ) ) ;
AO22X1_RVT U48 (.A2 ( n27 ) , .A3 ( tx_ip ) , .Y ( n105 ) , .A4 ( n8 ) 
    , .A1 ( tx_ip_sync ) ) ;
AO22X1_RVT U49 (.A2 ( n61 ) , .A3 ( n62 ) , .Y ( n106 ) , .A4 ( n63 ) 
    , .A1 ( state[2] ) ) ;
AND2X1_RVT U50 (.Y ( n62 ) , .A1 ( state[0] ) , .A2 ( state[1] ) ) ;
AO22X1_RVT U51 (.A2 ( n61 ) , .A3 ( n63 ) , .Y ( n107 ) , .A4 ( n31 ) 
    , .A1 ( state[1] ) ) ;
AO22X1_RVT U52 (.A2 ( data_done ) , .A3 ( n57 ) , .Y ( n101 ) 
    , .A4 ( TxValid_i ) , .A1 ( n68 ) ) ;
AND2X1_RVT U53 (.Y ( n57 ) , .A1 ( IN0 ) , .A2 ( n58 ) ) ;
DFFX1_RVT \hold_reg_d_reg[6] (.D ( hold_reg[6] ) , .CLK ( clk ) 
    , .Q ( hold_reg_d[6] ) ) ;
endmodule




module usb_phy (DataOut_i , DataIn_o , LineState_o , TxValid_i , rxdn , 
    rxdp , rxd , phy_tx_mode , rst , clk , RxError_o , RxActive_o , 
    RxValid_o , TxReady_o , txoe , txdn , txdp , usb_rst );
input  [7:0] DataOut_i ;
output [7:0] DataIn_o ;
output [1:0] LineState_o ;
input  TxValid_i ;
input  rxdn ;
input  rxdp ;
input  rxd ;
input  phy_tx_mode ;
input  rst ;
input  clk ;
output RxError_o ;
output RxActive_o ;
output RxValid_o ;
output TxReady_o ;
output txoe ;
output txdn ;
output txdp ;
output usb_rst ;


wire [4:0] rst_cnt ;
wire [4:2] \add_178_S2/carry ;


usb_rx_phy i_rx_phy (.fs_ce ( fs_ce ) , .RxValid_o ( RxValid_o ) , 
    .RxActive_o ( RxActive_o ) , .RxError_o ( RxError_o ) , .IN0 ( rst ) , 
    .LineState ( LineState_o ) , .clk ( clk ) , .rst ( n1 ) , .rxd ( rxd ) , 
    .rxdp ( rxdp ) , .rxdn ( rxdn ) , .RxEn_i ( txoe ) , .DataIn_o ( DataIn_o ) ) ;


usb_tx_phy i_tx_phy (.TxReady_o ( TxReady_o ) , .IN0 ( rst ) , .clk ( clk ) , 
    .rst ( n1 ) , .fs_ce ( fs_ce ) , .phy_mode ( phy_tx_mode ) , 
    .TxValid_i ( TxValid_i ) , .txdp ( txdp ) , .txdn ( txdn ) , .txoe ( txoe ) , 
    .DataOut_i ( DataOut_i ) ) ;

INVX1_RVT U1 (.A ( rst ) , .Y ( n1 ) ) ;
DFFX1_RVT \rst_cnt_reg[2] (.D ( n10 ) , .CLK ( clk ) , .Q ( rst_cnt[2] ) ) ;
DFFX1_RVT \rst_cnt_reg[3] (.D ( n9 ) , .CLK ( clk ) , .Q ( rst_cnt[3] ) ) ;
DFFX1_RVT \rst_cnt_reg[4] (.D ( n8 ) , .CLK ( clk ) , .Q ( rst_cnt[4] ) ) ;
DFFX1_RVT \rst_cnt_reg[1] (.D ( n11 ) , .CLK ( clk ) , .Q ( rst_cnt[1] ) ) ;
DFFX1_RVT \rst_cnt_reg[0] (.QN ( N7 ) , .D ( n12 ) , .CLK ( clk ) 
    , .Q ( rst_cnt[0] ) ) ;
SDFFSSRX1_RVT usb_rst_reg (.SI ( 1'b0 ), .D ( rst_cnt[1] ) , .SE ( N7 ) 
    , .RSTB ( n7 ) , .Q ( usb_rst ) , .SETB ( 1'b1 ), .CLK ( clk ) ) ;
INVX1_RVT U18 (.A ( n5 ) , .Y ( n16 ) ) ;
AO22X1_RVT U19 (.A2 ( n4 ) , .A3 ( N11 ) , .Y ( n8 ) , .A4 ( n16 ) 
    , .A1 ( rst_cnt[4] ) ) ;
AO22X1_RVT U20 (.A2 ( n4 ) , .A3 ( N10 ) , .Y ( n9 ) , .A4 ( n16 ) 
    , .A1 ( rst_cnt[3] ) ) ;
AO22X1_RVT U21 (.A2 ( n4 ) , .A3 ( N9 ) , .Y ( n10 ) , .A4 ( n16 ) 
    , .A1 ( rst_cnt[2] ) ) ;
AO22X1_RVT U22 (.A2 ( n4 ) , .A3 ( N8 ) , .Y ( n11 ) , .A4 ( n16 ) 
    , .A1 ( rst_cnt[1] ) ) ;
AO22X1_RVT U23 (.A2 ( n4 ) , .A3 ( N7 ) , .Y ( n12 ) , .A4 ( n16 ) 
    , .A1 ( rst_cnt[0] ) ) ;
NAND4X0_RVT U24 (.A2 ( fs_ce ) , .A4 ( n17 ) , .A3 ( n6 ) , .Y ( n5 ) 
    , .A1 ( rst ) ) ;
NOR2X0_RVT U25 (.Y ( n6 ) , .A2 ( LineState_o[1] ) , .A1 ( usb_rst ) ) ;
AND4X1_RVT U26 (.Y ( n4 ) , .A1 ( rst ) , .A3 ( n17 ) , .A4 ( n18 ) , .A2 ( n5 ) ) ;
INVX1_RVT U27 (.A ( LineState_o[1] ) , .Y ( n18 ) ) ;
HADDX1_RVT U28 (.SO ( N8 ) , .B0 ( rst_cnt[0] ) , .A0 ( rst_cnt[1] ) 
    , .C1 ( \add_178_S2/carry [2] ) ) ;
HADDX1_RVT U29 (.SO ( N9 ) , .B0 ( \add_178_S2/carry [2] ) , .A0 ( rst_cnt[2] ) 
    , .C1 ( \add_178_S2/carry [3] ) ) ;
HADDX1_RVT U30 (.SO ( N10 ) , .B0 ( \add_178_S2/carry [3] ) , .A0 ( rst_cnt[3] ) 
    , .C1 ( \add_178_S2/carry [4] ) ) ;
INVX1_RVT U31 (.A ( LineState_o[0] ) , .Y ( n17 ) ) ;
AND3X1_RVT U32 (.A1 ( rst_cnt[3] ) , .Y ( n7 ) , .A2 ( rst_cnt[4] ) 
    , .A3 ( rst_cnt[2] ) ) ;
XOR2X1_RVT U34 (.Y ( N11 ) , .A2 ( rst_cnt[4] ) , .A1 ( \add_178_S2/carry [4] ) ) ;
endmodule


